-- Auto-generated by ts-lean-transpiler
-- Source: /workspace/tslean/src/project/index.ts

import TSLean.Generated.SelfHost.codegen_index
import TSLean.Generated.DoModel.Ambient
import TSLean.Generated.SelfHost.ir_types
import TSLean.Generated.SelfHost.parser_index
import TSLean.Generated.SelfHost.rewrite_index
import TSLean.Generated.SelfHost.verification_index
import TSLean.Runtime.Basic
import TSLean.Runtime.Coercions
import TSLean.Runtime.Monad
import TSLean.Stdlib.HashMap

open TSLean TSLean.Stdlib.HashMap

namespace TSLean.Generated.Index

-- // ─── Public API ───────────────────────────────────────────────────────────────
structure ProjectOpts where
  mk ::
  projectDir : String
  outputDir : String
  verify : Option Bool
  rootNS : Option (Option String)
  deriving Repr, BEq

structure ProjectResult where
  mk ::
  files : Array String
  errors : Array String
  deriving Repr, BEq

def transpileProject (opts : ProjectOpts) : StateT Unit IO ProjectResult :=
  do
    let projectDir : String := opts.projectDir
    let outputDir : String := opts.outputDir
    let verify : Bool := Option.getD opts.verify false
    let rootNS : String := Option.getD opts.rootNS "TSLean.Generated"
    if !(fs.existsSync projectDir) then
      pure { files := #[], errors := #[s!"Directory not found: {projectDir}"] }
    else
      let tsFiles : Array String := discoverTs projectDir
      if tsFiles.size == 0 then
        pure { files := #[], errors := #[s!"No .ts files in {projectDir}"] }
      else
        let results : Array String := #[]
        let errors : Array String := #[]
        do
          Array.forM tsFiles (fun f => do
            tryCatch (let src : Any := fs.readFileSync f "utf-8"
          let mod : IRModule := parseFile ({ fileName := f, sourceText := src })
          let rw : IRModule := rewriteModule (fixImports mod f projectDir rootNS)
          let code : String := generateLean rw
          do
            if verify then
              let leanCode : String := generateVerification rw.leanCode
              if leanCode then
                let code := s!"{code}

-- Verification
{leanCode}"
              else
                pure ()
            else
              pure ()
            let lf := toLeanPath f projectDir outputDir rootNS) (fun err => errors.push (s!"{f}: {err.val.message}")))
          return { files := results, errors := errors }

def writeProjectOutputs (result : ProjectResult) : Unit :=
  default

def IGNORED : AssocSet String := AssocSet.empty

partial def discoverTs (dir : String) : Array String :=
  default

-- // ─── Import resolution ────────────────────────────────────────────────────────
def fixImports (mod : IRModule) (tsFile : String) (rootDir : String) (rootNS : String) : IRModule :=
  let fixed : Array IRImport := mod.imports.map (fun imp => if (imp.module.startsWith "TSLean.") || (imp.module.startsWith "Lean") then
    imp
  else
    { imp with module := relToLean imp.module tsFile rootDir rootNS })
  { mod with imports := fixed }

def relToLean (spec : String) (fromFile : String) (rootDir : String) (rootNS : String) : String :=
  let resolved : Option String := resolveSpec spec fromFile
  if !resolved then
    specToLean spec rootNS
  else
    let rel : Any := path.relative rootDir resolved
    let parts : Any := rel.replace "/\\.ts$/" "".split path.sep.filter Boolean.map (fun p => p.replace "/\\.js$/" "".split "/[-_]/".map cap.foldl (· ++ ·) "" "")
    (s!"{rootNS}.") ++ (parts.foldl (· ++ ·) "" ".")

def resolveSpec (spec : String) (fromFile : String) : Option String :=
  default

def specToLean (spec : String) (rootNS : String) : String :=
  let parts : Array String := spec.replace "/^[./]+/" "".replace "/\\.(ts|js)$/" "".split "/".filter Boolean.map (fun p => p.split "/[-_]/".map cap.foldl (· ++ ·) "" "")
  (s!"{rootNS}.") ++ (parts.foldl (· ++ ·) "" ".")

-- // ─── Path helpers ─────────────────────────────────────────────────────────────
def toLeanPath (tsFile : String) (projectDir : String) (outputDir : String) (rootNS : String := "TSLean.Generated") : String :=
  let rel : Any := path.relative projectDir tsFile
  let parts : Any := rel.replace "/\\.ts$/" "".split path.sep.map (fun p => p.split "/[-_]/".map cap.foldl (· ++ ·) "" "")
  (path.foldl (· ++ ·) "" outputDir parts) + ".lean"

def toModuleName (tsFile : String) (projectDir : String) (rootNS : String := "TSLean.Generated") : String :=
  let rel : Any := path.relative projectDir tsFile
  let parts : Any := rel.replace "/\\.ts$/" "".split path.sep.filter Boolean.map (fun p => p.split "/[-_]/".map cap.foldl (· ++ ·) "" "")
  (s!"{rootNS}.") ++ (parts.foldl (· ++ ·) "" ".")

def cap (s : String) : String :=
  if s then
    (s.getD 0 default.toUpper) ++ (s.extract 1)
  else
    s

end TSLean.Generated.Index