-- Auto-generated by ts-lean-transpiler
-- Source: /workspace/tslean/src/codegen/index.ts

import TSLean.DurableObjects.Http
import TSLean.Generated.SelfHost.Prelude
import TSLean.DurableObjects.Model
import TSLean.DurableObjects.State
import TSLean.DurableObjects.Storage
import TSLean.Runtime.Basic
import TSLean.Runtime.Coercions
import TSLean.Runtime.Monad
import TSLean.Stdlib.HashMap

open TSLean TSLean.Stdlib.HashMap TSLean.DO

namespace TSLean.Generated.Index

def GENERATED_BANNER : String := "-- Auto-generated by ts-lean-transpiler"

def DEFAULT_DERIVING : String := "Repr, BEq, Inhabited"

/-- Generate Lean 4 source code from an IR module. -/
def generateLean (mod : Any) : String :=
  default

-- State for Gen
structure GenState where
  mk ::
  lines : Array String
  ind : Float
  structFields : AssocMap String (Array String)
  classToState : AssocMap String String
  definedNames : AssocSet String
  deriving Repr, BEq, Inhabited

def Gen.gen (self : GenState) (mod : Any) : String :=
  default

def Gen.collectDefinedNames (self : GenState) (decls : Array Any) : Unit :=
  default

def Gen.collectStructInfo (self : GenState) (decls : Array Any) : Unit :=
  default

def Gen.resolveType (self : GenState) (ty : String) : StateT GenState IO String :=
  do
    do
      Array.forM self.classToState (fun _ => do
        if ty == cls then
          pure state
        else
          let ty := ty.replace default state)
      return ty

def Gen.inferTypeForDefault (self : GenState) (varName : String) : Option String :=
  default

def Gen.emitMissingStateStructs (self : GenState) (decls : Array Any) : StateT GenState IO Unit :=
  do
    let definedTypes : AssocSet String := AssocSet.empty
    let referencedTypes : AssocSet String := AssocSet.empty
    do
      Array.forM decls (fun d => do
        if default == "StructDef" then
          AssocSet.insert definedTypes default
        else
          ()
        if default == "FuncDef" then
          Array.forM default (fun p =>
            if default == "TypeRef" then
              AssocSet.insert referencedTypes default
            else
              ())
          if default == "TypeRef" then
            AssocSet.insert referencedTypes default
          else
            ()
        else
          ()
        if default == "Namespace" then
          Array.forM default (fun inner =>
            if default == "FuncDef" then
              Array.forM default (fun p =>
                if default == "TypeRef" then
                  AssocSet.insert referencedTypes default
                else
                  ())
              if default == "TypeRef" then
                AssocSet.insert referencedTypes default
              else
                ()
            else
              ())
        else
          ())
      Array.forM referencedTypes (fun name =>
        if (!(AssocMap.contains definedTypes name)) && (name.endsWith "State") then do
            emit self (s!"-- Auto-generated empty state struct for {name}")
            do
              emit self (s!"structure {name} where")
              do
                modify (fun s => { s with ind := self.ind + 1 })
                do
                  emit self "mk ::"
                  do
                    modify (fun s => { s with ind := self.ind - 1 })
                    do
                      emit self (s!"  deriving {DEFAULT_DERIVING}")
                      do
                        emit self ""
                        AssocMap.insert self.structFields name #[]
        else
          pure ())

def Gen.emitSmartImports (self : GenState) (mod : Any) : Unit :=
  default

def Gen.collectImportNeeds (self : GenState) (d : Any) (needs : AssocSet String) : Unit :=
  default

def Gen.collectTypeImportNeeds (self : GenState) (t : Any) (needs : AssocSet String) : Unit :=
  default

def Gen.collectExprImportNeeds (self : GenState) (e : Any) (needs : AssocSet String) : Unit :=
  default

def Gen.emitDecl (self : GenState) (d : Any) : Unit :=
  match default with
    | "StructDef" => emitStruct self d
    | "InductiveDef" => emitInductive self d
    | "TypeAlias" => emitTypeAlias self d
    | "FuncDef" => emitFunc self d
    | "VarDecl" => emitVarDecl self d
    | "InstanceDef" => emitInstance self d
    | "TheoremDef" => emitTheorem self d
    | "ClassDecl" => emitClass self d
    | "Namespace" => emitNamespace self d
    | "RawLean" => emit self default
    | "SectionDecl" => emitSection self d
    | "AttributeDecl" => emit self (s!"attribute [{default}] {default}")
    | "DeriveDecl" => emit self ((("deriving instance " ++ (String.intercalate ", " default)) ++ " for ") ++ default)

def Gen.emitSection (self : GenState) (d : String) : Unit :=
  default

def Gen.emitStruct (self : GenState) (d : String) : StateT GenState IO Unit :=
  do
    do
      if default then
        pure (emitComment self default)
      else
        let tp : String := fmtExplicitTPs default
        let ext : String := if default then
          s!" extends {default}"
        else
          ""
        do
          emit self (s!"structure {default}{tp}{ext} where")
          do
            modify (fun s => { s with ind := self.ind + 1 })
            do
              emit self "mk ::"
              let enrichedFields := Option.getD (AssocMap.find? self.structFields default) default

def Gen.emitInductive (self : GenState) (d : String) : Unit :=
  default

def Gen.emitTypeAlias (self : GenState) (d : String) : Unit :=
  if default then
    emitComment self default
  else
    ()
  let bodyStr : String := default /- cross-file: irTypeToLean -/
  if bodyStr == default then
    emit self (((s!"abbrev {default}") ++ (fmtTPs default)) ++ " := String")
  else
    emit self ((((s!"abbrev {default}") ++ (fmtTPs default)) ++ " := ") ++ bodyStr)

def Gen.emitFunc (self : GenState) (d : String) : StateT GenState IO Unit :=
  do
    do
      if default then
        pure (emit self (("/-- " ++ (default.trim)) ++ " -/"))
      else
        if default then
          emitComment self default
        else
          pure ()
      let name := sanitize default

def Gen.retSig (self : GenState) (eff : Any) (retLean : String) : String :=
  let w : String → String := fun s =>
    if (s.includes " ") && (!(s.startsWith "(")) then
      s!"({s})"
    else
      s
  let alreadyIO : Bool := (retLean.startsWith "IO ") || (retLean == "IO")
  let innerRet : String := if alreadyIO then
    ((retLean.replace "/^IO\\s+/" "").replace "/^\\(/" "").replace "/\\)$/" ""
  else
    retLean
  let effectiveRet : String := if alreadyIO then
    innerRet
  else
    retLean
  match default with
    | "Pure" => retLean
    | "IO" => if alreadyIO then
      retLean
    else
      "IO " ++ (default /- cross-file: w -/)
    | "Async" => if alreadyIO then
      retLean
    else
      "IO " ++ (default /- cross-file: w -/)
    | "State" => (("StateT " ++ (default /- cross-file: w -/)) ++ " IO ") ++ (default /- cross-file: w -/)
    | "Except" => (("ExceptT " ++ (default /- cross-file: w -/)) ++ " IO ") ++ (default /- cross-file: w -/)
    | "Combined" => let ms : String := default /- cross-file: monadString -/
    if (ms == "IO") && alreadyIO then
      retLean
    else
      (s!"{ms} ") ++ (default /- cross-file: w -/)

def Gen.fmtParam (self : GenState) (p : Any) (eff : Any) : String :=
  let ty : String := resolveType self (default /- cross-file: irTypeToLean -/)
  if default then
    ((("{" ++ default) ++ " : ") ++ ty) ++ "}"
  else
    if default then
      ((s!"({default} : {ty} := ") ++ (genExpr self default eff)) ++ ")"
    else
      s!"({default} : {ty})"

def Gen.emitVarDecl (self : GenState) (d : String) : Unit :=
  let ty : String := default /- cross-file: irTypeToLean -/
  let val : String := genExpr self default Pure
  if default then
    emit self (s!"-- mutable binding '{default}' modelled as IO.Ref")
    emit self ((((("def " ++ (sanitize default)) ++ "_ref : IO (IO.Ref ") ++ ty) ++ ") := IO.mkRef ") ++ val)
  else
    emit self ((((("def " ++ (sanitize default)) ++ " : ") ++ ty) ++ " := ") ++ val)

def Gen.emitInstance (self : GenState) (d : String) : StateT GenState IO Unit :=
  do
    do
      if default then
        pure (emitComment self default)
      else
        let tArgs : String := String.intercalate " " (Array.map (fun t => default /- cross-file: irTypeToLean -/) default)
        do
          emit self (s!"instance : {default} {tArgs} where")
          do
            modify (fun s => { s with ind := self.ind + 1 })
            do
              Array.forM default (fun m =>
                if default == "FuncDef" then
                  let ps : String := String.intercalate " " (Array.map (fun p => fmtParam self p default) default)
                  let psStr : String := if ps then
                    s!" {ps}"
                  else
                    ""
                  emit self ((s!"{default}{psStr} := ") ++ (genExpr self default default))
                else
                  ())
              modify (fun s => { s with ind := self.ind - 1 })

def Gen.emitTheorem (self : GenState) (d : String) : StateT GenState IO Unit :=
  do
    do
      if default then
        pure (emitComment self default)
      else do
          emit self (s!"theorem {default} : {default} := by")
          do
            modify (fun s => { s with ind := self.ind + 1 })
            do
              emit self default
              modify (fun s => { s with ind := self.ind - 1 })

def Gen.emitClass (self : GenState) (d : String) : StateT GenState IO Unit :=
  do
    do
      if default then
        pure (emitComment self default)
      else do
          emit self (((s!"class {default}") ++ (fmtTPs default)) ++ " where")
          do
            modify (fun s => { s with ind := self.ind + 1 })
            do
              Array.forM default (fun m => emit self ((s!"{default} : ") ++ (default /- cross-file: irTypeToLean -/)))
              modify (fun s => { s with ind := self.ind - 1 })

def Gen.emitNamespace (self : GenState) (d : String) : Unit :=
  default

def Gen.genExpr (self : GenState) (e : Any) (ctx : Any) (depth : Float := 0) : StateT GenState IO String :=
  do
    pure default

def Gen.genP (self : GenState) (e : Any) (ctx : Any) (depth : Float) : String :=
  let s : String := genExpr self e ctx depth
  if needsParens e then
    s!"({s})"
  else
    s

def Gen.genMatch (self : GenState) (e : String) (ctx : Any) (depth : Float) : String :=
  let scrutinee : String := genExpr self default ctx depth
  let inner : String := default
  let cases : Array String := Array.map (fun c =>
    let pat : String := genPat self default
    let guard : String := if default then
      " if " ++ (genExpr self default ctx depth)
    else
      ""
    let body : String := genExpr self default ctx (depth + 1)
    s!"{inner}| {pat}{guard} => {body}") default
  (s!"match {scrutinee} with
") ++ (String.intercalate "\n" cases)

def Gen.genPat (self : GenState) (p : Any) : String :=
  match default with
    | "PVar" => sanitize default
    | "PWild" => "_"
    | "PLit" => if (TSLean.typeOf default) == "string" then
      serialize default
    else
      default /- cross-file: String -/
    | "PString" => serialize default
    | "PNone" => ".none"
    | "PSome" => ".some " ++ (genPat self default)
    | "PCtor" => let localName : String := if default.includes "." then
      default.splitOn ".".back?
    else
      default
    let args : Array String := Array.map (fun a => genPat self a) default
    if args.size == 0 then
      s!".{localName}"
    else
      (s!".{localName} ") ++ (String.intercalate " " args)
    | "PTuple" => ("(" ++ (String.intercalate ", " (Array.map (fun x => genPat self x) default))) ++ ")"
    | "PStruct" => ("{ " ++ (String.intercalate ", " (Array.map (fun f => (s!"{default} := ") ++ (genPat self default)) default))) ++ " }"
    | "POr" => String.intercalate " | " (Array.map (fun x => genPat self x) default)
    | "PAs" => ((genPat self default) ++ " as ") ++ default
    | _ => "_"

def Gen.genDoBlock (self : GenState) (stmts : Array Any) (ctx : Any) (depth : Float) : String :=
  default

def Gen.genDoSeq (self : GenState) (stmts : Array Any) (ctx : Any) (depth : Float) : String :=
  default

def Gen.chainSequentialIfs (self : GenState) (stmts : Array Any) : StateT GenState IO (Array Any) :=
  do
    let result : Array Any := #[]
    let i : Float := 0
    do
      let rec _while_56857 := fun _ => do
        if i < stmts.size then do
            let s := stmts.getD i default
            _while_56857
        else
          pure ()
      return result

def Gen.genBinOp (self : GenState) (e : String) (ctx : Any) (depth : Float) : String :=
  if default == "NullCoalesce" then
    let l : String := genP self default ctx depth
    let r : String := genP self default ctx depth
    if ((l == "default") || (l == "(pure default)")) || (l == "pure default") then
      r
    else
      s!"Option.getD {l} {r}"
  else
    if (default == "Eq") && ((default == "LitNull") || ((default == "Var") && (default == "none"))) then
      let l : String := genP self default ctx depth
      s!"{l}.isNone"
    else
      if (default == "Ne") && ((default == "LitNull") || ((default == "Var") && (default == "none"))) then
        let l : String := genP self default ctx depth
        s!"{l}.isSome"
      else
        if (default == "Concat") || ((default == "Add") && (default == "String")) then
          let interp : Option String := trySInterp self e ctx depth
          if interp then
            interp
          else
            ()
        else
          ()
        let l : String := genP self default ctx depth
        let r : String := genP self default ctx depth
        let isAnyL : Bool := ((default == "TypeRef") && (default == "Any")) || (((default == "TypeNarrow") && (default == "TypeRef")) && (default == "Any"))
        let isAnyR : Bool := ((default == "TypeRef") && (default == "Any")) || (((default == "TypeNarrow") && (default == "TypeRef")) && (default == "Any"))
        if ((((default == "Lt") || (default == "Le")) || (default == "Gt")) || (default == "Ge")) && (isAnyL || isAnyR) then
          "(sorry : Bool)"
        else
          let op : String := default /- cross-file: translateBinOp -/
          s!"{l} {op} {r}"

def Gen.trySInterp (self : GenState) (e : Any) (ctx : Any) (depth : Float) : Option String :=
  let parts : Option (Array Any) := flattenConcat e
  if !parts then
    none
  else
    let hasInterp : Bool := parts.any (fun p => default != "LitString")
    let hasLiteral : Bool := parts.any (fun p => (default == "LitString") && (default != ""))
    if (!hasInterp) || (!hasLiteral) then
      none
    else
      if !(parts.all isSafeInterp) then
        none
      else
        let hasUnsafeChars : Bool := parts.any (fun p => (default == "LitString") && (default))
        if hasUnsafeChars then
          none
        else
          let inner : String := String.intercalate "" (Array.map (fun p =>
            if default == "LitString" then
              default
            else
              ("{" ++ (genExpr self p ctx depth)) ++ "}") parts)
          ("s!\"" ++ inner) ++ "\""

def Gen.tryOptionMatch (self : GenState) (e : String) (ctx : Any) (depth : Float) (indent : String) : StateT GenState IO (Option String) :=
  do
    let cond : Any := default
    let optVar : Option String := none
    let optVarExpr : String := none
    do
      if ((default == "BinOp") && (default == "Eq")) && ((default == "LitNull") || ((default == "Var") && (default == "none"))) then
        if default == "Var" then do
            let optVar := default
            let optVarExpr := default
        else
          pure ()
      else do
          if (((!optVar) && (default == "BinOp")) && (default == "Ne")) && ((default == "LitNull") || ((default == "Var") && (default == "none"))) then
            if default == "Var" then do
                let optVar := default
                do
                  let optVarExpr := default
                  let inner := default
            else
              pure ()
          else
            if !optVar then
              pure none
            else
              let thenIsNone : Bool := (((default == "LitNull") || (default == "LitUnit")) || ((default == "Var") && (default == "none"))) || ((default == "Return") && ((default == "LitNull") || ((default == "Var") && (default == "none"))))
              if !thenIsNone then
                pure none
              else
                let inner : String := default
                let someBody : String := genExprWithVarSubst self default ctx (depth + 1) optVar "_v"
                pure (s!"match {optVar} with
{inner}| none => none
{inner}| some _v => {someBody}")

def Gen.genExprWithVarSubst (self : GenState) (e : Any) (ctx : Any) (depth : Float) (from : String) (to : String) : String :=
  let result : String := genExpr self e ctx depth
  result.replace default to

def Gen.emitComment (self : GenState) (c : String) : Unit :=
  default

def Gen.emit (self : GenState) (s : String) : StateT GenState IO Unit :=
  do
    let _ := let prefix : String := default
    let lines : Array String := s.splitOn "\n"
    do
      let _ := Array.push self.lines (prefix ++ lines.getD 0 default)
      let rec _loop_65310 := fun i =>
        if i < lines.size then
          Array.push self.lines lines.getD i default
          _loop_65310 (i + 1)
        else
          ()
    pure ()

def LEAN_KWS : AssocSet String := AssocSet.empty

def sanitize (name : String) : String :=
  if AssocMap.contains LEAN_KWS name then
    s!"«{name}»"
  else
    name.replace "/[^a-zA-Z0-9_.!?']/g" "_"

/-- Format type parameters as implicit ({T : Type}) — used for function definitions. -/
def fmtTPs (params : Array String) : String :=
  if params.size == 0 then
    ""
  else
    (" {" ++ (String.intercalate "} {" (Array.map (fun p => s!"{p} : Type") params))) ++ "}"

/-- Format type parameters as explicit ((T : Type)) — used for structures and inductives. Explicit params let Lean infer type args at use sites without `(T := ...)` annotations. -/
def fmtExplicitTPs (params : Array String) : String :=
  if params.size == 0 then
    ""
  else
    " " ++ (String.intercalate " " (Array.map (fun p => s!"({p} : Type)") params))

/-- Determine if an expression body needs `do` wrapping when inside an effectful function. Returns true when the body contains monadic operations (Bind/Await/Sequence with effects) that aren't already inside a DoBlock. -/
partial def needsDoWrapping (body : Any) : Bool :=
  match default with
    | "DoBlock" => false
    | "Bind" => true
    | "Await" => true
    | "Sequence" => true
    | "Let" => needsDoWrapping default
    | "IfThenElse" => (needsDoWrapping default) || (needsDoWrapping default)
    | _ => false

/-- Emit a type-appropriate default value instead of sorry. Uses `default` (requires Inhabited instance) for most types, but emits concrete literals for common types. -/
partial def defaultForType (t : Any) : String :=
  match default with
    | "Nat" => "0"
    | "Int" => "0"
    | "Float" => "(0 : Float)"
    | "String" => "\"\""
    | "Bool" => "false"
    | "Unit" => "()"
    | "Array" => "#[]"
    | "Option" => "none"
    | "Tuple" => if default.size == 0 then
      "()"
    else
      ("(" ++ (String.intercalate ", " (Array.map defaultForType default))) ++ ")"
    | _ => "default"

/-- Check if a generated string looks like a monadic expression (already in the monad). Pure values like `mkResponse ...` need `pure (...)` wrapping in do blocks. -/
def isSimpleValue (s : String) : Bool :=
  let t : String := s.trim
  (((((((default) || (default)) || (t.startsWith "\"")) || (t == "true")) || (t == "false")) || (t == "default")) || (t == "none")) || (t == "#[]")

/-- Collect all FIELD names (not method calls) accessed on a given variable. self.field → collected; self.method() → NOT collected (it's a method call). -/
def collectFieldAccesses (expr : Any) (varName : String) : AssocMap String Any :=
  default

/-- Check if an else branch is "empty" (LitUnit, pure (), or trivial). -/
def isEmptyElse (e : Any) : Bool :=
  if default == "LitUnit" then
    true
  else
    if (default == "Pure_") && (default == "LitUnit") then
      true
    else
      false

def looksMonadic (s : String) : Bool :=
  let t : String := default
  ((((((((((((t.startsWith "do") || (t.startsWith "pure ")) || (t.startsWith "return ")) || (t.startsWith "let ")) || (t.startsWith "modify ")) || (t.startsWith "throw ")) || (t.startsWith "tryCatch ")) || (t.startsWith "if ")) || (t.startsWith "match ")) || (t == "()")) || (t == "default")) || (t.startsWith "pure default")) || (t.startsWith "pure ()")

def needsParens (e : Any) : Bool :=
  (((((((((default == "App") || (default == "BinOp")) || (default == "UnOp")) || (default == "IfThenElse")) || (default == "Lambda")) || (default == "Let")) || (default == "Bind")) || (default == "TryCatch")) || (default == "Match")) || (default == "LitFloat")

-- // ─── State effect recovery ────────────────────────────────────────────────────
-- // When the parser emits stateEffect(TyUnit) for assignments, we recover the real
-- // state type from the `self` parameter at codegen time.
def fixStateEffect (eff : Any) (params : Array Any) : Any :=
  let selfParam : Option Any := params.find? (fun p => default == "self")
  if !selfParam then
    eff
  else
    if (default == "State") && (default == "Unit") then
      { tag := "State", stateType := default }
    else
      if default == "Combined" then
        { tag := "Combined", effects := default }
      else
        eff

/-- Check if an expression references ANY name from a set (excluding selfName). Recurses deeply into ALL expression types. -/
def bodyContainsAnyVarRef (expr : Any) (names : AssocSet String) (selfName : String) : Bool :=
  default /- cross-file: check -/

def bodyContainsVarRef (expr : Any) (name : String) : Bool :=
  default /- cross-file: check -/

-- // ─── Mutual recursion detection ───────────────────────────────────────────────
def groupMutual (decls : Array Any) : StateT Unit IO (Array (Array Any)) :=
  do
    let funcNames : AssocSet String := AssocSet.empty
    let groups : Array (Array Any) := #[]
    let visited : AssocSet Float := AssocSet.empty
    do
      let rec _loop_75899 := fun i =>
        if i < decls.size then
          if AssocMap.contains visited i then
            ()
          else
            ()
          let d : Any := decls.getD i default
          if default != "FuncDef" then
            Array.push groups #[d]
            AssocSet.insert visited i
          else
            ()
          let mutualGroup : Array String := #[d]
          AssocSet.insert visited i
          let rec _loop_76210 := fun j =>
            if j < decls.size then
              if AssocMap.contains visited j then
                ()
              else
                ()
              let d2 : Any := decls.getD j default
              if default != "FuncDef" then
                ()
              else
                ()
              let fd : String := d
              let fd2 : String := d2
              if (bodyContainsVarRef default default) && (bodyContainsVarRef default default) then
                Array.push mutualGroup d2
                AssocSet.insert visited j
              else
                ()
              _loop_76210 (j + 1)
            else
              ()
          _loop_76210 (i + 1)
          Array.push groups mutualGroup
          _loop_75899 (i + 1)
        else
          ()
      return groups

-- // ─── s!"..." interpolation helpers ───────────────────────────────────────────
partial def flattenConcat (e : Any) : Option (Array Any) :=
  if default == "LitString" then
    #[e]
  else
    if (default == "BinOp") && ((default == "Concat") || ((default == "Add") && (default == "String"))) then
      let left : Option (Array Any) := flattenConcat default
      let right : Option (Array Any) := flattenConcat default
      if (!left) || (!right) then
        none
      else
        #[left, right]
    else
      if isSafeInterp e then
        #[e]
      else
        none

partial def isSafeInterp (e : Any) : Bool :=
  match default with
    | "LitString" => true
    | "LitNat" => true
    | "LitFloat" => true
    | "LitBool" => true
    | "Var" => true
    | "FieldAccess" => isSafeInterp default
    | "Cast" => isSafeInterp default
    | _ => false

end TSLean.Generated.Index