-- Auto-generated by ts-lean-transpiler
-- Source: /workspace/tslean/src/effects/index.ts

import TSLean.Runtime.Basic
import TSLean.Generated.SelfHost.Prelude
import TSLean.Runtime.Coercions
import TSLean.Stdlib.HashMap

open TSLean TSLean.Stdlib.HashMap

namespace TSLean.Generated.Index

def IO_TRIGGERING_PREFIXES : (String × String × String × String) := ("console.", "Date.", "Math.random", "crypto.")

def IO_TRIGGERING_CALLS : AssocSet String := AssocSet.empty

def PURE_MONAD : String := "Id"

def FALLBACK_ERROR_TYPE : String := "TSError"

/-- Infer the algebraic effect of a TypeScript AST node. For function-like nodes, analyses the body directly (skipping the outer signature) so that nested-function guards don't suppress the top level. -/
def inferNodeEffect (node : Any) (checker : Any) : Any :=
  let target : Any := Option.getD (getFunctionBody node) node
  let effects : Array Any := #[]
  if bodyContainsAwait target then
    Array.push effects Async
  else
    ()
  if bodyContainsThrow target then
    Array.push effects (default /- cross-file: exceptEffect -/)
  else
    ()
  if bodyContainsMutation target then
    Array.push effects (default /- cross-file: stateEffect -/)
  else
    ()
  if bodyContainsIO target then
    Array.push effects IO
  else
    ()
  default /- cross-file: combineEffects -/

/-- Convert an Effect to its Lean 4 monad string representation. The monad transformer stack is built right-to-left: ``` ['StateT S', 'ExceptT E', 'IO'] → 'ExceptT E IO'             (fold step 1) → 'StateT S (ExceptT E IO)'  (fold step 2) ``` -/
def monadString (effect : Any) (stateTypeName : String := "σ") : String :=
  match default with
    | "Pure" => PURE_MONAD
    | "IO" => "IO"
    | "Async" => "IO"
    | "State" => ("StateT " ++ (leanTypeName default)) ++ " IO"
    | "Except" => ("ExceptT " ++ (leanTypeName default)) ++ " IO"
    | "Combined" => let se : Option String := default.find? (fun e => default == "State")
    let ee : Option String := default.find? (fun e => default == "Except")
    let parts : Array String := #[]
    if se then
      Array.push parts ("StateT " ++ (leanTypeName default))
    else
      if default.any (fun e => default == "State") then
        Array.push parts (s!"StateT {stateTypeName}")
      else
        ()
    if ee then
      Array.push parts ("ExceptT " ++ (leanTypeName default))
    else
      if default.any (fun e => default == "Except") then
        Array.push parts (s!"ExceptT {FALLBACK_ERROR_TYPE}")
      else
        ()
    Array.push parts "IO"
    if parts.size == 1 then
      parts.getD 0 default
    else
      parts.reduceRight (fun inner outer =>
        (s!"{outer} ") ++ (if inner.includes " " then
          s!"({inner})"
        else
          inner))

/-- Generate the DOMonad type string for a Durable Object. -/
def doMonadType (stateTypeName : String) : String :=
  s!"DOMonad {stateTypeName}"

/-- Compute the join (least upper bound) of two effects. Pure is the identity element. -/
def joinEffects (a : Any) (b : Any) : Any :=
  if default == "Pure" then
    b
  else
    if default == "Pure" then
      a
    else
      default /- cross-file: combineEffects -/

/-- Test whether effect `a` subsumes effect `b` — i.e., `a` can handle `b`. Pure is subsumed by everything.  Combined effects check recursively. -/
partial def effectSubsumes (a : Any) (b : Any) : Bool :=
  if default == "Pure" then
    true
  else
    if default == default then
      true
    else
      if default == "Combined" then
        default.any (fun e => effectSubsumes e b)
      else
        false

-- // ─── Internal: AST scanning ─────────────────────────────────────────────────────
-- //
-- // Each `bodyContains*` function walks the AST looking for a specific pattern,
-- // but never recurses into nested function scopes (lambdas, arrow functions,
-- // method declarations) — those are separate effect boundaries.
partial def getFunctionBody (node : Any) : Option Any :=
  if ((default) || (default)) || (default) then
    Option.getD node.body none
  else
    if default then
      node.body
    else
      if default then
        let d : VariableDeclaration := node.declarationList.declarations.getD 0 default
        if (d.bind (fun _oc => _oc.initializer)) && ((default) || (default)) then
          getFunctionBody d.initializer
        else
          ()
      else
        ()
      none

partial def bodyContainsAwait (node : Any) : Bool :=
  if default then
    true
  else
    if isNestedFnScope node then
      false
    else
      node.getChildren.any bodyContainsAwait

partial def bodyContainsThrow (node : Any) : Bool :=
  if default then
    true
  else
    if isNestedFnScope node then
      false
    else
      node.getChildren.any bodyContainsThrow

partial def bodyContainsMutation (node : Any) : Bool :=
  if (default) && (isAssignOp node.operatorToken.kind) then
    true
  else
    if (default) && (isIncrDecr node.operator) then
      true
    else
      if (default) && (isIncrDecr node.operator) then
        true
      else
        if isNestedFnScope node then
          false
        else
          node.getChildren.any bodyContainsMutation

partial def bodyContainsIO (node : Any) : Bool :=
  if default then
    let text : String := node.expression.getText
    if (IO_TRIGGERING_PREFIXES.any (fun p => text.startsWith p)) || (AssocMap.contains IO_TRIGGERING_CALLS text) then
      true
    else
      ()
  else
    ()
  if isNestedFnScope node then
    false
  else
    node.getChildren.any bodyContainsIO

def isNestedFnScope (node : Any) : Bool :=
  (((default) || (default)) || (default)) || (default)

def isAssignOp (kind : SyntaxKind) : Bool :=
  (((((kind == ts.SyntaxKind.EqualsToken) || (kind == ts.SyntaxKind.PlusEqualsToken)) || (kind == ts.SyntaxKind.MinusEqualsToken)) || (kind == ts.SyntaxKind.AsteriskEqualsToken)) || (kind == ts.SyntaxKind.SlashEqualsToken)) || (kind == ts.SyntaxKind.PercentEqualsToken)

def isIncrDecr (kind : SyntaxKind) : Bool :=
  (kind == ts.SyntaxKind.PlusPlusToken) || (kind == ts.SyntaxKind.MinusMinusToken)

/-- Map an IR type to its Lean 4 name for use in monad signatures. Falls back to `TSError` for types that don't have a direct Lean primitive name. -/
partial def leanTypeName (t : Any) : String :=
  match default with
    | "String" => "String"
    | "Float" => "Float"
    | "Nat" => "Nat"
    | "Int" => "Int"
    | "Bool" => "Bool"
    | "Unit" => "Unit"
    | "TypeRef" => if default.size == 0 then
      default
    else
      ((s!"({default} ") ++ (String.intercalate " " (Array.map leanTypeName default))) ++ ")"
    | _ => FALLBACK_ERROR_TYPE

end TSLean.Generated.Index