-- Auto-generated by ts-lean-transpiler
-- Source: /workspace/tslean/src/parser/index.ts

import TSLean.DurableObjects.Http
import TSLean.Generated.SelfHost.Prelude
import TSLean.DurableObjects.Model
import TSLean.DurableObjects.State
import TSLean.DurableObjects.Storage
import TSLean.Runtime.Basic
import TSLean.Runtime.Coercions
import TSLean.Runtime.Monad
import TSLean.Stdlib.HashMap

open TSLean TSLean.Stdlib.HashMap TSLean.DO

namespace TSLean.Generated.Index

-- // ─── Public API ───────────────────────────────────────────────────────────────
-- Options for parsing a single TypeScript file into IR.
structure ParseOptions where
  mk ::
  fileName : String
  sourceText : Option (Option String)
  extraFiles : Option (Option (AssocMap String String))
  deriving Repr, BEq, Inhabited

/-- Parse a TypeScript source file into a fully-typed IR module. Creates a `ts.Program` with type checking, resolves all types and effects, and produces an `IRModule` ready for the rewrite and codegen passes. -/
def parseFile (opts : ParseOptions) : ExceptT String IO Any :=
  do
    let fileName : String := opts.fileName
    let sourceText : String := Option.getD (Option.getD opts.sourceText (default)) ""
    let virtual : AssocMap String String := AssocMap.empty
    do
      AssocMap.insert virtual fileName sourceText
      let needsDO := default /- cross-file: hasDOPattern -/

-- State for ParserCtx
structure ParserCtxState where
  mk ::
  imports : Array Any
  sf : Any
  needsDO : Bool
  checker : Any
  deriving Repr, BEq, Inhabited

def ParserCtx.init (self : ParserCtxState) (checker : Any) (sf : Any) (needsDO : Bool) : Unit :=
  ()

def ParserCtx.parseModule (self : ParserCtxState) : Any :=
  default

def ParserCtx.collectImport (self : ParserCtxState) (node : ImportDeclaration) : Unit :=
  default

def ParserCtx.tsModToLean (self : ParserCtxState) (spec : String) : String :=
  if !(spec.startsWith ".") then
    let known : String := { zod := "TSLean.Stdlib.Validation", uuid := "TSLean.Stdlib.Uuid" }
    Option.getD known.getD spec default ("TSLean.External." ++ (cap (spec.replace "/[^a-zA-Z0-9]/g" "_")))
  else
    let parts : Array String := Array.map (fun p => String.intercalate "" (Array.map cap (p.splitOn "/[-_]/"))) (Array.filter (((spec.replace "/^[./]+/" "").replace "/\\.(ts|js)$/" "").splitOn "/") Boolean)
    "TSLean.Generated." ++ (String.intercalate "." parts)

def ParserCtx.parseStatement (self : ParserCtxState) (stmt : Any) : String :=
  if default then
    parseFnDecl self stmt
  else
    if default then
      parseClassDecl self stmt
    else
      if default then
        parseInterface self stmt
      else
        if default then
          parseTypeAlias self stmt
        else
          if default then
            parseEnum self stmt
          else
            if default then
              parseVarStmt self stmt
            else
              if default then
                parseNamespace self stmt
              else
                if default then
                  parseExportDecl self stmt
                else
                  if default then
                    parseExportAssignment self stmt
                  else
                    if default then
                      let e : Any := parseExpr self stmt.expression
                      { tag := "VarDecl", name := "_main", type := TyUnit, value := e, mutable := false }
                    else
                      none

def ParserCtx.parseExportDecl (self : ParserCtxState) (node : ExportDeclaration) : Option (Array Any) :=
  if !node.moduleSpecifier then
    none
  else
    let spec : String := node.moduleSpecifier.text
    let lean : String := tsModToLean self spec
    Array.push self.imports { module := lean }
    none

def ParserCtx.parseExportAssignment (self : ParserCtxState) (node : ExportAssignment) : Option (Array Any) :=
  default

def ParserCtx.parseFnDecl (self : ParserCtxState) (node : Any) : Any :=
  let name : String := Option.getD (node.name.bind (fun _oc => _oc.text)) "anonymous"
  let tps : Array String := default /- cross-file: extractTypeParams -/
  let params : Array Any := parseParams self node.parameters
  let sig : Signature := self.checker.getSignatureFromDeclaration node
  let ret : Any := if sig then
    default /- cross-file: mapType -/
  else
    TyUnit
  let eff : Any := default /- cross-file: inferNodeEffect -/
  let body : Any := if node.body then
    parseBlock self node.body eff
  else
    default /- cross-file: holeExpr -/
  let docComment : Option String := jsdocComment node self.sf
  { tag := "FuncDef", name := name, typeParams := tps, params := params, retType := ret, effect := eff, body := body, comment := leadingComment node self.sf, docComment := docComment }

def ParserCtx.parseParams (self : ParserCtxState) (params : NodeArray ParameterDeclaration) : Array Any :=
  params.map (fun p =>
    if p.dotDotDotToken && (default) then
      let sym : Option Symbol := self.checker.getSymbolAtLocation p.name
      let elemTy : Any := if sym then
        default /- cross-file: mapType -/
      else
        default /- cross-file: TyRef -/
      let arrTy : Any := if default == "Array" then
        elemTy
      else
        default /- cross-file: TyArray -/
      { name := p.name.text, type := arrTy, default_ := none }
    else
      if !(default) then
        { name := default, type := default /- cross-file: TyRef -/, default_ := none }
      else
        let name : String := p.name.text
        let sym : Option Symbol := self.checker.getSymbolAtLocation p.name
        let ty : Any := if sym then
          default /- cross-file: mapType -/
        else
          default /- cross-file: TyRef -/
        { name := name, type := ty, default_ := if p.initializer then
          parseExpr self p.initializer
        else
          none })

def ParserCtx.parseClassDecl (self : ParserCtxState) (node : Any) : Array Any :=
  default

def ParserCtx.parseGetter (self : ParserCtxState) (node : GetAccessorDeclaration) (className : String) (stateType : String) : String :=
  let fieldName : String := Option.getD (node.name.getText self.sf) "unknown"
  let sig : Option Signature := self.checker.getSignatureFromDeclaration node
  let ret : Any := if sig then
    default /- cross-file: mapType -/
  else
    TyUnit
  let self : Any := { name := "self", type := default /- cross-file: TyRef -/ }
  let body : Any := if node.body then
    parseBlock self node.body Pure
  else
    { tag := "FieldAccess", obj := default /- cross-file: varExpr -/, field := fieldName, type := ret, effect := Pure }
  { tag := "FuncDef", name := default, typeParams := #[], params := #[self], retType := ret, effect := Pure, body := body }

def ParserCtx.parseSetter (self : ParserCtxState) (node : SetAccessorDeclaration) (className : String) (stateType : String) : String :=
  let fieldName : String := Option.getD (node.name.getText self.sf) "unknown"
  let params : Array Any := parseParams self node.parameters
  let self : Any := { name := "self", type := default /- cross-file: TyRef -/ }
  let valType : Any := Option.getD (default) TyUnit
  let valName : String := Option.getD (default) "v"
  let retType : Any := default /- cross-file: TyRef -/
  let body : Any := { tag := "StructLit", typeName := stateType, fields := #[{ name := "_base", value := default /- cross-file: varExpr -/ }, { name := fieldName, value := default /- cross-file: varExpr -/ }], type := retType, effect := Pure }
  { tag := "FuncDef", name := default, typeParams := #[], params := #[self, params], retType := retType, effect := Pure, body := body }

def ParserCtx.isDOClass (self : ParserCtxState) (node : Any) : Bool :=
  (Option.getD node.heritageClauses #[].any (fun h => h.types.any (fun t => (t.expression.getText self.sf).includes "DurableObject"))) || (node.members.any (fun m => (default) && (m.parameters.any (fun p => p.type.getText self.sf.contains "DurableObjectState"))))

def ParserCtx.classStateFields (self : ParserCtxState) (node : Any) : Array String :=
  default

def ParserCtx.parseCtor (self : ParserCtxState) (node : ConstructorDeclaration) (className : String) (stateType : String) (isDO : Bool) : String :=
  let params : Array Any := parseParams self node.parameters
  let eff : Any := default /- cross-file: inferNodeEffect -/
  if isDO then
    let stateFields : Array String := classStateFields self node.parent
    let appParams : Array Any := Array.filter params (fun p =>
      let t : Any := default
      if (default == "TypeRef") && ((default == "DurableObjectState") || (default == "Env")) then
        false
      else
        true)
    let fields : Array __object := Array.map (fun f =>
      { name := default, value := if appParams.find? (fun p => default == default) then
        default /- cross-file: varExpr -/
      else
        default /- cross-file: holeExpr -/ }) stateFields
    let retType : Any := default /- cross-file: TyRef -/
    let body : Any := if fields.size > 0 then
      { tag := "StructLit", typeName := stateType, fields := fields, type := retType, effect := Pure }
    else
      { tag := "StructLit", typeName := stateType, fields := #[], type := retType, effect := Pure }
    { tag := "FuncDef", name := default, typeParams := #[], params := appParams, retType := retType, effect := Pure, body := body }
  else
    let self : Any := { name := "self", type := default /- cross-file: TyRef -/ }
    let body : Any := if node.body then
      parseBlock self node.body eff
    else
      default /- cross-file: holeExpr -/
    { tag := "FuncDef", name := default, typeParams := #[], params := #[self, params], retType := TyUnit, effect := eff, body := body }

def ParserCtx.parseMethod (self : ParserCtxState) (node : MethodDeclaration) (className : String) (stateType : String) (isDO : Bool) : String :=
  let name : String := Option.getD (node.name.getText self.sf) "unknown"
  let isStatic : Bool := node.modifiers.any (fun m => m.kind == ts.SyntaxKind.StaticKeyword)
  let methodTPs : Array String := default /- cross-file: extractTypeParams -/
  let classTPs : Array String := if node.parent && (default) then
    default /- cross-file: extractTypeParams -/
  else
    #[]
  let tps : Array String := #[AssocSet.empty]
  let sig : Signature := self.checker.getSignatureFromDeclaration node
  let ret : Any := if sig then
    default /- cross-file: mapType -/
  else
    TyUnit
  let eff : Any := default /- cross-file: inferNodeEffect -/
  let params : Array Any := parseParams self node.parameters
  let selfType : Any := if classTPs.size > 0 then
    default /- cross-file: TyRef -/
  else
    default /- cross-file: TyRef -/
  let self : Any := { name := "self", type := selfType }
  let allParams : Array Any := if isStatic then
    params
  else
    #[self, params]
  let body : Any := if node.body then
    parseBlock self node.body eff
  else
    default /- cross-file: holeExpr -/
  let fullName : String := s!"{className}.{name}"
  { tag := "FuncDef", name := fullName, typeParams := tps, params := allParams, retType := ret, effect := eff, body := body }

def ParserCtx.parseInterface (self : ParserCtxState) (node : Any) : String :=
  default

def ParserCtx.parseTypeAlias (self : ParserCtxState) (node : Any) : String :=
  let name : String := node.name.text
  let tps : Array String := default /- cross-file: extractTypeParams -/
  let ty : Type := self.checker.getTypeAtLocation node
  if ty.isUnion then
    let disc : Option DiscriminantInfo := default /- cross-file: detectDiscriminatedUnion -/
    if disc then
      { tag := "InductiveDef", name := name, typeParams := tps, ctors := default, comment := leadingComment node self.sf }
    else
      let members : Array Type := ty.types
      if members.all (fun m => m.flags &&& ts.TypeFlags.StringLiteral) then
        { tag := "InductiveDef", name := name, typeParams := tps, ctors := default, comment := leadingComment node self.sf }
      else
        ()
  else
    ()
  if ty.isIntersection then
    let isBranded : Bool := ty.types.any (fun t => (t.flags &&& ts.TypeFlags.Object) && (t.getProperties.any (fun p => (p.name.startsWith "__brand") || (p.name.startsWith "_brand"))))
    if isBranded then
      { tag := "StructDef", name := name, typeParams := tps, fields := #[{ name := "val", type := TyString }], deriving := #["Repr", "BEq", "DecidableEq"] }
    else
      ()
  else
    ()
  let typeNode : TypeNode := node.type
  if typeNode then
    if default then
      let resolved : Any := default /- cross-file: mapType -/
      { tag := "TypeAlias", name := name, typeParams := tps, body := resolved, comment := "-- conditional type: " ++ (typeNode.getText self.sf) }
    else
      if default then
        let resolved : Any := default /- cross-file: mapType -/
        { tag := "TypeAlias", name := name, typeParams := tps, body := resolved, comment := "-- mapped type: " ++ (default) }
      else
        if default then
          { tag := "TypeAlias", name := name, typeParams := tps, body := TyString, comment := "-- template literal type: " ++ (typeNode.getText self.sf) }
        else
          if default then
            let elems : Array Any := typeNode.elements.map (fun e =>
              let elemType : Type := self.checker.getTypeAtLocation e
              default /- cross-file: mapType -/)
            { tag := "TypeAlias", name := name, typeParams := tps, body := default /- cross-file: TyTuple -/, comment := leadingComment node self.sf }
          else
            if default then
              let resolved : Any := default /- cross-file: mapType -/
              { tag := "TypeAlias", name := name, typeParams := tps, body := resolved, comment := "-- typeof type: " ++ (typeNode.getText self.sf) }
            else
              if (default) && (typeNode.operator == ts.SyntaxKind.KeyOfKeyword) then
                { tag := "TypeAlias", name := name, typeParams := tps, body := TyString, comment := "-- keyof type" }
              else
                ()
  else
    ()
  { tag := "TypeAlias", name := name, typeParams := tps, body := default /- cross-file: mapType -/, comment := leadingComment node self.sf }

def ParserCtx.parseEnum (self : ParserCtxState) (node : Any) : String :=
  let enumName : String := node.name.text
  let members : Array __object := node.members.map (fun m =>
    { name := if default then
      m.name.text
    else
      m.name.getText self.sf, value := if m.initializer then
      (m.initializer.getText self.sf).replace "/['\"]/g" ""
    else
      none })
  let isStringEnum : Bool := members.any (fun m => (m.value.isSome) && (Float.isNaN (default /- cross-file: Number -/)))
  let inductive : Any := { tag := "InductiveDef", name := enumName, typeParams := #[], ctors := default, comment := leadingComment node self.sf }
  if !isStringEnum then
    «inductive»
  else
    let toStringCases : Array Any := Array.map (fun m => { pattern := default, body := default /- cross-file: litStr -/ }) members
    let toStringFn : Any := { tag := "FuncDef", name := default, typeParams := #[], params := #[{ name := "e", type := default /- cross-file: TyRef -/ }], retType := TyString, effect := Pure, body := default }
    #[«inductive», toStringFn]

def ParserCtx.parseVarStmt (self : ParserCtxState) (node : Any) : Array Any :=
  default

def ParserCtx.parseNamespace (self : ParserCtxState) (node : Any) : Any :=
  default

def ParserCtx.parseBlock (self : ParserCtxState) (block : Block) (eff : Any) : Any :=
  parseStmts self block.statements eff

def ParserCtx.parseStmts (self : ParserCtxState) (stmts : Array Any) (eff : Any) : Any :=
  if stmts.size == 0 then
    default /- cross-file: litUnit -/
  else
    let head : Any := stmts.getD 0 default
    let rest : Array Any := stmts.getD 1 default
    parseStmt self head rest eff

def ParserCtx.parseStmt (self : ParserCtxState) (stmt : Any) (rest : Array Any) (eff : Any) : StateT ParserCtxState IO Any :=
  do
    let cont : Unit → Any := fun _ =>
      if rest.size > 0 then
        parseStmts self rest eff
      else
        default /- cross-file: litUnit -/
    if default then
      let v : Any := if stmt.expression then
        pure (parseExpr self stmt.expression)
      else
        pure (default /- cross-file: litUnit -/)
      pure { tag := "Return", value := v, type := default, effect := default }
    else do
        if default then
          let decl : VariableDeclaration := stmt.declarationList.declarations.getD 0 default
          if decl && (default) then
            let name : String := decl.name.text
            let ty : Any := default /- cross-file: mapType -/
            let val : Any := if decl.initializer then
              parseExpr self decl.initializer
            else
              default /- cross-file: holeExpr -/
            let body : Any := default /- cross-file: cont -/
            let combined : Any := default /- cross-file: combineEffects -/
            if (!(default /- cross-file: isPure -/)) && (default /- cross-file: hasAsync -/) then
              pure { tag := "Bind", name := name, monad := val, body := body, type := default, effect := combined }
            else
              pure { tag := "Let", name := name, annot := ty, value := val, body := body, type := default, effect := combined }
          else
            if (decl && (default)) && decl.initializer then
              let rhs : Any := parseExpr self decl.initializer
              let body : Any := default /- cross-file: cont -/
              do
                let body := flattenObjectBinding self decl.name rhs body
                return body
            else
              if (decl && (default)) && decl.initializer then
                let rhs : Any := parseExpr self decl.initializer
                let body : Any := default /- cross-file: cont -/
                do
                  let body := flattenArrayBinding self decl.name rhs body
                  return body
              else
                pure ()
        else
          if default then
            pure (parseIf self stmt rest eff)
          else
            if default then
              let iter : Any := parseExpr self stmt.expression
              let binding : String := if default then
                stmt.initializer.declarations.getD 0 default.name.text
              else
                "_x"
              let body : Any := if default then
                parseBlock self stmt.statement eff
              else
                parseStmt self stmt.statement #[] eff
              let loop : Any := { tag := "App", fn := default /- cross-file: varExpr -/, args := #[iter, { tag := "Lambda", params := #[{ name := binding, type := TyUnit }], body := body, type := default /- cross-file: TyFn -/, effect := default }], type := TyUnit, effect := default /- cross-file: combineEffects -/ }
              let c : Any := default /- cross-file: cont -/
              pure (if default == "LitUnit" then
                loop
              else
                seq loop c)
            else
              if default then
                let loop : Any := parseFor self stmt eff
                let c : Any := default /- cross-file: cont -/
                pure (if default == "LitUnit" then
                  loop
                else
                  seq loop c)
              else
                if default then
                  let obj : Any := parseExpr self stmt.expression
                  let binding : String := if default then
                    stmt.initializer.declarations.getD 0 default.name.text
                  else
                    "_k"
                  let body : Any := if default then
                    parseBlock self stmt.statement eff
                  else
                    parseStmt self stmt.statement #[] eff
                  let keysExpr : Any := { tag := "App", fn := default /- cross-file: varExpr -/, args := #[obj], type := default /- cross-file: TyArray -/, effect := Pure }
                  let loop : Any := { tag := "App", fn := default /- cross-file: varExpr -/, args := #[keysExpr, { tag := "Lambda", params := #[{ name := binding, type := TyString }], body := body, type := default /- cross-file: TyFn -/, effect := default }], type := TyUnit, effect := default /- cross-file: combineEffects -/ }
                  let c : Any := default /- cross-file: cont -/
                  pure (if default == "LitUnit" then
                    loop
                  else
                    seq loop c)
                else
                  if default then
                    let loop : Any := parseWhile self stmt eff
                    let c : Any := default /- cross-file: cont -/
                    pure (if default == "LitUnit" then
                      loop
                    else
                      seq loop c)
                  else
                    if default then
                      let err : Any := if stmt.expression then
                        parseExpr self stmt.expression
                      else
                        default /- cross-file: litStr -/
                      pure { tag := "Throw", error := err, type := TyNever, effect := default /- cross-file: exceptEffect -/ }
                    else
                      if default then
                        pure (parseTry self stmt rest eff)
                      else
                        if default then
                          let m : Any := parseSwitch self stmt
                          let c : Any := default /- cross-file: cont -/
                          pure (if default == "LitUnit" then
                            m
                          else
                            seq m c)
                        else
                          if default then
                            let inner : Any := parseBlock self stmt eff
                            let c : Any := default /- cross-file: cont -/
                            pure (if default == "LitUnit" then
                              inner
                            else
                              seq inner c)
                          else
                            if default then
                              let e : Any := parseExpr self stmt.expression
                              let c : Any := default /- cross-file: cont -/
                              pure (if default == "LitUnit" then
                                e
                              else
                                seq e c)
                            else
                              pure (default /- cross-file: cont -/)

def ParserCtx.parseIf (self : ParserCtxState) (stmt : IfStatement) (rest : Array Any) (eff : Any) : Any :=
  let cond : Any := parseExpr self stmt.expression
  let then_ : Any := if default then
    parseBlock self stmt.thenStatement eff
  else
    parseStmt self stmt.thenStatement #[] eff
  let thenRets : Bool := branchReturns then_
  if thenRets && (rest.size > 0) then
    let else_ : Any := if stmt.elseStatement then
      if default then
        parseBlock self stmt.elseStatement eff
      else
        parseStmt self stmt.elseStatement rest eff
    else
      parseStmts self rest eff
    { tag := "IfThenElse", cond := cond, «then» := then_, else_ := else_, type := default, effect := default /- cross-file: combineEffects -/ }
  else
    let else_ : Any := if stmt.elseStatement then
      if default then
        parseBlock self stmt.elseStatement eff
      else
        parseStmt self stmt.elseStatement #[] eff
    else
      default /- cross-file: litUnit -/
    let ifExpr : Any := { tag := "IfThenElse", cond := cond, «then» := then_, else_ := else_, type := default, effect := default /- cross-file: combineEffects -/ }
    if rest.size == 0 then
      ifExpr
    else
      let c : Any := parseStmts self rest eff
      seq ifExpr c

def ParserCtx.parseSwitch (self : ParserCtxState) (node : SwitchStatement) : StateT ParserCtxState IO Any :=
  do
    let scrutinee : Any := parseExpr self node.expression
    let cases : Array Any := #[]
    let hasDefault : Bool := false
    do
      let _ := Array.forM node.caseBlock.clauses (fun cl => do
        if default then
          let caseExpr : Any := parseExpr self cl.expression
          let pat : Any := exprToPat caseExpr
          let body : Any := parseSwitchCaseBody self cl node.caseBlock.clauses
          Array.push cases { pattern := pat, body := body }
        else do
            let hasDefault := true
            let body := parseStmts self cl.statements Pure)
      let _ := do
        let _ := if (!hasDefault) && (cases.size > 0) then
          let allStringPatterns : Bool := cases.all (fun c => (default == "PString") || (default == "PLit"))
          let isDiscriminantSwitch : Bool := (default == "FieldAccess") && ((((default == "kind") || (default == "type")) || (default == "tag")) || (default == "ok"))
          if !(allStringPatterns && isDiscriminantSwitch) then
            let retType : Any := Option.getD default.type TyUnit
            let fallbackBody : Any := if default == "Unit" then
              default /- cross-file: litUnit -/
            else
              default /- cross-file: holeExpr -/
            Array.push cases { pattern := default, body := fallbackBody }
          else
            pure ()
        else
          pure { tag := "Match", scrutinee := scrutinee, cases := cases, type := Option.getD default.type TyUnit, effect := default /- cross-file: combineEffects -/ }

def ParserCtx.parseSwitchCaseBody (self : ParserCtxState) (cl : CaseClause) (allClauses : NodeArray CaseOrDefaultClause) : StateT ParserCtxState IO Any :=
  do
    let stmts : Array Any := Array.filter (Array.ofList cl.statements) (fun s => (!(default)) && (!(default)))
    if stmts.size == 0 then
      let idx : Float := allClauses.indexOf? cl
      do
        let rec _loop_40376 := fun i =>
          if i < allClauses.size then
            let next : CaseOrDefaultClause := allClauses.getD i default
            let nextStmts : Array Any := Array.filter (Array.ofList next.statements) (fun s => (!(default)) && (!(default)))
            if nextStmts.size > 0 then
              parseStmts self nextStmts Pure
            else
              ()
            _loop_40376 (i + 1)
          else
            ()
        return default /- cross-file: litUnit -/
    else
      pure (parseStmts self stmts Pure)

def ParserCtx.flattenObjectBinding (self : ParserCtxState) (pattern : ObjectBindingPattern) (rhs : Any) (body : Any) : StateT ParserCtxState IO Any :=
  do
    let elems : Array BindingElement := #[pattern.elements].reverse
    do
      Array.forM elems (fun el => do
        let propName : String := if el.propertyName then
          if default then
            el.propertyName.text
          else
            el.propertyName.getText self.sf
        else
          if default then
            el.name.text
          else
            s!"_el{el.pos}"
        let ty : Any := default /- cross-file: mapType -/
        let fieldVal : Any := { tag := "FieldAccess", obj := rhs, field := propName, type := ty, effect := default }
        if default then
          let tmpName : String := s!"_ds_{propName}"
          let tmpRef : Any := { tag := "Var", name := tmpName, type := ty, effect := Pure }
          do
            let body := flattenObjectBinding self el.name tmpRef body
            let body := { tag := "Let", name := tmpName, annot := ty, value := fieldVal, body := body, type := default, effect := default /- cross-file: combineEffects -/ }
        else
          if default then
            let tmpName : String := s!"_ds_{propName}"
            let tmpRef : Any := { tag := "Var", name := tmpName, type := ty, effect := Pure }
            do
              let body := flattenArrayBinding self el.name tmpRef body
              let body := { tag := "Let", name := tmpName, annot := ty, value := fieldVal, body := body, type := default, effect := default /- cross-file: combineEffects -/ }
          else
            let bindName : String := if default then
              el.name.text
            else
              s!"_el{el.pos}"
            if el.initializer then
              let defaultVal : Any := parseExpr self el.initializer
              let withDefault : Any := { tag := "App", fn := default /- cross-file: varExpr -/, args := #[fieldVal, defaultVal], type := ty, effect := default /- cross-file: combineEffects -/ }
              let body := { tag := "Let", name := bindName, annot := ty, value := withDefault, body := body, type := default, effect := default /- cross-file: combineEffects -/ }
            else
              let body := { tag := "Let", name := bindName, annot := ty, value := fieldVal, body := body, type := default, effect := default /- cross-file: combineEffects -/ })
      return body

def ParserCtx.flattenArrayBinding (self : ParserCtxState) (pattern : ArrayBindingPattern) (rhs : Any) (body : Any) : Any :=
  default

def ParserCtx.parseTry (self : ParserCtxState) (node : TryStatement) (rest : Array Any) (eff : Any) : Any :=
  let body : Any := parseBlock self node.tryBlock eff
  let errName : String := if node.catchClause.bind (fun _oc => _oc.variableDeclaration).bind (fun _oc => some _oc.name) then
    node.catchClause.variableDeclaration.name.text
  else
    "_e"
  let handler : Any := if node.catchClause.bind (fun _oc => _oc.block) then
    parseBlock self node.catchClause.block eff
  else
    default /- cross-file: varExpr -/
  let tryCatch : Any := { tag := "TryCatch", body := body, errName := errName, handler := handler, type := default, effect := default }
  if rest.size == 0 then
    tryCatch
  else
    seq tryCatch (parseStmts self rest eff)

def ParserCtx.parseFor (self : ParserCtxState) (node : ForStatement) (eff : Any) : Any :=
  let init : Option VariableDeclaration := if node.initializer && (default) then
    node.initializer.declarations.getD 0 default
  else
    none
  let iName : String := if init && (default) then
    init.name.text
  else
    "_i"
  let iVal : Any := if init.bind (fun _oc => _oc.initializer) then
    parseExpr self init.initializer
  else
    default /- cross-file: litNat -/
  let cond : Any := if node.condition then
    parseExpr self node.condition
  else
    default /- cross-file: litBool -/
  let body : Any := if default then
    parseBlock self node.statement eff
  else
    parseStmt self node.statement #[] eff
  let incrParsed : Any := if node.incrementor then
    parseExpr self node.incrementor
  else
    { tag := "BinOp", op := "Add", left := default /- cross-file: varExpr -/, right := default /- cross-file: litNat -/, type := TyNat, effect := Pure }
  let incrArg : Any := if (default == "Assign") && (default == "Var") then
    default
  else
    incrParsed
  let lName : String := s!"_loop_{node.pos}"
  let recurse : Any := { tag := "App", fn := default /- cross-file: varExpr -/, args := #[incrArg], type := TyUnit, effect := Pure }
  let loopBody : Any := { tag := "IfThenElse", cond := cond, «then» := seq body recurse, else_ := default /- cross-file: litUnit -/, type := TyUnit, effect := default /- cross-file: combineEffects -/ }
  { tag := "Let", name := lName, value := default, body := default, type := TyUnit, effect := default }

def ParserCtx.parseWhile (self : ParserCtxState) (node : WhileStatement) (eff : Any) : Any :=
  let cond : Any := parseExpr self node.expression
  let body : Any := if default then
    parseBlock self node.statement eff
  else
    parseStmt self node.statement #[] eff
  let lName : String := s!"_while_{node.pos}"
  let recurse : Any := { tag := "App", fn := default /- cross-file: varExpr -/, args := #[], type := TyUnit, effect := Pure }
  let lBody : Any := { tag := "IfThenElse", cond := cond, «then» := seq body recurse, else_ := default /- cross-file: litUnit -/, type := TyUnit, effect := default /- cross-file: combineEffects -/ }
  { tag := "Let", name := lName, value := default, body := default, type := TyUnit, effect := default }

def ParserCtx.parseExpr (self : ParserCtxState) (node : Any) : Any :=
  let ty : Any := default /- cross-file: mapType -/
  if default then
    let v : Float := default /- cross-file: Number -/
    if (Number.isInteger v) && (v >= 0) then
      { tag := "LitNat", value := v, type := TyNat, effect := Pure }
    else
      { tag := "LitFloat", value := v, type := TyFloat, effect := Pure }
  else
    if (default) || (default) then
      default /- cross-file: litStr -/
    else
      if default then
        parseTemplate self node
      else
        if node.kind == ts.SyntaxKind.TrueKeyword then
          default /- cross-file: litBool -/
        else
          if node.kind == ts.SyntaxKind.FalseKeyword then
            default /- cross-file: litBool -/
          else
            if (node.kind == ts.SyntaxKind.NullKeyword) || (node.kind == ts.SyntaxKind.UndefinedKeyword) then
              { tag := "LitNull", type := default /- cross-file: TyOption -/, effect := Pure }
            else
              if default then
                default /- cross-file: varExpr -/
              else
                if node.kind == ts.SyntaxKind.ThisKeyword then
                  default /- cross-file: varExpr -/
                else
                  if default then
                    parsePropAccess self node ty
                  else
                    if default then
                      let obj : Any := parseExpr self node.expression
                      let index : Any := parseExpr self node.argumentExpression
                      if default then
                        { tag := "App", fn := default /- cross-file: varExpr -/, args := #[obj, index], type := default /- cross-file: TyOption -/, effect := Pure }
                      else
                        { tag := "IndexAccess", obj := obj, index := index, type := ty, effect := Pure }
                    else
                      if default then
                        parseCall self node ty
                      else
                        if default then
                          parseNew self node ty
                        else
                          if (default) || (default) then
                            parseLambda self node
                          else
                            if default then
                              if node.operatorToken.kind == ts.SyntaxKind.InstanceOfKeyword then
                                let expr : Any := parseExpr self node.left
                                let testTy : Any := default /- cross-file: mapType -/
                                { tag := "IsType", expr := expr, testType := testTy, type := TyBool, effect := default }
                              else
                                if node.operatorToken.kind == ts.SyntaxKind.InKeyword then
                                  let key : Any := parseExpr self node.left
                                  let obj : Any := parseExpr self node.right
                                  { tag := "App", fn := default /- cross-file: varExpr -/, args := #[obj, key], type := TyBool, effect := Pure }
                                else
                                  if node.operatorToken.kind == ts.SyntaxKind.CommaToken then
                                    let left : Any := parseExpr self node.left
                                    let right : Any := parseExpr self node.right
                                    { tag := "Sequence", stmts := #[left, right], type := default, effect := default /- cross-file: combineEffects -/ }
                                  else
                                    parseBinary self node ty
                            else
                              if default then
                                parsePrefix self node ty
                              else
                                if default then
                                  parsePostfix self node
                                else
                                  if default then
                                    let cond : Any := parseExpr self node.condition
                                    let then_ : Any := parseExpr self node.whenTrue
                                    let else_ : Any := parseExpr self node.whenFalse
                                    { tag := "IfThenElse", cond := cond, «then» := then_, else_ := else_, type := default, effect := default /- cross-file: combineEffects -/ }
                                  else
                                    if default then
                                      parseObjLit self node ty
                                    else
                                      if default then
                                        let elems : Array Any := node.elements.map (fun e =>
                                          if default then
                                            parseExpr self e.expression
                                          else
                                            parseExpr self e)
                                        { tag := "ArrayLit", elems := elems, type := default /- cross-file: TyArray -/, effect := default /- cross-file: combineEffects -/ }
                                      else
                                        if default then
                                          let inner : Any := parseExpr self node.expression
                                          { tag := "Await", expr := inner, type := ty, effect := Async }
                                        else
                                          if (default) || (default) then
                                            let inner : Any := parseExpr self node.expression
                                            { tag := "Cast", expr := inner, targetType := ty, type := ty, effect := default }
                                          else
                                            if default then
                                              parseExpr self node.expression
                                            else
                                              if default then
                                                parseExpr self node.expression
                                              else
                                                if default then
                                                  parseExpr self node.expression
                                                else
                                                  if default then
                                                    let inner : Any := parseExpr self node.expression
                                                    if default /- cross-file: isPure -/ then
                                                      default /- cross-file: litUnit -/
                                                    else
                                                      seq inner (default /- cross-file: litUnit -/)
                                                  else
                                                    if default then
                                                      parseExpr self node.expression
                                                    else
                                                      if default then
                                                        let inner : Any := parseExpr self node.expression
                                                        { tag := "App", fn := default /- cross-file: varExpr -/, args := #[inner], type := TyString, effect := Pure }
                                                      else
                                                        if default then
                                                          let template : TemplateLiteral := node.template
                                                          if default then
                                                            default /- cross-file: litStr -/
                                                          else
                                                            if default then
                                                              parseTemplate self template
                                                            else
                                                              default /- cross-file: holeExpr -/
                                                        else
                                                          if default then
                                                            default /- cross-file: litBool -/
                                                          else
                                                            if default then
                                                              default /- cross-file: litStr -/
                                                            else
                                                              if node.kind == ts.SyntaxKind.ObjectLiteralExpression then
                                                                parseObjLit self node ty
                                                              else
                                                                default /- cross-file: holeExpr -/

def ParserCtx.parsePropAccess (self : ParserCtxState) (node : Any) (ty : Any) : Any :=
  let obj : Any := parseExpr self node.expression
  let field : String := node.name.text
  if node.expression.kind == ts.SyntaxKind.ThisKeyword then
    { tag := "FieldAccess", obj := default /- cross-file: varExpr -/, field := field, type := ty, effect := Pure }
  else
    if default then
      let fullName : String := s!"{node.expression.text}.{field}"
      let global : Option GlobalTx := default /- cross-file: lookupGlobal -/
      if global then
        default /- cross-file: varExpr -/
      else
        let sym : Option Symbol := self.checker.getSymbolAtLocation node.expression
        if sym && (sym.flags &&& ts.SymbolFlags.Enum) then
          let enumName : String := node.expression.text
          { tag := "CtorApp", ctor := default, args := #[], type := ty, effect := Pure }
        else
          ()
    else
      ()
    if node.questionDotToken then
      let fieldAccess : Any := { tag := "FieldAccess", obj := default /- cross-file: varExpr -/, field := field, type := ty, effect := Pure }
      let lambdaBody : String := if default == "Option" then
        fieldAccess
      else
        { tag := "App", fn := default /- cross-file: varExpr -/, args := #[fieldAccess], type := default /- cross-file: TyOption -/, effect := Pure }
      let accessor : Any := { tag := "Lambda", params := #[{ name := "_oc", type := default }], body := lambdaBody, type := default /- cross-file: TyFn -/, effect := Pure }
      { tag := "App", fn := default, args := #[accessor], type := default /- cross-file: TyOption -/, effect := default }
    else
      { tag := "FieldAccess", obj := obj, field := field, type := ty, effect := Pure }

def ParserCtx.parseCall (self : ParserCtxState) (node : Any) (ty : Any) : StateT ParserCtxState IO Any :=
  do
    if default then
      let fullName : String := node.expression.getText self.sf
      let global : Option GlobalTx := default /- cross-file: lookupGlobal -/
      if global then
        let args : Array Any := node.arguments.map (fun a => parseExpr self a)
        do
          if global.maxArgs.isSome then
            let args := args.extract 0 global.maxArgs
          else
            let eff : Any := if global.io then
              IO
            else
              Pure
            pure { tag := "App", fn := default /- cross-file: varExpr -/, args := args, type := ty, effect := default /- cross-file: combineEffects -/ }
      else
        pure (parseMethodCall self node node.expression ty)
    else do
        if default then
          let global : Option GlobalTx := default /- cross-file: lookupGlobal -/
          if global then
            let args : Array Any := node.arguments.map (fun a => parseExpr self a)
            do
              if global.maxArgs.isSome then
                let args := args.extract 0 global.maxArgs
              else
                let eff : Any := if global.io then
                  IO
                else
                  Pure
                pure { tag := "App", fn := default /- cross-file: varExpr -/, args := args, type := ty, effect := default /- cross-file: combineEffects -/ }
          else
            pure ()
        else
          let fn : Any := parseExpr self node.expression
          let args : Array Any := node.arguments.map (fun a => parseExpr self a)
          pure { tag := "App", fn := fn, args := args, type := ty, effect := default /- cross-file: combineEffects -/ }

def ParserCtx.parseMethodCall (self : ParserCtxState) (node : Any) (acc : Any) (ty : Any) : Any :=
  let obj : Any := parseExpr self acc.expression
  let method : String := acc.name.text
  let args : Array Any := node.arguments.map (fun a => parseExpr self a)
  let allEff : Any := default /- cross-file: combineEffects -/
  let storageTarget : Bool := isStorageAccess self acc.expression
  if storageTarget then
    let fn : String := s!"Storage.{method}"
    { tag := "App", fn := default /- cross-file: varExpr -/, args := #[obj, args], type := ty, effect := Async }
  else
    { tag := "App", fn := default, args := args, type := ty, effect := allEff }

def ParserCtx.isStorageAccess (self : ParserCtxState) (node : Any) : Bool :=
  let text : String := node.getText self.sf
  ((text.includes ".storage") || (text == "storage")) || (text.includes "this.state.storage")

def ParserCtx.parseNew (self : ParserCtxState) (node : NewExpression) (ty : Any) : Any :=
  let name : String := node.expression.getText self.sf
  let args : Array Any := Array.map (fun a => parseExpr self a) (Option.getD node.arguments #[])
  if name == "Map" then
    default /- cross-file: varExpr -/
  else
    if name == "Set" then
      default /- cross-file: varExpr -/
    else
      if name == "Array" then
        { tag := "ArrayLit", elems := #[], type := ty, effect := Pure }
      else
        if (name == "Error") || (name.endsWith "Error") then
          { tag := "App", fn := default /- cross-file: varExpr -/, args := if args.size > 0 then
            #[args.getD 0 default]
          else
            #[default /- cross-file: litStr -/], type := ty, effect := Pure }
        else
          if name == "Response" then
            { tag := "App", fn := default /- cross-file: varExpr -/, args := args, type := ty, effect := Pure }
          else
            if name == "Promise" then
              default /- cross-file: holeExpr -/
            else
              if name == "URL" then
                { tag := "App", fn := default /- cross-file: varExpr -/, args := args, type := ty, effect := Pure }
              else
                { tag := "CtorApp", ctor := name, args := args, type := ty, effect := default /- cross-file: combineEffects -/ }

def ParserCtx.parseLambda (self : ParserCtxState) (node : ArrowFunction) : Any :=
  let params : Array Any := parseParams self node.parameters
  let eff : Any := default /- cross-file: inferNodeEffect -/
  let body : Any := if default then
    parseBlock self node.body eff
  else
    parseExpr self node.body
  let sig : Signature := self.checker.getSignatureFromDeclaration node
  let ret : Any := if sig then
    default /- cross-file: mapType -/
  else
    default
  { tag := "Lambda", params := params, body := body, type := default /- cross-file: TyFn -/, effect := eff }

def ParserCtx.parseBinary (self : ParserCtxState) (node : Any) (ty : Any) : Any :=
  let op : BinaryOperator := node.operatorToken.kind
  if (op == ts.SyntaxKind.EqualsToken) || (isCompoundAssign op) then
    let target : Any := parseExpr self node.left
    let rhs : Any := parseExpr self node.right
    let val : Any := if isCompoundAssign op then
      mkBinOp (compoundOp op) target rhs
    else
      rhs
    { tag := "Assign", target := target, value := val, type := TyUnit, effect := default /- cross-file: stateEffect -/ }
  else
    let left : Any := parseExpr self node.left
    let right : Any := parseExpr self node.right
    let irOp : String := tsBinOp op
    if !irOp then
      default /- cross-file: holeExpr -/
    else
      { tag := "BinOp", op := irOp, left := left, right := right, type := ty, effect := default /- cross-file: combineEffects -/ }

def ParserCtx.parsePrefix (self : ParserCtxState) (node : PrefixUnaryExpression) (ty : Any) : Any :=
  let operand : Any := parseExpr self node.operand
  match node.operator with
    | _ => { tag := "UnOp", op := "Not", operand := operand, type := TyBool, effect := default }
    | _ => { tag := "UnOp", op := "Neg", operand := operand, type := default, effect := default }
    | _ => { tag := "UnOp", op := "BitNot", operand := operand, type := ty, effect := default }
    | _ => { tag := "Assign", target := operand, value := mkBinOp "Add" operand (default /- cross-file: litNat -/), type := TyUnit, effect := default /- cross-file: stateEffect -/ }
    | _ => { tag := "Assign", target := operand, value := mkBinOp "Sub" operand (default /- cross-file: litNat -/), type := TyUnit, effect := default /- cross-file: stateEffect -/ }
    | _ => operand

def ParserCtx.parsePostfix (self : ParserCtxState) (node : PostfixUnaryExpression) : Any :=
  let operand : Any := parseExpr self node.operand
  if node.operator == ts.SyntaxKind.PlusPlusToken then
    { tag := "Assign", target := operand, value := mkBinOp "Add" operand (default /- cross-file: litNat -/), type := TyUnit, effect := default /- cross-file: stateEffect -/ }
  else
    { tag := "Assign", target := operand, value := mkBinOp "Sub" operand (default /- cross-file: litNat -/), type := TyUnit, effect := default /- cross-file: stateEffect -/ }

def ParserCtx.parseObjLit (self : ParserCtxState) (node : ObjectLiteralExpression) (ty : Any) : Any :=
  default

def ParserCtx.parseTemplate (self : ParserCtxState) (node : TemplateExpression) : Any :=
  default

-- // ─── Helpers ──────────────────────────────────────────────────────────────────
def seq (a : Any) (b : Any) : Any :=
  if default == "LitUnit" then
    a
  else
    if default == "LitUnit" then
      b
    else
      if default == "Sequence" then
        { tag := "Sequence", stmts := #[default, b], type := default, effect := default /- cross-file: combineEffects -/ }
      else
        { tag := "Sequence", stmts := #[a, b], type := default, effect := default /- cross-file: combineEffects -/ }

def mkBinOp (op : Any) (left : Any) (right : Any) : Any :=
  { tag := "BinOp", op := op, left := left, right := right, type := default, effect := Pure }

partial def branchReturns (e : Any) : Bool :=
  if (default == "Return") || (default == "Throw") then
    true
  else
    if default == "Sequence" then
      branchReturns default.getD (default.size - 1) default
    else
      if default == "Let" then
        branchReturns default
      else
        if default == "IfThenElse" then
          (branchReturns default) && (branchReturns default)
        else
          false

def exprToPat (e : Any) : Any :=
  if default == "LitString" then
    { tag := "PString", value := default }
  else
    if default == "LitNat" then
      { tag := "PLit", value := default }
    else
      if default == "LitBool" then
        { tag := "PLit", value := default }
      else
        if default == "LitNull" then
          { tag := "PNone" }
        else
          if default == "Var" then
            { tag := "PVar", name := default }
          else
            { tag := "PWild" }

def isCompoundAssign (kind : SyntaxKind) : Bool :=
  (((((((kind == ts.SyntaxKind.PlusEqualsToken) || (kind == ts.SyntaxKind.MinusEqualsToken)) || (kind == ts.SyntaxKind.AsteriskEqualsToken)) || (kind == ts.SyntaxKind.SlashEqualsToken)) || (kind == ts.SyntaxKind.PercentEqualsToken)) || (kind == ts.SyntaxKind.AmpersandEqualsToken)) || (kind == ts.SyntaxKind.BarEqualsToken)) || (kind == ts.SyntaxKind.CaretEqualsToken)

def compoundOp (kind : SyntaxKind) : Any :=
  match kind with
    | _ => "Add"
    | _ => "Sub"
    | _ => "Mul"
    | _ => "Div"
    | _ => "Mod"
    | _ => "Add"

def tsBinOp (kind : SyntaxKind) : String :=
  match kind with
    | _ => "Add"
    | _ => "Sub"
    | _ => "Mul"
    | _ => "Div"
    | _ => "Mod"
    | _ => "Eq"
    | _ => "Eq"
    | _ => "Ne"
    | _ => "Ne"
    | _ => "Lt"
    | _ => "Le"
    | _ => "Gt"
    | _ => "Ge"
    | _ => "And"
    | _ => "Or"
    | _ => "NullCoalesce"
    | _ => "BitAnd"
    | _ => "BitOr"
    | _ => "BitXor"
    | _ => "Shl"
    | _ => "Shr"
    | _ => none

def cap (s : String) : String :=
  if s then
    (s.getD 0 default.toUpper) ++ (default)
  else
    s

def fileToModuleName (filePath : String) : String :=
  let base : Any := default
  let parts : Any := default
  "TSLean.Generated." ++ (default)

def leadingComment (node : Any) (sf : Any) : Option String :=
  let ranges : Option (Array CommentRange) := default
  if !(ranges.bind (fun _oc => _oc.size)) then
    none
  else
    String.intercalate "\n" (Array.map (fun r => default) ranges)

/-- Extract JSDoc comment text (/** ... *\/) from a node. Strips @param/@returns/@throws tags — these use a different Lean 4 syntax. Returns just the summary description. -/
def jsdocComment (node : Any) (sf : Any) : Option String :=
  default

/-- Check if a statement has a const/let/var with an interface/object type that acts as index signature -/
def hasIndexSignature (node : Any) (checker : Any) : Bool :=
  if (!(default)) && (!(default)) then
    false
  else
    let members : NodeArray TypeElement := if default then
      node.members
    else
      node.members
    members.any (fun m => default)

end TSLean.Generated.Index