-- Auto-generated by ts-lean-transpiler
-- Source: /workspace/tslean/src/cli.ts

import TSLean.Runtime.Basic
import TSLean.Generated.SelfHost.Prelude
import TSLean.Runtime.Coercions
import TSLean.Runtime.Monad

open TSLean

namespace TSLean.Generated.Cli

-- // ─── Argument parsing ─────────────────────────────────────────────────────────
structure Args where
  mk ::
  mode : String
  input : String
  output : String
  verify : Bool
  ns : String
  deriving Repr, BEq, Inhabited

def parseArgs (argv : Array String) : StateT Unit IO Args :=
  do
    let args : Array String := argv.extract 2
    let mode : String := "single"
    let input : String := ""
    do
      let rec _loop_916 := fun i => do
        if i < args.size then do
            let a := args.getD i default
            _loop_916 (i + 1)
        else
          pure ()
      do
        if !input then do
            default
            default
        else do
            if !output then
              let output := if mode == "single" then
                input.replace "/\\.ts$/" ".lean"
              else
                (input.replace "/\\/$/" "") ++ "_lean"
            else
              pure { mode := mode, input := input, output := output, verify := verify, ns := ns }

-- // ─── Single file ──────────────────────────────────────────────────────────────
def single (opts : Args) : StateT Unit IO Unit :=
  do
    let input : String := opts.input
    let output : String := opts.output
    let verify : Bool := opts.verify
    do
      if !(default) then do
          default
          default
      else
        tryCatch (let src : Any := default
        let mod : Any := default /- cross-file: parseFile -/
        let rw : Any := default /- cross-file: rewriteModule -/
        let code : String := default /- cross-file: generateLean -/
        do
          if verify then
            let leanCode : String := default /- cross-file: generateVerification -/.leanCode
            let obligations : Array Any := default /- cross-file: generateVerification -/.obligations
            do
              if leanCode then
                let code := s!"{code}

-- Verification obligations
{leanCode}"
              else
                if obligations.size then
                  default
                else
                  pure ()
          else do
              default
              do
                default
                default) (fun err => do
          default
          do
            if default.getD "DEBUG" default then
              default
            else
              default)

-- // ─── Project mode ─────────────────────────────────────────────────────────────
def project (opts : Args) : Unit :=
  default

def opts : Args := parseArgs default

end TSLean.Generated.Cli