-- Auto-generated by ts-lean-transpiler
-- Source: /workspace/tslean/src/typemap/index.ts

import TSLean.Runtime.Basic
import TSLean.Generated.SelfHost.Prelude
import TSLean.Runtime.Coercions
import TSLean.Stdlib.HashMap

open TSLean TSLean.Stdlib.HashMap

namespace TSLean.Generated.Index

def MAX_TYPE_DEPTH : Float := 20

def FALLBACK_TYPE_VAR : String := "α"

def TS_ANON_TYPE : String := "__type"

def DISCRIMINANT_FIELDS : Array String := #["kind", "type", "tag", "ok", "hasValue", "_type"]

/-- Map a TypeScript compiler type to an IR type. Handles primitives, unions, intersections, arrays, tuples, object types, generic references, conditional types, and branded newtypes. -/
partial def mapType (t : Type) (checker : Any) (depth : Float := 0) : Any :=
  if depth > MAX_TYPE_DEPTH then
    default /- cross-file: TyRef -/
  else
    let f : TypeFlags := t.flags
    if f &&& ts.TypeFlags.String then
      TyString
    else
      if f &&& ts.TypeFlags.Number then
        TyFloat
      else
        if f &&& ts.TypeFlags.Boolean then
          TyBool
        else
          if f &&& ts.TypeFlags.Undefined then
            default /- cross-file: TyOption -/
          else
            if f &&& ts.TypeFlags.Null then
              default /- cross-file: TyOption -/
            else
              if f &&& ts.TypeFlags.Void then
                TyUnit
              else
                if f &&& ts.TypeFlags.Never then
                  TyNever
                else
                  if f &&& ts.TypeFlags.Any then
                    default /- cross-file: TyRef -/
                  else
                    if f &&& ts.TypeFlags.Unknown then
                      default /- cross-file: TyRef -/
                    else
                      if f &&& ts.TypeFlags.BigInt then
                        TyInt
                      else
                        if f &&& ts.TypeFlags.StringLiteral then
                          TyString
                        else
                          if f &&& ts.TypeFlags.NumberLiteral then
                            TyFloat
                          else
                            if f &&& ts.TypeFlags.BooleanLiteral then
                              TyBool
                            else
                              if f &&& ts.TypeFlags.TypeParameter then
                                default /- cross-file: TyVar -/
                              else
                                if t.isUnion then
                                  mapUnion t checker depth
                                else
                                  if t.isIntersection then
                                    mapIntersection t checker depth
                                  else
                                    if checker.isArrayType t then
                                      let elem : Type := (checker.getTypeArguments t).getD 0 default
                                      default /- cross-file: TyArray -/
                                    else
                                      if checker.isTupleType t then
                                        let args : Array Type := checker.getTypeArguments t
                                        default /- cross-file: TyTuple -/
                                      else
                                        if f &&& ts.TypeFlags.Object then
                                          mapObject t checker depth
                                        else
                                          if f &&& ts.TypeFlags.Conditional then
                                            let c : ConditionalType := t
                                            let resolved : Option Type := default
                                            mapType (Option.getD resolved c.checkType) checker (depth + 1)
                                          else
                                            if f &&& ts.TypeFlags.Index then
                                              TyString
                                            else
                                              default /- cross-file: TyRef -/

-- // ─── Union types ────────────────────────────────────────────────────────────────
def mapUnion (t : UnionType) (checker : Any) (depth : Float) : Any :=
  let types : Array Type := t.types
  let withoutNil : Array Type := Array.filter types (fun x => !(x.flags &&& (ts.TypeFlags.Undefined ||| ts.TypeFlags.Null)))
  if (withoutNil.size == 1) && (withoutNil.size < types.size) then
    default /- cross-file: TyOption -/
  else
    if types.all (fun x => x.flags &&& ts.TypeFlags.StringLiteral) then
      let alias : Option String := getAliasName t
      if alias then
        default /- cross-file: TyRef -/
      else
        TyString
    else
      if (types.size == 2) && (types.all (fun x => x.flags &&& ts.TypeFlags.BooleanLiteral)) then
        TyBool
      else
        let alias : Option String := getAliasName t
        if alias then
          let aliasArgs : Option (Array Type) := default
          if aliasArgs && (aliasArgs.size > 0) then
            default /- cross-file: TyRef -/
          else
            default /- cross-file: TyRef -/
        else
          if withoutNil.size > 0 then
            mapType withoutNil.getD 0 default checker (depth + 1)
          else
            default /- cross-file: TyRef -/

-- // ─── Intersection types ─────────────────────────────────────────────────────────
def mapIntersection (t : IntersectionType) (checker : Any) (depth : Float) : Any :=
  let base : Option Type := t.types.find? (fun x => x.flags &&& (ts.TypeFlags.String ||| ts.TypeFlags.Number))
  let brand : Option Type := t.types.find? (fun x => (x.flags &&& ts.TypeFlags.Object) && (x.getProperties.any (fun p => (p.name.startsWith "__brand") || (p.name.startsWith "_brand"))))
  if base && brand then
    let alias : Option String := getAliasName t
    if alias then
      default /- cross-file: TyRef -/
    else
      if base.flags &&& ts.TypeFlags.String then
        TyString
      else
        TyFloat
  else
    let alias : Option String := getAliasName t
    if alias then
      default /- cross-file: TyRef -/
    else
      let concrete : Option Type := t.types.find? (fun x => (!(x.flags &&& ts.TypeFlags.Object)) || (x.getProperties.size > 0))
      if concrete then
        mapType concrete checker (depth + 1)
      else
        default /- cross-file: TyRef -/

-- // ─── Object types ───────────────────────────────────────────────────────────────
def mapObject (t : ObjectType) (checker : Any) (depth : Float) : Any :=
  if t.objectFlags &&& ts.ObjectFlags.Reference then
    mapTypeRef t checker depth
  else
    let sym : Symbol := t.symbol
    if !sym then
      default /- cross-file: TyRef -/
    else
      let calls : Array Signature := checker.getSignaturesOfType t ts.SignatureKind.Call
      if calls.size > 0 then
        let sig : Signature := calls.getD 0 default
        let params : Array Any := Array.map (fun p =>
          let pt : Type := checker.getTypeOfSymbolAtLocation p (Option.getD p.valueDeclaration (Array.get? p.declarations 0))
          mapType pt checker (depth + 1)) (sig.getParameters)
        default /- cross-file: TyFn -/
      else
        let name : String := sym.name
        if name == TS_ANON_TYPE then
          default /- cross-file: TyRef -/
        else
          if (name == "Error") || (name.endsWith "Error") then
            TyString
          else
            default /- cross-file: TyRef -/

-- // ─── Generic type references ────────────────────────────────────────────────────
def mapTypeRef (t : TypeReference) (checker : Any) (depth : Float) : Any :=
  let name : String := Option.getD (t.target.symbol.bind (fun _oc => some _oc.name)) ""
  let args : Array Type := checker.getTypeArguments t
  let map1 : Unit → Any := fun _ =>
    if args.getD 0 default then
      mapType args.getD 0 default checker (depth + 1)
    else
      default /- cross-file: TyRef -/
  let map2 : Float → Any := fun i =>
    if args.getD i default then
      mapType args.getD i default checker (depth + 1)
    else
      default /- cross-file: TyRef -/
  match name with
    | "Array" => default /- cross-file: TyArray -/
    | "ReadonlyArray" => default /- cross-file: TyArray -/
    | "Map" => default /- cross-file: TyMap -/
    | "WeakMap" => default /- cross-file: TyMap -/
    | "Set" => default /- cross-file: TySet -/
    | "WeakSet" => default /- cross-file: TySet -/
    | "Promise" => default /- cross-file: TyPromise -/
    | "Record" => default /- cross-file: TyMap -/
    | "Readonly" => default /- cross-file: map1 -/
    | "NonNullable" => default /- cross-file: map1 -/
    | _ => if args.size == 0 then
      default /- cross-file: TyRef -/
    else
      default /- cross-file: TyRef -/

/-- Convert an IR type to its Lean 4 syntax string. -/
def irTypeToLean (t : Any) (parens : Bool := false) : String :=
  let s : String := typeStr t
  if parens && (s.includes " ") then
    s!"({s})"
  else
    s

partial def typeStr (t : Any) : String :=
  match default with
    | "Nat" => "Nat"
    | "Int" => "Int"
    | "Float" => "Float"
    | "String" => "String"
    | "Bool" => "Bool"
    | "Unit" => "Unit"
    | "Never" => "Empty"
    | "Option" => "Option " ++ (irTypeToLean default true)
    | "Array" => "Array " ++ (irTypeToLean default true)
    | "Tuple" => if default.size == 0 then
      "Unit"
    else
      ("(" ++ (String.intercalate " × " (Array.map typeStr default))) ++ ")"
    | "Function" => let paramStr : String := if default.size == 0 then
      "Unit"
    else
      String.intercalate " → " (Array.map (fun p => irTypeToLean p true) default)
    (s!"{paramStr} → ") ++ (typeStr default)
    | "Map" => (("AssocMap " ++ (irTypeToLean default true)) ++ " ") ++ (irTypeToLean default true)
    | "Set" => "AssocSet " ++ (irTypeToLean default true)
    | "Promise" => let inner : Any := default
    if default == "Promise" then
      "IO " ++ (irTypeToLean default true)
    else
      "IO " ++ (irTypeToLean inner true)
    | "Result" => (("Except " ++ (irTypeToLean default true)) ++ " ") ++ (irTypeToLean default true)
    | "TypeRef" => let tsOnlyTypes : AssocSet String := AssocSet.empty
    if AssocMap.contains tsOnlyTypes default then
      "Any"
    else
      if default.size == 0 then
        default
      else
        (s!"{default} ") ++ (String.intercalate " " (Array.map (fun a => irTypeToLean a true) default))
    | "TypeVar" => default
    | "Structure" => default
    | "Inductive" => default
    | "Dependent" => (((s!"({default} : ") ++ (typeStr default)) ++ ") → ") ++ (typeStr default)
    | "Subtype" => ((("{x : " ++ (typeStr default)) ++ " // ") ++ default) ++ "}"
    | "Universe" => if default == 0 then
      "Prop"
    else
      s!"Type {default}"
    | _ => "Any"

-- // ─── Struct field extraction ────────────────────────────────────────────────────
-- A single field extracted from a TypeScript interface or class declaration.
structure StructField where
  mk ::
  name : String
  type : Any
  optional : Bool
  mutable : Bool
  deriving Repr, BEq, Inhabited

/-- Extract struct fields from a TypeScript interface or class declaration. Handles optional fields (`?`), readonly modifiers, and resolves types via the type checker. -/
def extractStructFields (node : Any) (checker : Any) : Array StructField :=
  default

-- // ─── Discriminated union detection ──────────────────────────────────────────────
-- Result of detecting a discriminated union in a TypeScript union type.
structure DiscriminantInfo where
  mk ::
  field : String
  variants : Array String
  deriving Repr, BEq, Inhabited

/-- Detect whether a TypeScript union type is a discriminated union. Checks each known discriminant field name in priority order.  Returns the first field for which every union member has a unique string literal value. -/
def detectDiscriminatedUnion (t : UnionType) (checker : Any) : Option DiscriminantInfo :=
  default

def tryField (types : Array ObjectType) (field : String) (checker : Any) : Option DiscriminantInfo :=
  default

/-- Extract type parameter names from a TypeScript declaration. -/
def extractTypeParams (node : Any) : Array String :=
  Array.map (fun tp => tp.name.text) (Option.getD node.typeParameters #[])

/-- Access the `aliasSymbol.name` on a TypeScript type. This property is not in the public TS API typings but is stable across TypeScript versions (4.x–5.x).  It gives the user-defined alias name for union and intersection types. -/
def getAliasName (t : Type) : Option String :=
  default.bind (fun _oc => _oc.name)

end TSLean.Generated.Index