-- Auto-generated by ts-lean-transpiler
-- Source: /workspace/tslean/src/verification/index.ts

import TSLean.Runtime.Basic
import TSLean.Generated.SelfHost.Prelude
import TSLean.Runtime.Coercions

open TSLean

namespace TSLean.Generated.Index

-- // ─── Types ────────────────────────────────────────────────────────────────────
inductive ObligationKind where
  | ArrayBounds
  | DivisionSafe
  | OptionIsSome
  | InvariantPreserved
  | TerminationBy
  deriving Repr, BEq, Inhabited

structure ProofObligation where
  mk ::
  kind : ObligationKind
  funcName : String
  detail : String
  deriving Repr, BEq, Inhabited

structure VerificationResult where
  mk ::
  obligations : Array Any
  leanCode : String
  deriving Repr, BEq, Inhabited

-- // ─── Public API ───────────────────────────────────────────────────────────────
def generateVerification (mod : Any) : VerificationResult :=
  default

-- // ─── Collection ───────────────────────────────────────────────────────────────
partial def collectDecl (d : Any) (acc : Array Any) : Unit :=
  default

partial def collectExpr (e : Any) (fn : String) (acc : Array Any) : Unit :=
  default

partial def exprSummary (e : Any) : String :=
  match default with
    | "Var" => default
    | "FieldAccess" => ((exprSummary default) ++ ".") ++ default
    | "LitNat" => default /- cross-file: String -/
    | "LitString" => serialize default
    | _ => "_"

-- // ─── Emission ─────────────────────────────────────────────────────────────────
def emitObligation (o : Any) : String :=
  let safeName : String := default.replace "/[^a-zA-Z0-9_]/g" "_"
  match default with
    | "ArrayBounds" => String.intercalate "\n" #[s!"-- Array bounds safety for `{default}` accessing {default}", s!"theorem {safeName}_idx_in_bounds", "    (arr : Array α) (idx : Nat) (h : idx < arr.size) :", "    arr[idx]! = arr[⟨idx, h⟩] := by", "  simp [Array.get!_eq_getElem]"]
    | "DivisionSafe" => String.intercalate "\n" #[s!"-- Division safety for `{default}` divisor: {default}", s!"theorem {safeName}_divisor_nonzero", "    (n d : Float) (h : d ≠ 0) : n / d = n / d := rfl"]
    | "OptionIsSome" => String.intercalate "\n" #[s!"-- Option safety for `{default}` accessing {default}", s!"theorem {safeName}_val_is_some", "    {α : Type} (opt : Option α) (h : opt.isSome) :", "    opt.get!.isSome := by cases opt <;> simp_all"]
    | "InvariantPreserved" => String.intercalate "\n" #[s!"-- Invariant preserved by `{default}`", s!"theorem {safeName}_invariant_preserved", "    (s : σ) (h : invariant s) : ∃ s', invariant s' := ⟨s, h⟩"]
    | "TerminationBy" => s!"-- termination_by {default} -- for `{default}`"

end TSLean.Generated.Index