// E2E project mode tests: run --project on full-project fixture.

import { describe, it, expect, beforeAll } from 'vitest';
import { execSync } from 'child_process';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

const ROOT   = process.cwd();
const CLI    = path.join(ROOT, 'src/cli.ts');
const FP_DIR = path.join(ROOT, 'tests/fixtures/full-project');

let outDir: string;
let files: Record<string, string> = {};

beforeAll(() => {
  outDir = fs.mkdtempSync(path.join(os.tmpdir(), 'tslean-e2e-proj-'));
  execSync(`npx tsx ${CLI} --project ${FP_DIR} -o ${outDir}`, { stdio: 'pipe' });
  function read(dir: string) {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, e.name);
      if (e.isDirectory()) { read(full); continue; }
      if (e.name.endsWith('.lean')) {
        files[path.relative(outDir, full)] = fs.readFileSync(full, 'utf8');
      }
    }
  }
  read(outDir);
});

describe('Project output: file existence', () => {
  it('at least 4 lean files produced',   () => expect(Object.keys(files).length).toBeGreaterThanOrEqual(4));
  it('Shared/Types.lean exists',         () => expect(Object.keys(files).some(k => k.includes('Types.lean'))).toBe(true));
  it('Shared/Validators.lean exists',    () => expect(Object.keys(files).some(k => k.includes('Validators.lean'))).toBe(true));
  it('Backend/AuthDo.lean exists',       () => expect(Object.keys(files).some(k => k.includes('AuthDo.lean'))).toBe(true));
  it('Backend/Router.lean exists',       () => expect(Object.keys(files).some(k => k.includes('Router.lean'))).toBe(true));
});

describe('Project output: every file has correct header', () => {
  it('auto-generated header in all files', () => {
    for (const [n, c] of Object.entries(files)) {
      expect(c, n).toContain('-- Auto-generated by ts-lean-transpiler');
    }
  });
  it('open TSLean in all files', () => {
    for (const [n, c] of Object.entries(files)) {
      expect(c, n).toContain('open TSLean');
    }
  });
  it('each file has at least one declaration', () => {
    for (const [n, c] of Object.entries(files)) {
      expect(c, n).toMatch(/\b(def|structure|inductive|abbrev)\s+\w/);
    }
  });
});

describe('Project output: Shared/Types.lean', () => {
  let code: string;
  beforeAll(() => { code = files[Object.keys(files).find(k => k.includes('Types.lean'))!] ?? ''; });

  it('UserId is structure',    () => expect(code).toContain('structure UserId'));
  it('RoomId is structure',    () => expect(code).toContain('structure RoomId'));
  it('User structure',         () => expect(code).toContain('structure User'));
  it('makeApiSuccess defined', () => expect(code).toMatch(/def makeApiSuccess/));
  it('makeApiError defined',   () => expect(code).toMatch(/def makeApiError/));
});

describe('Project output: Shared/Validators.lean', () => {
  let code: string;
  beforeAll(() => { code = files[Object.keys(files).find(k => k.includes('Validators.lean'))!] ?? ''; });

  it('validateEmail defined',      () => expect(code).toMatch(/def validateEmail/));
  it('validateDisplayName defined', () => expect(code).toMatch(/def validateDisplayName/));
  it('validateRoomName defined',   () => expect(code).toMatch(/def validateRoomName/));
  it('ValidationResult structure', () => expect(code).toContain('structure ValidationResult'));
});

describe('Project output: Backend/AuthDo.lean cross-file imports', () => {
  let code: string;
  beforeAll(() => { code = files[Object.keys(files).find(k => k.includes('AuthDo.lean'))!] ?? ''; });

  it('imports Shared.Types (no .js)', () => {
    expect(code).toContain('import TSLean.Generated.Shared.Types');
    expect(code).not.toContain('import TSLean.Generated.Shared.Types.js');
  });
  it('imports Shared.Validators',    () => expect(code).toContain('import TSLean.Generated.Shared.Validators'));
  it('imports DO Http',              () => expect(code).toContain('import TSLean.DurableObjects.Http'));
  it('StoredUser structure emitted', () => expect(code).toContain('structure StoredUser'));
  it('register function defined',    () => expect(code).toMatch(/def.*register/));
  it('login function defined',       () => expect(code).toMatch(/def.*login/));
  it('verify function defined',      () => expect(code).toMatch(/def.*verify/));
  it('content not empty stub',       () => expect(code.split('\n').length).toBeGreaterThan(20));
});

describe('Project output: no duplicates', () => {
  it('no duplicate import lines', () => {
    for (const [n, content] of Object.entries(files)) {
      const imps = content.split('\n').filter(l => l.startsWith('import '));
      const unique = new Set(imps);
      expect(unique.size, `${n} has duplicate imports`).toBe(imps.length);
    }
  });
});

describe('Project output: balanced parentheses', () => {
  it('all files balanced', () => {
    for (const [n, content] of Object.entries(files)) {
      let depth = 0;
      for (const ch of content) {
        if (ch === '(') depth++;
        if (ch === ')') depth--;
        if (depth < 0) break;
      }
      expect(depth, `${n} unmatched parens`).toBe(0);
    }
  });
});

describe('Project with --verify', () => {
  it('produces valid output', () => {
    const vdir = fs.mkdtempSync(path.join(os.tmpdir(), 'tslean-e2e-verify-'));
    execSync(`npx tsx ${CLI} --project ${FP_DIR} -o ${vdir} --verify`, { stdio: 'pipe' });
    const leans = fs.readdirSync(vdir, { recursive: true, withFileTypes: true })
      .filter(e => e.isFile() && (e.name as string).endsWith('.lean'));
    expect(leans.length).toBeGreaterThan(0);
    fs.rmSync(vdir, { recursive: true });
  });
});
