// Tests for the Lean 4 code generator.

import { describe, it, expect } from 'vitest';
import { generateLean } from '../src/codegen/index.js';
import {
  IRModule, IRDecl, IRExpr,
  TyString, TyFloat, TyBool, TyUnit, TyNat, TyArray, TyOption, TyRef, TyMap, TySet, TyTuple,
  Pure, IO, Async, stateEffect, exceptEffect, combineEffects,
  litStr, litNat, litBool, litUnit, varExpr, holeExpr,
} from '../src/ir/types.js';

function mod(decls: IRDecl[]): IRModule {
  return { name: 'TSLean.Test', imports: [{ module: 'TSLean.Runtime.Basic' }], decls, comments: [], sourceFile: 'test.ts' };
}

// ─── Header ───────────────────────────────────────────────────────────────────

describe('generateLean – header', () => {
  it('emits auto-generated comment', () => expect(generateLean(mod([]))).toContain('Auto-generated by ts-lean-transpiler'));
  it('emits open TSLean',            () => expect(generateLean(mod([]))).toContain('open TSLean'));
  it('emits imports',                () => expect(generateLean(mod([]))).toContain('import TSLean.Runtime.Basic'));
  it('deduplicates imports', () => {
    const m = mod([]);
    m.imports.push({ module: 'TSLean.Runtime.Basic' });
    const code = generateLean(m);
    expect((code.match(/import TSLean.Runtime.Basic/g) ?? []).length).toBe(1);
  });
});

// ─── Structures ───────────────────────────────────────────────────────────────

describe('generateLean – structures', () => {
  it('basic structure', () => {
    const code = generateLean(mod([{
      tag: 'StructDef', name: 'Point', typeParams: [],
      fields: [{ name: 'x', type: TyFloat }, { name: 'y', type: TyFloat }],
      deriving: ['Repr', 'BEq'],
    }]));
    expect(code).toContain('structure Point');
    expect(code).toContain('x : Float');
    expect(code).toContain('y : Float');
    expect(code).toContain('deriving Repr, BEq');
  });

  it('structure with type params', () => {
    const code = generateLean(mod([{
      tag: 'StructDef', name: 'Box', typeParams: ['T'],
      fields: [{ name: 'val', type: TyRef('T') }],
    }]));
    expect(code).toContain('structure Box');
    expect(code).toContain('(T : Type)');  // structs use explicit params
    expect(code).toContain('val : T');
  });

  it('struct inside namespace: fields appear after mk ::', () => {
    const code = generateLean(mod([{
      tag: 'Namespace', name: 'Geo', decls: [{
        tag: 'StructDef', name: 'Rect', typeParams: [],
        fields: [{ name: 'w', type: TyFloat }, { name: 'h', type: TyFloat }],
        deriving: [],
      }],
    }]));
    const lines = code.split('\n');
    const mkIdx = lines.findIndex(l => l.trimEnd().endsWith('mk ::'));
    const wIdx  = lines.findIndex(l => l.includes('w : Float'));
    expect(mkIdx).toBeGreaterThan(-1);
    expect(wIdx).toBeGreaterThan(-1);
    // Fields must appear after mk ::
    expect(wIdx).toBeGreaterThan(mkIdx);
    // Fields must be indented at least as much as the structure keyword
    const structIdx = lines.findIndex(l => l.includes('structure Rect'));
    const structInd = lines[structIdx].match(/^(\s*)/)?.[1].length ?? 0;
    const wInd      = lines[wIdx].match(/^(\s*)/)?.[1].length ?? 0;
    expect(wInd).toBeGreaterThanOrEqual(structInd);
  });
});

// ─── Inductives ───────────────────────────────────────────────────────────────

describe('generateLean – inductives', () => {
  it('no-arg constructors', () => {
    const code = generateLean(mod([{
      tag: 'InductiveDef', name: 'Color', typeParams: [],
      ctors: [{ name: 'Red', fields: [] }, { name: 'Green', fields: [] }, { name: 'Blue', fields: [] }],
    }]));
    expect(code).toContain('inductive Color');
    expect(code).toContain('| Red');
    expect(code).toContain('| Green');
    expect(code).toContain('| Blue');
    expect(code).toContain('deriving Repr, BEq');
  });

  it('constructors with named fields', () => {
    const code = generateLean(mod([{
      tag: 'InductiveDef', name: 'Shape', typeParams: [],
      ctors: [
        { name: 'Circle', fields: [{ name: 'radius', type: TyFloat }] },
        { name: 'Rect',   fields: [{ name: 'w', type: TyFloat }, { name: 'h', type: TyFloat }] },
      ],
    }]));
    expect(code).toContain('| Circle (radius : Float)');
    expect(code).toContain('| Rect (w : Float) (h : Float)');
  });

  it('inductive with type param', () => {
    const code = generateLean(mod([{
      tag: 'InductiveDef', name: 'Maybe', typeParams: ['T'],
      ctors: [{ name: 'Nothing', fields: [] }, { name: 'Just', fields: [{ type: TyRef('T') }] }],
    }]));
    expect(code).toContain('inductive Maybe (T : Type)');  // inductives use explicit params for proper lake build
  });
});

// ─── Type aliases ─────────────────────────────────────────────────────────────

describe('generateLean – type aliases', () => {
  it('emits abbrev', () => {
    const code = generateLean(mod([{ tag: 'TypeAlias', name: 'Name', typeParams: [], body: TyString }]));
    expect(code).toContain('abbrev Name := String');
  });

  it('abbrev with type param', () => {
    const code = generateLean(mod([{
      tag: 'TypeAlias', name: 'Opt', typeParams: ['T'],
      body: { tag: 'Option', inner: TyRef('T') },
    }]));
    expect(code).toContain('abbrev Opt {T : Type} := Option T');
  });
});

// ─── Functions ────────────────────────────────────────────────────────────────

describe('generateLean – functions', () => {
  it('pure function', () => {
    const code = generateLean(mod([{
      tag: 'FuncDef', name: 'add', typeParams: [],
      params: [{ name: 'a', type: TyFloat }, { name: 'b', type: TyFloat }],
      retType: TyFloat, effect: Pure,
      body: { tag: 'BinOp', op: 'Add', left: varExpr('a', TyFloat), right: varExpr('b', TyFloat), type: TyFloat, effect: Pure },
    }]));
    expect(code).toContain('def add (a : Float) (b : Float) : Float :=');
    expect(code).toContain('a + b');
  });

  it('async function → IO return type', () => {
    const code = generateLean(mod([{
      tag: 'FuncDef', name: 'fetch', typeParams: [],
      params: [{ name: 'url', type: TyString }],
      retType: TyString, effect: Async, body: litStr('response'),
    }]));
    expect(code).toContain('def fetch');
    expect(code).toContain('IO');
  });

  it('function with type params', () => {
    const code = generateLean(mod([{
      tag: 'FuncDef', name: 'identity', typeParams: ['T'],
      params: [{ name: 'x', type: TyRef('T') }],
      retType: TyRef('T'), effect: Pure, body: varExpr('x', TyRef('T')),
    }]));
    expect(code).toContain('{T : Type}' || '(T : Type)');
    expect(code).toContain('(x : T)');
  });

  it('default parameter value uses genExpr', () => {
    const code = generateLean(mod([{
      tag: 'FuncDef', name: 'greet', typeParams: [],
      params: [
        { name: 'name', type: TyString },
        { name: 'times', type: TyNat, default_: litNat(3) },
      ],
      retType: TyString, effect: Pure, body: litStr('hello'),
    }]));
    expect(code).toContain(':= 3');
    expect(code).not.toMatch(/times\s*:=\s*times/);
  });

  it('State effect → StateT in return', () => {
    const code = generateLean(mod([{
      tag: 'FuncDef', name: 'count', typeParams: [],
      params: [], retType: TyNat, effect: stateEffect(TyRef('S')), body: litNat(0),
    }]));
    expect(code).toContain('StateT');
  });

  it('Except effect → ExceptT in return', () => {
    const code = generateLean(mod([{
      tag: 'FuncDef', name: 'risky', typeParams: [],
      params: [], retType: TyString, effect: exceptEffect(TyString), body: litStr('ok'),
    }]));
    expect(code).toContain('ExceptT');
  });

  it('Combined effect uses monadString', () => {
    const eff = combineEffects([stateEffect(TyString), exceptEffect(TyFloat)]);
    const code = generateLean(mod([{
      tag: 'FuncDef', name: 'complex', typeParams: [],
      params: [], retType: TyNat, effect: eff, body: litNat(0),
    }]));
    expect(code).toMatch(/StateT|ExceptT/);
  });

  it('Lean keywords in names get escaped', () => {
    const code = generateLean(mod([{
      tag: 'FuncDef', name: 'where', typeParams: [],
      params: [], retType: TyUnit, effect: Pure, body: litUnit(),
    }]));
    expect(code).toContain('«where»');
  });
});

// ─── Expressions ──────────────────────────────────────────────────────────────

describe('generateLean – expressions', () => {
  function expr(e: IRExpr, eff = Pure): string {
    const code = generateLean(mod([{ tag: 'FuncDef', name: 'f', typeParams: [], params: [], retType: TyUnit, effect: eff, body: e }]));
    const idx  = code.indexOf(':=\n') + 3;
    return code.slice(idx).trimStart();
  }

  it('LitUnit → ()',     () => expect(expr(litUnit())).toContain('()'));
  it('LitNull → none',  () => expect(expr({ tag: 'LitNull', type: TyOption(TyUnit), effect: Pure })).toContain('none'));
  it('LitBool true',    () => expect(expr(litBool(true))).toContain('true'));
  it('LitNat',          () => expect(expr(litNat(7))).toContain('7'));
  it('LitFloat',        () => expect(expr({ tag: 'LitFloat', value: 3.14, type: TyFloat, effect: Pure })).toContain('3.14'));
  it('LitString',       () => expect(expr(litStr('hi'))).toContain('"hi"'));
  it('Hole → default value', () => expect(expr(holeExpr())).toMatch(/()|default|sorry/));
  it('Var → name',      () => expect(expr(varExpr('x'))).toContain('x'));

  it('ArrayLit → #[...]', () =>
    expect(expr({ tag: 'ArrayLit', elems: [litNat(1), litNat(2)], type: TyArray(TyNat), effect: Pure })).toContain('#[1, 2]'));

  it('TupleLit → (...)', () =>
    expect(expr({ tag: 'TupleLit', elems: [litNat(1), litStr('a')], type: TyTuple([TyNat, TyString]), effect: Pure })).toContain('(1, "a")'));

  it('StructLit → { ... }', () =>
    expect(expr({ tag: 'StructLit', typeName: 'Point', fields: [{ name: 'x', value: litNat(1) }, { name: 'y', value: litNat(2) }], type: TyRef('Point'), effect: Pure })).toContain('{ x := 1, y := 2 }'));

  it('if-then-else', () =>
    expect(expr({ tag: 'IfThenElse', cond: litBool(true), then: litNat(1), else_: litNat(2), type: TyNat, effect: Pure })).toContain('if true then'));

  it('match expression', () => {
    const code = expr({
      tag: 'Match', scrutinee: varExpr('x', TyNat),
      cases: [
        { pattern: { tag: 'PLit', value: 0 }, body: litStr('zero') },
        { pattern: { tag: 'PWild' },           body: litStr('other') },
      ],
      type: TyString, effect: Pure,
    });
    expect(code).toContain('match x with');
    expect(code).toContain('| 0');
    expect(code).toContain('| _');
  });

  it('PCtor pattern uses dot syntax', () => {
    const code = expr({
      tag: 'Match', scrutinee: varExpr('s', TyRef('Shape')),
      cases: [{ pattern: { tag: 'PCtor', ctor: 'Shape.Circle', args: [{ tag: 'PVar', name: 'r' }] }, body: varExpr('r', TyFloat) }],
      type: TyFloat, effect: Pure,
    });
    expect(code).toContain('.Circle r');
  });

  it('BinOp Add Float → +',        () => expect(expr({ tag: 'BinOp', op: 'Add', left: varExpr('a', TyFloat), right: varExpr('b', TyFloat), type: TyFloat, effect: Pure })).toContain('a + b'));
  it('BinOp Add String → ++',      () => expect(expr({ tag: 'BinOp', op: 'Add', left: varExpr('a', TyString), right: varExpr('b', TyString), type: TyString, effect: Pure })).toContain('a ++ b'));
  it('BinOp NullCoalesce → Option.getD', () => expect(expr({ tag: 'BinOp', op: 'NullCoalesce', left: varExpr('x', TyOption(TyNat)), right: litNat(0), type: TyNat, effect: Pure })).toContain('Option.getD'));

  it('UnOp Not',    () => expect(expr({ tag: 'UnOp', op: 'Not',    operand: litBool(true), type: TyBool, effect: Pure })).toContain('!true'));
  it('UnOp Neg',    () => expect(expr({ tag: 'UnOp', op: 'Neg',    operand: varExpr('x', TyFloat), type: TyFloat, effect: Pure })).toContain('-x'));
  it('UnOp BitNot', () => expect(expr({ tag: 'UnOp', op: 'BitNot', operand: varExpr('x', TyNat), type: TyNat, effect: Pure })).toContain('~~~x'));

  it('Panic → panic!', () =>
    expect(expr({ tag: 'Panic', msg: 'unreachable', type: TyUnit, effect: Pure })).toContain('panic!'));

  it('Throw → throw', () =>
    expect(expr({ tag: 'Throw', error: litStr('err'), type: TyUnit, effect: exceptEffect(TyString) }, exceptEffect(TyString))).toContain('throw'));

  it('Return in IO context → pure val', () =>
    expect(expr({ tag: 'Return', value: litNat(42), type: TyNat, effect: Pure }, Async)).toContain('pure 42'));

  it('Assign self.field → modify', () => {
    const code = expr({
      tag: 'Assign',
      target: { tag: 'FieldAccess', obj: varExpr('self', TyRef('S')), field: 'count', type: TyNat, effect: Pure },
      value: litNat(0),
      type: TyUnit, effect: stateEffect(TyRef('S')),
    });
    expect(code).toContain('modify');
    expect(code).toContain('count');
  });

  it('do-notation Bind', () => {
    const code = expr({
      tag: 'DoBlock',
      stmts: [
        { tag: 'DoBind',   name: 'x', expr: varExpr('fetchSomething', TyNat) },
        { tag: 'DoReturn', value: varExpr('x', TyNat) },
      ],
      type: TyNat, effect: Async,
    }, Async);
    expect(code).toContain('do');
    expect(code).toContain('let x ←');
    expect(code).toContain('return x');
  });
});

// ─── Namespace ────────────────────────────────────────────────────────────────

describe('generateLean – namespace', () => {
  it('emits namespace/end', () => {
    const code = generateLean(mod([{
      tag: 'Namespace', name: 'Utils', decls: [{
        tag: 'FuncDef', name: 'helper', typeParams: [], params: [], retType: TyUnit, effect: Pure, body: litUnit(),
      }],
    }]));
    expect(code).toContain('namespace Utils');
    expect(code).toContain('end Utils');
    expect(code).toContain('def helper');
  });
});

// ─── Map / Set types ──────────────────────────────────────────────────────────

describe('generateLean – Map/Set type emission', () => {
  it('Map field → AssocMap', () => {
    const code = generateLean(mod([{
      tag: 'StructDef', name: 'Registry', typeParams: [],
      fields: [{ name: 'entries', type: TyMap(TyString, TyNat) }],
    }]));
    expect(code).toContain('AssocMap String Nat');
  });

  it('Set field → AssocSet', () => {
    const code = generateLean(mod([{
      tag: 'StructDef', name: 'Bag', typeParams: [],
      fields: [{ name: 'items', type: TySet(TyString) }],
    }]));
    expect(code).toContain('AssocSet String');
  });
});
