import TSLean.Lcnf.Target

/-!
# Printing the target AST as TypeScript

`print : Target.Program → String` is total and deterministic: the same program always prints to the
same bytes, which is what lets a compilation check `bytes = print (lower ir)`. The output uses the
runtime's `Value` type for every local and parameter, so it never mentions `any`.
-/

namespace TSLean.Lcnf.Print

open TSLean.Lcnf.Target

def hex4 (n : Nat) : String :=
  let d := Nat.toDigits 16 n
  String.ofList (List.replicate (4 - d.length) '0' ++ d)

/-- A JavaScript string literal. -/
def jsString (s : String) : String :=
  let body := s.foldl (init := "") fun acc c =>
    acc ++ match c with
    | '"' => "\\\""
    | '\\' => "\\\\"
    | '\n' => "\\n"
    | '\r' => "\\r"
    | '\t' => "\\t"
    | c =>
      if c.toNat < 0x20 || c.toNat == 0x2028 || c.toNat == 0x2029 then "\\u" ++ hex4 c.toNat
      else c.toString
  "\"" ++ body ++ "\""

def ty : Ty → String
  | .value => "rt.Value"
  | .obj => "rt.Obj"
  | .number => "number"
  | .numberOrNone => "number | undefined"
  | .values => "rt.Value[]"
  | .numbers => "number[]"

mutual
def expr : Expr → String
  | .var x => x
  | .rt n => "rt." ++ n
  | .bigint n => toString n ++ "n"
  | .num n => toString n
  | .bool b => if b then "true" else "false"
  | .str s => jsString s
  | .undef => "undefined"
  | .call f as => expr f ++ "(" ++ exprs as ++ ")"
  | .method e n as => expr e ++ "." ++ n ++ "(" ++ exprs as ++ ")"
  | .obj fs => if fs.isEmpty then "{}" else "{ " ++ fields fs ++ " }"
  | .arr es => "[" ++ exprs es ++ "]"
  | .prop e n => expr e ++ "." ++ n
  | .index e i => expr e ++ "[" ++ toString i ++ "]"
  | .strictEq a b => "(" ++ expr a ++ " === " ++ expr b ++ ")"
def exprs : List Expr → String
  | [] => ""
  | [e] => expr e
  | e :: es => expr e ++ ", " ++ exprs es
def fields : List (Ident × Expr) → String
  | [] => ""
  | [(k, e)] => k ++ ": " ++ expr e
  | (k, e) :: fs => k ++ ": " ++ expr e ++ ", " ++ fields fs
end

def indent (n : Nat) : String := String.ofList (List.replicate (2 * n) ' ')

mutual
def stmt (d : Nat) : Stmt → String
  | .const x t e => indent d ++ "const " ++ x ++ ": " ++ ty t ++ " = " ++ expr e ++ ";\n"
  | .let x t e => indent d ++ "let " ++ x ++ ": " ++ ty t ++ " = " ++ expr e ++ ";\n"
  | .assign x e => indent d ++ x ++ " = " ++ expr e ++ ";\n"
  | .expr e => indent d ++ expr e ++ ";\n"
  | .block l b => indent d ++ l ++ ": {\n" ++ stmts (d + 1) b ++ indent d ++ "}\n"
  | .loop l b => indent d ++ l ++ ": while (true) {\n" ++ stmts (d + 1) b ++ indent d ++ "}\n"
  | .break l => indent d ++ "break " ++ l ++ ";\n"
  | .continue l => indent d ++ "continue " ++ l ++ ";\n"
  | .switch e cs dflt =>
    indent d ++ "switch (" ++ expr e ++ ") {\n" ++ cases (d + 1) cs ++
    indent (d + 1) ++ "default: {\n" ++ stmts (d + 2) dflt ++ indent (d + 1) ++ "}\n" ++
    indent d ++ "}\n"
  | .ite c t e =>
    indent d ++ "if (" ++ expr c ++ ") {\n" ++ stmts (d + 1) t ++ indent d ++ "} else {\n" ++
    stmts (d + 1) e ++ indent d ++ "}\n"
  | .ret e => indent d ++ "return " ++ expr e ++ ";\n"
  | .throw e => indent d ++ "throw " ++ expr e ++ ";\n"
def stmts (d : Nat) : List Stmt → String
  | [] => ""
  | s :: ss => stmt d s ++ stmts d ss
def cases (d : Nat) : List (Nat × List Stmt) → String
  | [] => ""
  | (n, b) :: cs =>
    indent d ++ "case " ++ toString n ++ ": {\n" ++ stmts (d + 1) b ++ indent d ++ "}\n" ++ cases d cs
end

def params : List (Ident × Ty) → String
  | [] => ""
  | [(x, t)] => x ++ ": " ++ ty t
  | (x, t) :: ps => x ++ ": " ++ ty t ++ ", " ++ params ps

def fn (f : Fn) : String :=
  "export function " ++ f.name ++ "(" ++ params f.params ++ "): " ++ ty f.ret ++ " {\n" ++
    stmts 1 f.body ++ "}\n"

def program (p : Program) : String :=
  "// Generated by the TSLean LCNF lowering. Do not edit.\n" ++
  "import * as rt from " ++ jsString p.runtime ++ ";\n" ++
  String.join (p.fns.map fun f => "\n" ++ fn f)

end TSLean.Lcnf.Print
