/*
 * Generated by TSLean from a kernel-checked Lean declaration.
 * Fragment: tslean-pure-first-order-v1
 * Source module: TSLean.Examples.Placement
 * Manifest: sha256:da83c32252e7f22a04f0de1465e4fa910989a05919a960028ffa7ec18e718bac
 * Input closure: sha256:b40b480ad463da1c4c8608b2ef2d4a2fa99fd50822fd9f0cbf830c0b70d787e2
 * Semantic IR: sha256:1eed8008e7d38c37b789a16c221ff25eeb20e23d49eddd9a18d22a2c0a785cc7
 * Generated body: sha256:748344172b982c1d98064e3a40ae88ab88edfc304bae5f19d0bc684c38b9bd57
 * TypeScript: 6.0.2
 * Runtime: node:v22.21.1
 * Lean toolchain: leanprover/lean4:v4.29.0
 * Lean: Lean (version 4.29.0, x86_64-unknown-linux-gnu, commit 98dc76e3c0a9b856c9b98726b713fb04fab16740, Release)
 * Lake: Lake version 5.0.0-src+98dc76e (Lean version 4.29.0)
 * Evidence boundary: generation is checked and differential tests are empirical; no refinement theorem is claimed.
 */
export type Placement = "bundled" | "provider" | "dynamic";
export interface PlacementSet {
    readonly bundled: boolean;
    readonly provider: boolean;
    readonly dynamic: boolean;
}
function intersect(left: PlacementSet, right: PlacementSet): PlacementSet {
    return {
        bundled: left.bundled && right.bundled,
        provider: left.provider && right.provider,
        dynamic: left.dynamic && right.dynamic
    };
}
export function choosePlacement(manifest: PlacementSet, policy: PlacementSet, substrate: PlacementSet, trust: PlacementSet): Placement | undefined {
    const available = intersect(intersect(intersect(manifest, policy), substrate), trust);
    return available.dynamic ? "dynamic" : available.provider ? "provider" : available.bundled ? "bundled" : undefined;
}
