/*
 * Generated by TSLean from a kernel-checked Lean declaration.
 * Fragment: tslean-pure-first-order-v2
 * Source module: TSLean.Examples.Placement
 * Semantic identity: sha256:4804dbfe0e3fe58e947230c82df5367f31f6b55cd27060c16738e64194872bdd
 * Input closure: sha256:47b36141507ff6f91ad6db3be786d1a576c79ff1e59858441411333893167540
 * Semantic IR: sha256:dffd09745e2af51f0a6d83e49b40f73476cce67cf74684252e12fde26de1ceb9
 * Generated body: sha256:d7675ed227a395cb22717028330d35f50a9ea8ef33c33fb797aba457cc6b3f66
 * Lean toolchain: leanprover/lean4:v4.29.0
 * Lean: Lean (version 4.29.0, x86_64-unknown-linux-gnu, commit 98dc76e3c0a9b856c9b98726b713fb04fab16740, Release)
 * Lake: Lake version 5.0.0-src+98dc76e (Lean version 4.29.0)
 * Environment attestation: recorded in the manifest sidecar; it does not affect these bytes.
 * Evidence boundary: generation is checked and differential tests are empirical; no refinement theorem is claimed.
 */
export type Placement = "bundled" | "provider" | "dynamic";

export interface PlacementSet {
    readonly bundled: boolean;
    readonly provider: boolean;
    readonly dynamic: boolean;
}

function intersect(left: PlacementSet, right: PlacementSet): PlacementSet {
    return {
        bundled: left.bundled && right.bundled,
        provider: left.provider && right.provider,
        dynamic: left.dynamic && right.dynamic
    };
}

export function choosePlacement(manifest: PlacementSet, policy: PlacementSet, substrate: PlacementSet, trust: PlacementSet): Placement | undefined {
    const available = intersect(intersect(intersect(manifest, policy), substrate), trust);
    return available.dynamic ? "dynamic" : available.provider ? "provider" : available.bundled ? "bundled" : undefined;
}
