// Generate lakefile.toml and root .lean barrel module for a transpiled project.

import * as path from 'path';
import * as fs from 'fs';

export interface LakefileOpts {
  name: string;           // Lean package name
  rootNS: string;         // root namespace (same as name for most projects)
  modules: string[];      // all Lean module names, in topological order
  outDir: string;         // output directory
  leanVersion: string;    // Lean toolchain version
}

/** Generate lakefile.toml content. */
export function generateLakefile(opts: LakefileOpts): string {
  return `# Auto-generated by tslean. Edit with care.
[package]
name = "${opts.name}"
version = "0.1.0"
leanOptions = ["-DautoImplicit=false"]

[[lean_lib]]
name = "${opts.rootNS}"
roots = ["${opts.rootNS}"]

# TSLean runtime dependency (uncomment when published)
# [[require]]
# name = "TSLean"
# git = "https://github.com/AshishKumar4/ts-lean-transpiler.git"
# rev = "main"
`;
}

/** Generate lean-toolchain file content. */
export function generateToolchain(leanVersion: string): string {
  return `leanprover/lean4:${leanVersion}\n`;
}

/** Generate the root barrel module that imports all sub-modules. */
export function generateRootModule(opts: LakefileOpts): string {
  const lines = [
    `-- Auto-generated by tslean. Do not edit manually.`,
    `-- Root module for ${opts.name} (${opts.modules.length} files)`,
    '',
  ];

  for (const mod of opts.modules) {
    if (mod !== opts.rootNS) {
      lines.push(`import ${mod}`);
    }
  }

  lines.push('');
  return lines.join('\n');
}

/** Write all generated build files to the output directory. */
export function writeLakefiles(opts: LakefileOpts): void {
  const lakeDir = opts.outDir;
  fs.mkdirSync(lakeDir, { recursive: true });

  fs.writeFileSync(path.join(lakeDir, 'lakefile.toml'), generateLakefile(opts));
  fs.writeFileSync(path.join(lakeDir, 'lean-toolchain'), generateToolchain(opts.leanVersion));

  const rootFile = path.join(lakeDir, opts.rootNS + '.lean');
  fs.writeFileSync(rootFile, generateRootModule(opts));
}
