/-!
# One constructor that meets both erasures

`Stamp` is indexed by a term — `tag`, which no *surviving* field mentions — and it carries a field
that holds only a proof. Each erasure has its own rule and its own soundness argument, and this is
the one module where a single constructor meets both. `Stamp.mk` is declared at arity three (the
index, the level, the proof) and the emitted constructor takes one argument, because the emitted
arity is the declared arity less the erased leading parameters **and** less the erased proof
fields. `PhantomIndex` exercises the first subtraction and `Invariant` the second; neither
exercises them together, so a compiler that applied only one of the two would pass both of those
fixtures and fail this one.

Why the combination is admitted rather than refused: the two obligations range over disjoint sets
of fields. `Export.lean:erasedDataParameters` demands that no field which survives erasure mention
the index, and `parameterReachesData` skips a field whose role is erased. The proof field is
therefore free to mention `tag` — nothing an erased field's type mentions reaches a target
position, so it cannot make the index dependent. Erasing the proof is
`Semantics.ProofErasure.record_determined_by_data`; erasing the index is
`Semantics.Erasure.Phantom.reindex`. Neither erasure weakens the other's premise, and the join with
Lean's own lowering runs twice over this module: `ensureFieldRelevanceAgrees` on the field and
`ensureLeanErasesEveryIndex` on the index.

The three shapes that fill the erased field occur once each: a dependent `if` whose bound
hypothesis *is* the proof (`stamp`), a use site at a concrete nullary index (`runStamp`), and a
proof discharged by reduction (`highRun`).

**What this module does not claim.** The round-trip *behaviour* comparison does not read it, and the
registry entry records that with a tracking form. The observation driver builds a value by
elaborating a structure literal against the original Lean module, where the dropped proof field is
still declared and still has to be discharged, so a record whose proof field was erased has no
driver. Generated bytes, manifest bindings, the recorded erasures and the TypeScript-to-Lean
recovery are all checked here; behavioural agreement against Lean is not.
-/

namespace TSLean.Examples.Roundtrip.IndexedInvariant

/-- Which kind of thing a stamp names. Every constructor is nullary, so an index is a name. -/
inductive Tag where
  | run
  | turn
  deriving DecidableEq, Repr

/-- How much a stamp is allowed to claim. -/
inductive Level where
  | low
  | high
  deriving DecidableEq, Repr

/-- Whether the level is the demanding one. -/
def isHigh : Level → Bool
  | .low => false
  | .high => true

/-- Which tags may carry the demanding level. This is the one thing the index is read for at
runtime, and it is why `stamp` keeps its `tag` parameter after the index leaves its result type. -/
def allowsHigh : Tag → Bool
  | .run => true
  | .turn => false

/-- Whether a tag admits a level. -/
def admits (tag : Tag) (level : Level) : Bool :=
  if isHigh level then allowsHigh tag else true

/-- That a tag admits a level, stated rather than decided.

A `Prop`-sorted definition, so the exporter skips it exactly as it skips a theorem and a field of
this type carries no data. -/
def Admitted (tag : Tag) (level : Level) : Prop := admits tag level = true

/-- A stamp: the level it claims, the tag in its type, and the proof that the tag admits the level.

Both erasures meet here. `tag` is a term index no surviving field mentions — `level : Level` is
closed — so it leaves the emitted type. `admitted` is a `Prop` field, so it leaves the emitted
record. The proof field's type mentions `tag`, which is exactly the case `parameterReachesData`
skips: an erased field reaches no target position, so it cannot make the index dependent. -/
structure Stamp (tag : Tag) where
  level : Level
  /-- The tag admits the level. -/
  admitted : Admitted tag level

/-- **The merged arity, at an abstract index.** `Stamp.mk` is declared
`(tag : Tag) → (level : Level) → Admitted tag level → Stamp tag` and the emitted constructor takes
`level` alone: the index is dropped as an erased leading parameter and the proof as an erased
field. The dependent `if` binds the decision's own hypothesis and that hypothesis is what fills the
field, so both erased arguments disappear under the same decision. -/
def stamp (tag : Tag) (level : Level) : Option (Stamp tag) :=
  if admitted : admits tag level = true then some ⟨level, admitted⟩ else none

/-- Reading the field that survived erasure. One projection serves every tag. -/
def levelOf (tag : Tag) (stamp : Stamp tag) : Level := stamp.level

/-- **The merged arity, at a concrete index.** The index is a nullary constructor, so the use site
records it as an erased argument of constructor origin rather than of binder origin. -/
def runStamp (level : Level) : Option (Stamp .run) := stamp .run level

/-- A stamp whose proof is discharged by reduction rather than by a decision. The argument is
dropped whole, so the walk never descends into the proof term. -/
def highRun : Stamp .run := ⟨.high, rfl⟩

/-- The level a stamp records, with the stamp itself kept off the boundary.

A root may **return** a proof-carrying record and may reach one through the closure; it may not
**accept** one, because reading the data back does not establish the invariant the dropped field
asserts. This root takes the two enumerations and returns one, so it reads the surviving field
through a projection without asking any decoder to rebuild the proof. -/
def stampedLevel (tag : Tag) (level : Level) : Option Level :=
  match stamp tag level with
  | some stamped => some (levelOf tag stamped)
  | none => none

/-- The level the reduction-discharged stamp records. -/
def highRunLevel : Level := levelOf .run highRun

/-- **Every tag admits the undemanding level.** Both indices reach the constructor, so the emitted
single type is the right type at each. -/
theorem stampedLevel_low (tag : Tag) : stampedLevel tag .low = some .low := by
  cases tag <;> rfl

/-- **A turn stamp refuses the demanding level.** The two tags disagree, which is what makes `tag`
a runtime value rather than dead weight even though the type dropped it. -/
theorem stampedLevel_turn_high : stampedLevel .turn .high = none := rfl

/-- **The tag is not the content.** Two stamps built at different tags carry the same level, which
is the fact that makes the index erasable at runtime. -/
theorem level_independent_of_tag :
    (Stamp.mk (tag := .run) .low rfl).level = (Stamp.mk (tag := .turn) .low rfl).level := rfl

/-- **The dropped proof is not the data.** The surviving field determines what the record reports,
so erasing the proof is invisible to every program that reads one. -/
theorem highRunLevel_high : highRunLevel = .high := rfl

end TSLean.Examples.Roundtrip.IndexedInvariant
