// Code generator: IR → valid Lean 4 syntax.
// Handles: structures, inductives, functions, do-notation, match, type classes.

import {
  IRModule, IRDecl, IRExpr, IRType, IRParam, IRCase, IRPattern, DoStmt,
  IRImport, Effect, BinOp, UnOp,
  Pure, isPure, hasAsync, hasState, hasExcept,
  TyString, TyUnit,
} from '../ir/types.js';
import { irTypeToLean } from '../typemap/index.js';
import { monadString } from '../effects/index.js';
import { translateBinOp } from '../stdlib/index.js';

// ─── Public API ───────────────────────────────────────────────────────────────

export function generateLean(mod: IRModule): string {
  return new Gen().gen(mod);
}

// ─── Generator ────────────────────────────────────────────────────────────────

class Gen {
  private lines: string[] = [];
  private ind = 0;

  gen(mod: IRModule): string {
    this.emit(`-- Auto-generated by ts-lean-transpiler`);
    this.emit(`-- Source: ${mod.sourceFile ?? 'unknown'}`);
    this.emit('');
    this.emitImports(mod.imports);
    this.emit('');
    for (const d of mod.decls) { this.emitDecl(d); this.emit(''); }
    return this.lines.join('\n');
  }

  // ─── Imports ────────────────────────────────────────────────────────────────

  private emitImports(imps: IRImport[]): void {
    const seen = new Set<string>();
    for (const i of imps) {
      if (!seen.has(i.module)) { this.emit(`import ${i.module}`); seen.add(i.module); }
    }
    this.emit('');
    this.emit('open TSLean');
  }

  // ─── Declarations ───────────────────────────────────────────────────────────

  emitDecl(d: IRDecl): void {
    switch (d.tag) {
      case 'StructDef':      return this.emitStruct(d);
      case 'InductiveDef':   return this.emitInductive(d);
      case 'TypeAlias':      return this.emitTypeAlias(d);
      case 'FuncDef':        return this.emitFunc(d);
      case 'VarDecl':        return this.emitVarDecl(d);
      case 'InstanceDef':    return this.emitInstance(d);
      case 'TheoremDef':     return this.emitTheorem(d);
      case 'ClassDecl':      return this.emitClass(d);
      case 'Namespace':      return this.emitNamespace(d);
      case 'RawLean':        return this.emit(d.code);
      case 'SectionDecl':    return this.emitSection(d);
      case 'AttributeDecl':  return this.emit(`attribute [${d.attr}] ${d.target}`);
      case 'DeriveDecl':     return this.emit(`deriving instance ${d.classes.join(', ')} for ${d.typeName}`);
    }
  }

  private emitSection(d: Extract<IRDecl, { tag: 'SectionDecl' }>): void {
    if (d.name) this.emit(`section ${d.name}`);
    else this.emit('section');
    this.emit('');
    for (const x of d.decls) { this.emitDecl(x); this.emit(''); }
    if (d.name) this.emit(`end ${d.name}`);
    else this.emit('end');
  }

  private emitStruct(d: Extract<IRDecl, { tag: 'StructDef' }>): void {
    if (d.comment) this.emitComment(d.comment);
    const tp = fmtTPs(d.typeParams);
    // If extending another struct, use extends keyword
    const ext = (d as any).extends_ ? ` extends ${(d as any).extends_}` : '';
    this.emit(`structure ${d.name}${tp}${ext} where`);
    this.ind++;
    this.emit(`mk ::`);
    for (const f of d.fields) {
      const mut = f.mutable ? '' : '';  // Lean 4 doesn't distinguish mutable/immutable in structures
      this.emit(`${f.name} : ${irTypeToLean(f.type)}`);
    }
    this.ind--;
    if (d.deriving?.length) this.emit(`  deriving ${d.deriving.join(', ')}`);
  }

  private emitInductive(d: Extract<IRDecl, { tag: 'InductiveDef' }>): void {
    if (d.comment) this.emitComment(d.comment);
    const tp = fmtTPs(d.typeParams);
    this.emit(`inductive ${d.name}${tp} where`);
    for (const c of d.ctors) {
      if (c.fields.length === 0) {
        this.emit(`  | ${c.name}`);
      } else {
        const fs = c.fields.map(f => f.name ? `(${f.name} : ${irTypeToLean(f.type)})` : `(${irTypeToLean(f.type)})`).join(' ');
        this.emit(`  | ${c.name} ${fs}`);
      }
    }
    this.emit(`  deriving Repr, BEq`);
  }

  private emitTypeAlias(d: Extract<IRDecl, { tag: 'TypeAlias' }>): void {
    if (d.comment) this.emitComment(d.comment);
    this.emit(`abbrev ${d.name}${fmtTPs(d.typeParams)} := ${irTypeToLean(d.body)}`);
  }

  private emitFunc(d: Extract<IRDecl, { tag: 'FuncDef' }>): void {
    // JSDoc / leading comment
    if (d.docComment) {
      this.emit(`/-- ${d.docComment.trim()} -/`);
    } else if (d.comment) {
      this.emitComment(d.comment);
    }
    const name    = sanitize(d.name);
    const tp      = d.typeParams.length > 0 ? ` {${d.typeParams.map(t => `${t} : Type`).join('} {')}}` : '';
    const params  = d.params.map(p => this.fmtParam(p, d.effect)).join(' ');
    const retLean = irTypeToLean(d.retType);
    const retSig  = this.retSig(d.effect, retLean);
    const ps = params ? ` ${params}` : '';
    // Detect self-recursive functions for `partial def` (avoids termination checker rejection)
    const isRecursive = d.isPartial ?? bodyContainsVarRef(d.body, d.name);
    const kw = isRecursive ? 'partial def' : 'def';
    this.emit(`${kw} ${name}${tp}${ps} : ${retSig} :=`);
    this.ind++;
    this.emit(this.genExpr(d.body, d.effect));
    this.ind--;
    // Emit where clauses (local helper definitions)
    if (d.where_ && d.where_.length > 0) {
      this.emit('where');
      this.ind++;
      for (const w of d.where_) { this.emitDecl(w); }
      this.ind--;
    }
  }

  private retSig(eff: Effect, retLean: string): string {
    const w = (s: string) => s.includes(' ') && !s.startsWith('(') ? `(${s})` : s;
    switch (eff.tag) {
      case 'Pure':   return retLean;
      case 'IO':     return `IO ${w(retLean)}`;
      case 'Async':  return `IO ${w(retLean)}`;
      case 'State':  return `StateT ${w(irTypeToLean(eff.stateType))} IO ${w(retLean)}`;
      case 'Except': return `ExceptT ${w(irTypeToLean(eff.errorType))} IO ${w(retLean)}`;
      case 'Combined': return `${monadString(eff)} ${w(retLean)}`;
    }
  }

  private fmtParam(p: IRParam, eff: Effect): string {
    const ty = irTypeToLean(p.type);
    if (p.implicit) return `{${p.name} : ${ty}}`;
    if (p.default_) return `(${p.name} : ${ty} := ${this.genExpr(p.default_, eff)})`;
    return `(${p.name} : ${ty})`;
  }

  private emitVarDecl(d: Extract<IRDecl, { tag: 'VarDecl' }>): void {
    const ty  = irTypeToLean(d.type);
    const val = this.genExpr(d.value, Pure);
    if (d.mutable) {
      // Mutable vars use IO.Ref; emit as an IO action creating a ref
      this.emit(`-- mutable binding '${d.name}' modelled as IO.Ref`);
      this.emit(`def ${sanitize(d.name)}_ref : IO (IO.Ref ${ty}) := IO.mkRef ${val}`);
    } else {
      this.emit(`def ${sanitize(d.name)} : ${ty} := ${val}`);
    }
  }

  private emitInstance(d: Extract<IRDecl, { tag: 'InstanceDef' }>): void {
    if (d.comment) this.emitComment(d.comment);
    const tArgs = d.typeArgs.map(t => irTypeToLean(t)).join(' ');
    this.emit(`instance : ${d.typeClass} ${tArgs} where`);
    this.ind++;
    for (const m of d.methods) {
      if (m.tag === 'FuncDef') {
        const ps = m.params.map(p => this.fmtParam(p, m.effect)).join(' ');
        const psStr = ps ? ` ${ps}` : '';
        this.emit(`${m.name}${psStr} := ${this.genExpr(m.body, m.effect)}`);
      }
    }
    this.ind--;
  }

  private emitTheorem(d: Extract<IRDecl, { tag: 'TheoremDef' }>): void {
    if (d.comment) this.emitComment(d.comment);
    this.emit(`theorem ${d.name} : ${d.statement} := by`);
    this.ind++;
    this.emit(d.proof);
    this.ind--;
  }

  private emitClass(d: Extract<IRDecl, { tag: 'ClassDecl' }>): void {
    if (d.comment) this.emitComment(d.comment);
    this.emit(`class ${d.name}${fmtTPs(d.typeParams)} where`);
    this.ind++;
    for (const m of d.methods) this.emit(`${m.name} : ${irTypeToLean(m.type)}`);
    this.ind--;
  }

  private emitNamespace(d: Extract<IRDecl, { tag: 'Namespace' }>): void {
    this.emit(`namespace ${d.name}`);
    this.emit('');
    // Detect mutual recursion groups
    const groups = groupMutual(d.decls);
    for (const group of groups) {
      if (group.length === 1) {
        this.emitDecl(group[0]);
        this.emit('');
      } else {
        this.emit('mutual');
        this.emit('');
        for (const x of group) { this.emitDecl(x); this.emit(''); }
        this.emit('end');
        this.emit('');
      }
    }
    this.emit(`end ${d.name}`);
  }

  // ─── Expression generation ──────────────────────────────────────────────────

  genExpr(e: IRExpr, ctx: Effect, depth = 0): string {
    const indent = '  '.repeat(this.ind + depth);
    switch (e.tag) {
      case 'LitNat':    return String(e.value);
      case 'LitInt':    return String(e.value);
      case 'LitFloat':  return Number.isInteger(e.value) ? `(${e.value} : Float)` : String(e.value);
      case 'LitString': return JSON.stringify(e.value);
      case 'LitBool':   return e.value ? 'true' : 'false';
      case 'LitUnit':   return '()';
      case 'LitNull':   return 'none';
      case 'Hole':      return 'sorry';
      case 'Var':       return sanitize(e.name);

      case 'FieldAccess': return `${this.genExpr(e.obj, ctx, depth)}.${e.field}`;

      case 'IndexAccess': return `${this.genExpr(e.obj, ctx, depth)}[${this.genExpr(e.index, ctx, depth)}]!`;

      case 'Lambda': {
        const ps = e.params.map(p => p.name).join(' ');
        return `fun ${ps || '_'} => ${this.genExpr(e.body, e.effect ?? ctx, depth)}`;
      }

      case 'App': {
        const fn   = this.genExpr(e.fn, ctx, depth);
        const args = e.args.map(a => this.genP(a, ctx, depth));
        return args.length === 0 ? fn : `${fn} ${args.join(' ')}`;
      }

      case 'TypeApp': {
        const fn   = this.genExpr(e.fn, ctx, depth);
        const tArgs = e.typeArgs.map(t => `(${irTypeToLean(t)})`).join(' ');
        return `${fn} ${tArgs}`;
      }

      case 'Let': {
        const v    = this.genExpr(e.value, ctx, depth);
        const body = this.genExpr(e.body, ctx, depth);
        const ann  = e.annot ? ` : ${irTypeToLean(e.annot)}` : '';
        return `let ${e.name}${ann} := ${v}\n${indent}${body}`;
      }

      case 'Bind': {
        const m    = this.genExpr(e.monad, ctx, depth);
        const body = this.genExpr(e.body, ctx, depth);
        return `let ${e.name} ← ${m}\n${indent}${body}`;
      }

      case 'IfThenElse': {
        const cond  = this.genExpr(e.cond, ctx, depth);
        const inner = '  '.repeat(this.ind + depth + 1);
        const then_ = this.genExpr(e.then, ctx, depth + 1);
        const else_ = this.genExpr(e.else_, ctx, depth + 1);
        return `if ${cond} then\n${inner}${then_}\n${indent}else\n${inner}${else_}`;
      }

      case 'Match': return this.genMatch(e, ctx, depth);

      case 'Sequence': {
        if (e.stmts.length === 0) return '()';
        if (e.stmts.length === 1) return this.genExpr(e.stmts[0], ctx, depth);
        const needsDo = hasAsync(ctx) || hasState(ctx) || hasExcept(ctx);
        if (needsDo) return this.genDoSeq(e.stmts, ctx, depth);
        return e.stmts.map(s => this.genExpr(s, ctx, depth)).join(`\n${indent}`);
      }

      case 'DoBlock': return this.genDoBlock(e.stmts, ctx, depth);

      case 'StructLit': {
        // Detect struct-update pattern: one `_base` field + other fields → `{ base with f := v }`
        const baseField = e.fields.find(f => f.name === '_base');
        const realFields = e.fields.filter(f => f.name !== '_base' && f.name !== '_spread');
        if (baseField && realFields.length > 0) {
          const base = this.genExpr(baseField.value, ctx, depth);
          const updates = realFields.map(f => `${f.name} := ${this.genExpr(f.value, ctx, depth)}`).join(', ');
          return `{ ${base} with ${updates} }`;
        }
        const fields = e.fields.filter(f => f.name !== '_spread')
          .map(f => `${f.name} := ${this.genExpr(f.value, ctx, depth)}`).join(', ');
        return `{ ${fields} }`;
      }

      case 'CtorApp': {
        const args = e.args.map(a => this.genP(a, ctx, depth));
        return args.length === 0 ? sanitize(e.ctor) : `${sanitize(e.ctor)} ${args.join(' ')}`;
      }

      case 'ArrayLit': return `#[${e.elems.map(x => this.genExpr(x, ctx, depth)).join(', ')}]`;

      case 'TupleLit': return `(${e.elems.map(x => this.genExpr(x, ctx, depth)).join(', ')})`;

      case 'Pure_': return `pure ${this.genP(e.value, ctx, depth)}`;

      case 'StateGet': return 'get';
      case 'StateSet': return `set ${this.genP(e.value, ctx, depth)}`;

      case 'Throw':    return `throw ${this.genP(e.error, ctx, depth)}`;

      case 'TryCatch': {
        const body    = this.genP(e.body, ctx, depth);
        const handler = this.genExpr(e.handler, ctx, depth);
        return `tryCatch ${body} (fun ${e.errName} => ${handler})`;
      }

      case 'Await': return this.genExpr(e.expr, ctx, depth);

      case 'Assign': {
        const val = this.genExpr(e.value, ctx, depth);
        if (e.target.tag === 'FieldAccess' && e.target.obj.tag === 'Var' && e.target.obj.name === 'self')
          return `modify (fun s => { s with ${e.target.field} := ${val} })`;
        if (e.target.tag === 'Var')
          return `let ${e.target.name} := ${val}`;
        return `-- assign: ${this.genExpr(e.target, ctx, depth)} := ${val}`;
      }

      case 'BinOp': return this.genBinOp(e, ctx, depth);
      case 'UnOp':  {
        const op = e.op === 'Not' ? '!' : e.op === 'Neg' ? '-' : '~~~';
        return `${op}${this.genP(e.operand, ctx, depth)}`;
      }

      case 'Cast':   return this.genExpr(e.expr, ctx, depth);
      case 'IsType': {
        // instanceof / type guard — approximated with a decidable check.
        // In Lean 4 there is no runtime type inspection for opaque types, so we emit a sorry
        // that signals a proof obligation: the caller must supply the type proof.
        const typeName = e.testType.tag === 'TypeRef' ? e.testType.name
                       : e.testType.tag === 'Structure' ? e.testType.name
                       : irTypeToLean(e.testType);
        const expr = this.genExpr(e.expr, ctx, depth);
        // Emit as a decision procedure stub
        return `(${expr} matches ${typeName} := sorry)`;
      }

      case 'Return': {
        const val = this.genExpr(e.value, ctx, depth);
        return !isPure(ctx) ? `return ${val}` : val;
      }

      case 'Panic': return `panic! ${JSON.stringify(e.msg)}`;

      // New in v3:
      case 'StructUpdate': {
        const base    = this.genExpr(e.base, ctx, depth);
        const updates = e.fields.map(f => `${f.name} := ${this.genExpr(f.value, ctx, depth)}`).join(', ');
        return `{ ${base} with ${updates} }`;
      }

      case 'TypeNarrow': {
        // Type narrowing becomes a cast or match — emit the inner expression
        return this.genExpr(e.expr, ctx, depth);
      }

      case 'YieldExpr': {
        const val = e.value ? this.genExpr(e.value, ctx, depth) : '()';
        return `yield ${val}`;
      }

      case 'OptChain': {
        return this.genExpr(e.expr, ctx, depth);
      }

      case 'MultiLet': {
        const ind = '  '.repeat(this.ind + depth);
        let result = this.genExpr(e.body, ctx, depth);
        for (const b of [...e.bindings].reverse()) {
          const val = this.genExpr(b.value, ctx, depth);
          const ann = ` : ${irTypeToLean(b.type)}`;
          result = `let ${b.name}${ann} := ${val}\n${ind}${result}`;
        }
        return result;
      }

      case 'Labeled': return this.genExpr(e.body, ctx, depth);
      case 'Break':   return '-- break';
      case 'Continue':return '-- continue';

      default: return 'sorry';
    }
  }

  private genP(e: IRExpr, ctx: Effect, depth: number): string {
    const s = this.genExpr(e, ctx, depth);
    return needsParens(e) ? `(${s})` : s;
  }

  private genMatch(e: Extract<IRExpr, { tag: 'Match' }>, ctx: Effect, depth: number): string {
    const scrutinee = this.genExpr(e.scrutinee, ctx, depth);
    const inner     = '  '.repeat(this.ind + depth + 1);
    const cases     = e.cases.map(c => {
      const pat   = this.genPat(c.pattern);
      const guard = c.guard ? ` if ${this.genExpr(c.guard, ctx, depth)}` : '';
      const body  = this.genExpr(c.body, ctx, depth + 1);
      return `${inner}| ${pat}${guard} => ${body}`;
    });
    return `match ${scrutinee} with\n${cases.join('\n')}`;
  }

  private genPat(p: IRPattern): string {
    switch (p.tag) {
      case 'PVar':    return sanitize(p.name);
      case 'PWild':   return '_';
      case 'PLit':    return typeof p.value === 'string' ? JSON.stringify(p.value) : String(p.value);
      case 'PString': return JSON.stringify(p.value);
      case 'PNone':   return '.none';
      case 'PSome':   return `.some ${this.genPat(p.inner)}`;
      case 'PCtor': {
        const localName = p.ctor.includes('.') ? p.ctor.split('.').pop()! : p.ctor;
        const args = p.args.map(a => this.genPat(a));
        return args.length === 0 ? `.${localName}` : `.${localName} ${args.join(' ')}`;
      }
      case 'PTuple':  return `(${p.elems.map(x => this.genPat(x)).join(', ')})`;
      case 'PStruct': return `{ ${p.fields.map(f => `${f.name} := ${this.genPat(f.pattern)}`).join(', ')} }`;
      case 'POr':     return p.pats.map(x => this.genPat(x)).join(' | ');
      case 'PAs':     return `${this.genPat(p.pattern)} as ${p.name}`;
      default:        return '_';
    }
  }

  private genDoBlock(stmts: DoStmt[], ctx: Effect, depth: number): string {
    const ind = '  '.repeat(this.ind + depth + 1);
    const lines = ['do'];
    for (const s of stmts) {
      switch (s.tag) {
        case 'DoBind':   lines.push(`${ind}let ${s.name} ← ${this.genExpr(s.expr, ctx, depth + 1)}`); break;
        case 'DoLet':    lines.push(`${ind}let ${s.name} := ${this.genExpr(s.value, ctx, depth + 1)}`); break;
        case 'DoExpr':   lines.push(`${ind}${this.genExpr(s.expr, ctx, depth + 1)}`); break;
        case 'DoReturn': lines.push(`${ind}return ${this.genExpr(s.value, ctx, depth + 1)}`); break;
      }
    }
    return lines.join('\n');
  }

  private genDoSeq(stmts: IRExpr[], ctx: Effect, depth: number): string {
    const ind = '  '.repeat(this.ind + depth + 1);
    const lines = ['do'];
    for (const s of stmts) {
      if (s.tag === 'Bind') {
        lines.push(`${ind}let ${s.name} ← ${this.genExpr(s.monad, ctx, depth + 1)}`);
      } else if (s.tag === 'Let') {
        lines.push(`${ind}let ${s.name} := ${this.genExpr(s.value, ctx, depth + 1)}`);
      } else if (s.tag === 'Return') {
        lines.push(`${ind}return ${this.genExpr(s.value, ctx, depth + 1)}`);
      } else {
        lines.push(`${ind}${this.genExpr(s, ctx, depth + 1)}`);
      }
    }
    return lines.join('\n');
  }

  private genBinOp(e: Extract<IRExpr, { tag: 'BinOp' }>, ctx: Effect, depth: number): string {
    if (e.op === 'NullCoalesce') {
      const l = this.genP(e.left, ctx, depth);
      const r = this.genP(e.right, ctx, depth);
      return `Option.getD ${l} ${r}`;
    }
    // Try to emit s!"..." interpolation for Concat chains (template literals)
    if (e.op === 'Concat' || (e.op === 'Add' && e.left.type.tag === 'String')) {
      const interp = this.trySInterp(e, ctx, depth);
      if (interp) return interp;
    }
    const l = this.genP(e.left, ctx, depth);
    const r = this.genP(e.right, ctx, depth);
    const op = translateBinOp(e.op, e.left.type);
    return `${l} ${op} ${r}`;
  }

  // Try to fold a Concat/Add-string chain into Lean 4 s!"..." interpolation.
  // Returns null if the chain is not a simple template (e.g. contains function calls).
  private trySInterp(e: IRExpr, ctx: Effect, depth: number): string | null {
    const parts = flattenConcat(e);
    if (!parts) return null;
    // Require both: at least one interpolated expression AND at least one non-empty string literal.
    // This ensures s! only fires for real template literals ("`Hello, ${name}!`"),
    // not bare string concatenations (`a ++ b`) which are more readable as `++`.
    const hasInterp  = parts.some(p => p.tag !== 'LitString');
    const hasLiteral = parts.some(p => p.tag === 'LitString' && (p as any).value !== '');
    if (!hasInterp || !hasLiteral) return null;
    // Only safe for simple expressions (vars, field accesses, literals)
    if (!parts.every(isSafeInterp)) return null;
    const inner = parts.map(p => {
      if (p.tag === 'LitString') return (p as any).value.replace(/\{/g, '\\{');
      return `{${this.genExpr(p, ctx, depth)}}`;
    }).join('');
    return `s!"${inner}"`;
  }

  // Auto-generate common instances for a struct
  emitAutoInstances(name: string, typeParams: string[], fields: Array<{ name: string; type: IRType }>): void {
    if (typeParams.length > 0) return; // Skip generic types — instances need type-class constraints
    // BEq instance using field-by-field comparison
    const beqFields = fields.map(f => `a.${f.name} == b.${f.name}`).join(' && ');
    const beqExpr = beqFields || 'true';
    this.emit(`instance : BEq ${name} where`);
    this.ind++;
    this.emit(`beq a b := ${beqExpr}`);
    this.ind--;
    this.emit('');
    // DecidableEq using the BEq instance
    this.emit(`instance : DecidableEq ${name} := fun a b =>`);
    this.ind++;
    this.emit(`if a == b then isTrue (by simp [BEq.beq]) else isFalse (by simp [BEq.beq])`);
    this.ind--;
  }

  // Emit a where-clause block for local helper defs
  private emitWhereBlock(decls: IRDecl[]): void {
    if (decls.length === 0) return;
    this.emit('where');
    this.ind++;
    for (const d of decls) this.emitDecl(d);
    this.ind--;
  }

  private emitComment(c: string): void {
    for (const line of c.split('\n')) {
      const stripped = line.replace(/^\/\*+\s*/, '').replace(/\*+\/$/, '').replace(/^\s*\*\s?/, '').trim();
      if (!stripped) continue;  // Skip blank lines from JSDoc formatting
      if (stripped.startsWith('@')) continue;  // Skip JSDoc tags (@param, @returns, etc.)
      this.emit(`-- ${stripped}`);
    }
  }

  private emit(line: string): void {
    this.lines.push('  '.repeat(this.ind) + line);
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

const LEAN_KWS = new Set([
  'def','fun','let','in','if','then','else','match','with','do','return','where',
  'have','show','from','by','class','instance','structure','inductive','namespace',
  'end','open','import','theorem','lemma','example','variable','universe','abbrev',
  'opaque','partial','mutual','private','protected','section','attribute','and','or',
  'not','true','false','Type','Prop',
]);

function sanitize(name: string): string {
  if (LEAN_KWS.has(name)) return `«${name}»`;
  // Lean 4 allows ? at the end of identifiers (for Option-returning functions like Array.get?)
  // Also allow ! for panic functions. Replace other special chars with _.
  return name.replace(/[^a-zA-Z0-9_.!?']/g, '_');
}

function fmtTPs(params: string[]): string {
  return params.length === 0 ? '' : ` {${params.map(p => `${p} : Type`).join('} {')}}`;
}

function needsParens(e: IRExpr): boolean {
  return e.tag === 'App' || e.tag === 'BinOp' || e.tag === 'UnOp' ||
         e.tag === 'IfThenElse' || e.tag === 'Lambda' || e.tag === 'Let' ||
         e.tag === 'Bind' || e.tag === 'TryCatch' || e.tag === 'Match' ||
         e.tag === 'LitFloat';
}

// ─── Partial def detection ────────────────────────────────────────────────────

function bodyContainsVarRef(expr: IRExpr, name: string): boolean {
  function check(e: IRExpr): boolean {
    if (e.tag === 'Var' && e.name === name) return true;
    switch (e.tag) {
      case 'App':        return check(e.fn) || e.args.some(check);
      case 'Lambda':     return check(e.body);
      case 'Let':        return check(e.value) || check(e.body);
      case 'Bind':       return check(e.monad) || check(e.body);
      case 'IfThenElse': return check(e.cond)  || check(e.then) || check(e.else_);
      case 'Match':      return check(e.scrutinee) || e.cases.some(c => check(c.body));
      case 'Sequence':   return e.stmts.some(check);
      case 'BinOp':      return check(e.left) || check(e.right);
      case 'UnOp':       return check(e.operand);
      case 'FieldAccess':return check(e.obj);
      case 'IndexAccess':return check(e.obj) || check(e.index);
      case 'Assign':     return check(e.target) || check(e.value);
      case 'TryCatch':   return check(e.body) || check(e.handler);
      case 'Throw':      return check(e.error);
      case 'Return':     return check(e.value);
      case 'Await':      return check(e.expr);
      case 'Cast':       return check(e.expr);
      case 'CtorApp':    return e.args.some(check);
      case 'ArrayLit':   return e.elems.some(check);
      case 'TupleLit':   return e.elems.some(check);
      case 'StructLit':  return e.fields.some(f => check(f.value));
      case 'DoBlock':    return e.stmts.some(s => {
        switch (s.tag) {
          case 'DoBind':   return check(s.expr);
          case 'DoLet':    return check(s.value);
          case 'DoExpr':   return check(s.expr);
          case 'DoReturn': return check(s.value);
        }
      });
      default: return false;
    }
  }
  return check(expr);
}

// ─── Mutual recursion detection ───────────────────────────────────────────────

function groupMutual(decls: IRDecl[]): IRDecl[][] {
  // Build adjacency: which FuncDefs reference which others
  const funcNames = new Set<string>(
    decls.filter(d => d.tag === 'FuncDef').map(d => (d as any).name as string)
  );
  const groups: IRDecl[][] = [];
  const visited = new Set<number>();

  for (let i = 0; i < decls.length; i++) {
    if (visited.has(i)) continue;
    const d = decls[i];
    if (d.tag !== 'FuncDef') { groups.push([d]); visited.add(i); continue; }

    // Find all FuncDefs this one mutually references (within the same namespace)
    const mutualGroup = [d];
    visited.add(i);
    for (let j = i + 1; j < decls.length; j++) {
      if (visited.has(j)) continue;
      const d2 = decls[j];
      if (d2.tag !== 'FuncDef') continue;
      // Mutual if d references d2.name AND d2 references d.name
      if (bodyContainsVarRef((d as any).body, (d2 as any).name) &&
          bodyContainsVarRef((d2 as any).body, (d as any).name)) {
        mutualGroup.push(d2);
        visited.add(j);
      }
    }
    groups.push(mutualGroup);
  }
  return groups;
}

// ─── s!"..." interpolation helpers ───────────────────────────────────────────

function flattenConcat(e: IRExpr): IRExpr[] | null {
  if (e.tag === 'LitString') return [e];
  // Non-string-concat binary: stop
  if (e.tag === 'BinOp' && (e.op === 'Concat' || (e.op === 'Add' && e.left.type.tag === 'String'))) {
    const left  = flattenConcat(e.left);
    const right = flattenConcat(e.right);
    if (!left || !right) return null;
    return [...left, ...right];
  }
  // Safe interpolation leaf nodes: Var, FieldAccess, LitNat, LitBool, Cast
  if (isSafeInterp(e)) return [e];
  return null;
}

function isSafeInterp(e: IRExpr): boolean {
  switch (e.tag) {
    case 'LitString':
    case 'LitNat':
    case 'LitFloat':
    case 'LitBool':
    case 'Var':
      return true;
    case 'FieldAccess':
      return isSafeInterp(e.obj);
    case 'Cast':
      return isSafeInterp(e.expr);
    default:
      return false;
  }
}
