/**
 * @module codegen/lower
 *
 * Lowering pass: IR → LeanAST.
 *
 * Translates the transpiler's IR (typed, effect-annotated) into a Lean 4
 * surface syntax AST that the printer can emit directly. All semantic
 * decisions happen here:
 *   - do vs pure (based on Effect annotations, not string matching)
 *   - partial vs total (based on recursive self-reference detection)
 *   - sorry for unrepresentable constructs (TS API boundary, etc.)
 *   - sanitization of identifiers (Lean keywords)
 *   - import resolution (scanning the AST for needed modules)
 *   - mutual block detection (transitive cross-references between types)
 *
 * Pipeline:  IR → Rewrite → **Lowering** → Printer → Text
 */

import type {
  IRModule, IRDecl, IRExpr, IRType, IRParam, IRCase, IRPattern,
  DoStmt, Effect, BinOp, UnOp, IRImport,
} from '../ir/types.js';
import { Pure, isPure } from '../ir/types.js';
import type {
  LeanFile, LeanDecl, LeanExpr, LeanTy, LeanPat,
  LeanTyParam, LeanParam, LeanField, LeanCtor,
  LeanMatchArm, LeanFieldVal, SInterpPart,
} from './lean-ast.js';
import { irTypeToLean } from '../typemap/index.js';

import { translateBinOp } from '../stdlib/index.js';
import { printTyStr, printExprStr } from './printer.js';
import { currentTracker } from '../sorry-tracker.js';

// TS utility types that require type-level computation (keyof, infer, conditional)
// and cannot be expressed in Lean 4 when their arguments contain type variables.
const INEXPRESSIBLE_UTILITY_TYPES = new Set([
  'Partial', 'Required', 'Pick', 'Omit',
  'ReturnType', 'Parameters', 'ConstructorParameters', 'InstanceType',
  'Extract', 'Exclude', 'ThisParameterType', 'OmitThisParameter', 'ThisType',
  'Awaited',
]);

// ─── Public API ─────────────────────────────────────────────────────────────────

/** Lower an IR module to a LeanAST file. */
export function lowerModule(mod: IRModule): LeanFile {
  const ctx = new LowerCtx();
  ctx.collectStructInfo(mod.decls);
  ctx.collectDefinedNames(mod.decls);

  const decls: LeanDecl[] = [];

  // Imports
  const imports = ctx.resolveImports(mod);
  for (const imp of imports) {
    decls.push({ tag: 'Import', module: imp });
  }
  decls.push({ tag: 'Blank' });

  // Open namespaces
  const opens = ctx.resolveOpens(mod, imports);
  decls.push({ tag: 'Open', namespaces: opens });
  decls.push({ tag: 'Blank' });

  // Namespace
  const ns = mod.name;
  const useNs = ns && ns !== 'T' && ns !== 'Test';
  if (useNs) {
    // Missing state structs
    const missingStructs = ctx.emitMissingStateStructs(mod.decls);
    // Main declarations with mutual detection
    const bodyDecls = [...missingStructs, ...ctx.lowerDeclsWithMutual(mod.decls)];
    decls.push({ tag: 'Namespace', name: ns, decls: bodyDecls });
  } else {
    const missingStructs = ctx.emitMissingStateStructs(mod.decls);
    for (const d of missingStructs) decls.push(d);
    for (const d of ctx.lowerDeclsWithMutual(mod.decls)) decls.push(d);
  }

  return {
    banner: 'Auto-generated by ts-lean-transpiler',
    sourcePath: mod.sourceFile ?? 'unknown',
    decls,
  };
}

// ─── TS API boundary ────────────────────────────────────────────────────────────

const TS_API_TYPES = new Set([
  'Any', 'TSAny', 'Node', 'TypeChecker', 'Type', 'Symbol', 'Signature',
  'SyntaxKind', 'Token', 'Expression', 'Statement', 'Declaration',
  'FunctionDeclaration', 'FunctionExpression', 'ArrowFunction',
  'MethodDeclaration', 'ClassDeclaration', 'InterfaceDeclaration',
  'VariableDeclaration', 'VariableDeclarationList', 'VariableStatement',
  'PropertyDeclaration', 'PropertySignature', 'PropertyAccessExpression',
  'BinaryExpression', 'CallExpression', 'ElementAccessExpression',
  'PrefixUnaryExpression', 'PostfixUnaryExpression',
  'NewExpression', 'ObjectLiteralExpression', 'ArrayLiteralExpression',
  'IfStatement', 'Block', 'SourceFile', 'Program', 'Diagnostic',
  'CompilerHost', 'CompilerOptions', 'ModuleDeclaration',
  'ExportDeclaration', 'ExportAssignment', 'ImportDeclaration',
  'TypeAliasDeclaration', 'EnumDeclaration', 'EnumMember',
  'UnionType', 'IntersectionType', 'ObjectType', 'TypeReference',
  'ConditionalExpression', 'SwitchStatement', 'CaseClause',
  'ReturnStatement', 'ThrowStatement', 'TryStatement',
  'ForStatement', 'ForOfStatement', 'ForInStatement', 'WhileStatement',
  'TemplateExpression', 'TaggedTemplateExpression',
  'NodeArray', 'ConciseBody', 'LeftHandSideExpression',
  'BinaryOperator', 'PrefixUnaryOperator', 'PostfixUnaryOperator',
  'ConstructorDeclaration', 'GetAccessorDeclaration', 'SetAccessorDeclaration',
  'ArrayBindingPattern', 'ObjectBindingPattern', 'ts',
]);

const DEFAULT_DERIVING = ['Repr', 'BEq', 'Inhabited'];

/** Check if a Lean type contains arrow types (functions). Lean cannot derive Repr/BEq for these. */
function containsArrowType(ty: LeanTy): boolean {
  switch (ty.tag) {
    case 'TyArrow': return true;
    case 'TyApp': return ty.args.some(containsArrowType);
    case 'TyTuple': return ty.elems.some(containsArrowType);
    case 'TyParen': return containsArrowType(ty.inner);
    default: return false;
  }
}

/** Compute safe deriving clauses — exclude Repr/BEq if any field has arrow type. */
function safeDeriving(fields: LeanField[], isBranded: boolean): string[] {
  if (fields.some(f => containsArrowType(f.ty))) return ['Inhabited'];
  return isBranded ? [...DEFAULT_DERIVING, 'DecidableEq'] : DEFAULT_DERIVING;
}

// ─── Lowering context ───────────────────────────────────────────────────────────

class LowerCtx {
  /** Registry of struct fields by struct name — used for inheritance. */
  structFields = new Map<string, Array<{ name: string; type: IRType }>>();
  /** Map from class name → state struct name. */
  classToState = new Map<string, string>();
  /** Names defined in this module. */
  definedNames = new Set<string>();

  // ─── Pre-passes ─────────────────────────────────────────────────────────────

  collectDefinedNames(decls: IRDecl[]): void {
    for (const d of decls) {
      if ('name' in d && typeof d.name === 'string') this.definedNames.add(d.name);
      if (d.tag === 'Namespace') this.collectDefinedNames(d.decls);
    }
  }

  collectStructInfo(decls: IRDecl[]): void {
    for (const d of decls) {
      if (d.tag === 'StructDef') {
        this.structFields.set(d.name, d.fields.map(f => ({ name: f.name, type: f.type })));
        if (d.name.endsWith('State')) {
          this.classToState.set(d.name.slice(0, -5), d.name);
        }
      }
      if (d.tag === 'Namespace') this.collectStructInfo(d.decls);
    }
    // Second pass: find field accesses on `self` in method bodies
    for (const d of decls) {
      if (d.tag === 'FuncDef' && d.params.some(p => p.name === 'self')) {
        const selfType = d.params.find(p => p.name === 'self')?.type;
        if (selfType?.tag === 'TypeRef') {
          this.enrichFieldsFromBody(selfType.name, d.body);
        }
      }
      if (d.tag === 'Namespace') {
        for (const inner of d.decls) {
          if (inner.tag === 'FuncDef' && inner.params.some(p => p.name === 'self')) {
            const selfType = inner.params.find(p => p.name === 'self')?.type;
            if (selfType?.tag === 'TypeRef') {
              this.enrichFieldsFromBody(selfType.name, inner.body);
            }
          }
        }
      }
    }
  }

  private enrichFieldsFromBody(structName: string, body: IRExpr): void {
    const fields = this.structFields.get(structName);
    if (!fields) return;
    const accessed = collectFieldAccesses(body, 'self');
    for (const [fname, ftype] of accessed) {
      const isExcluded = fname.startsWith('_') || fname === 'state' || fname === 'storage' ||
        fname === 'env' || fname === 'config' ||
        (ftype.tag === 'TypeRef' && ['DurableObjectState', 'Env', 'CompilerHost'].includes(ftype.name));
      if (!fields.some(f => f.name === fname) && !isExcluded) {
        fields.push({ name: fname, type: ftype });
      }
    }
  }

  // ─── Import resolution ──────────────────────────────────────────────────────

  resolveImports(mod: IRModule): string[] {
    const needed = new Set<string>();
    needed.add('TSLean.Runtime.Basic');
    needed.add('TSLean.Runtime.Coercions');
    for (const d of mod.decls) this.scanImportNeeds(d, needed);
    const isSelfHost = mod.sourceFile?.includes('/src/') ?? false;
    for (const imp of mod.imports) {
      if (imp.module.startsWith('TSLean.External.')) continue;
      if (isSelfHost && imp.module.startsWith('TSLean.Generated.')) continue;
      if (imp.module.startsWith('TSLean.')) needed.add(imp.module);
    }
    return [...needed].sort();
  }

  resolveOpens(_mod: IRModule, imports: string[]): string[] {
    const opens = ['TSLean'];
    if (imports.some(i => i.includes('WebAPI'))) opens.push('TSLean.WebAPI');
    if (imports.some(i => i.includes('HashMap'))) opens.push('TSLean.Stdlib.HashMap');
    if (imports.some(i => i.includes('DurableObjects'))) opens.push('TSLean.DO');
    return opens;
  }

  private scanImportNeeds(d: IRDecl, needs: Set<string>): void {
    if (d.tag === 'FuncDef') {
      if (!isPure(d.effect)) needs.add('TSLean.Runtime.Monad');
      for (const p of d.params) this.scanTypeImports(p.type, needs);
      this.scanTypeImports(d.retType, needs);
      this.scanExprImports(d.body, needs);
    }
    if (d.tag === 'StructDef') {
      for (const f of d.fields) this.scanTypeImports(f.type, needs);
    }
    if (d.tag === 'Namespace') {
      for (const inner of d.decls) this.scanImportNeeds(inner, needs);
    }
    if (d.tag === 'VarDecl') {
      this.scanTypeImports(d.type, needs);
      this.scanExprImports(d.value, needs);
    }
  }

  private scanTypeImports(t: IRType, needs: Set<string>): void {
    switch (t.tag) {
      case 'Map': case 'Set': needs.add('TSLean.Stdlib.HashMap'); break;
      case 'TypeRef':
        if (['Request', 'Response', 'URL', 'Headers', 'WebSocket'].includes(t.name))
          needs.add('TSLean.Runtime.WebAPI');
        if (['DurableObjectState', 'DurableObjectId', 'DurableObjectNamespace', 'DurableObjectStub'].includes(t.name))
          needs.add('TSLean.DurableObjects.State');
        if (t.name === 'KVNamespace') needs.add('TSLean.Workers.KV');
        if (t.name === 'R2Bucket' || t.name === 'R2Object') needs.add('TSLean.Workers.R2');
        if (t.name === 'D1Database' || t.name === 'D1PreparedStatement') needs.add('TSLean.Workers.D1');
        if (t.name === 'QueueSender' || t.name === 'MessageBatch' || t.name === 'Queue') needs.add('TSLean.Workers.Queue');
        if (t.name === 'AlarmInvocationInfo' || t.name === 'ScheduledEvent') needs.add('TSLean.Workers.Scheduler');
        if (t.name === 'ExecutionContext') needs.add('TSLean.Runtime.WebAPI');
        for (const a of t.args) this.scanTypeImports(a, needs);
        break;
      case 'Array': this.scanTypeImports(t.elem, needs); break;
      case 'Option': this.scanTypeImports(t.inner, needs); break;
      case 'Function':
        for (const p of t.params) this.scanTypeImports(p, needs);
        this.scanTypeImports(t.ret, needs);
        break;
      case 'Promise': needs.add('TSLean.Runtime.Monad'); break;
    }
  }

  private scanExprImports(e: IRExpr, needs: Set<string>): void {
    if (!e) return;
    if (e.tag === 'Var') {
      if (e.name.startsWith('Storage.')) {
        needs.add('TSLean.DurableObjects.Storage');
        needs.add('TSLean.DurableObjects.Model');
      }
      if (e.name.startsWith('DOCtx.')) {
        if (e.name.includes('WebSocket') || e.name.includes('WsDoState') || e.name.includes('acceptWebSocket') || e.name.includes('getWebSockets') || e.name.includes('getTags'))
          needs.add('TSLean.DurableObjects.WebSocket');
        needs.add('TSLean.DurableObjects.State');
        needs.add('TSLean.Runtime.Monad');
      }
      if (e.name.startsWith('AlarmState.'))
        needs.add('TSLean.DurableObjects.Alarm');
      if (e.name.startsWith('Transaction.'))
        needs.add('TSLean.DurableObjects.Transaction');
      if (e.name.startsWith('AssocMap.') || e.name.startsWith('AssocSet.'))
        needs.add('TSLean.Stdlib.HashMap');
      if (e.name === 'mkResponse' || e.name.startsWith('WebAPI.') || e.name === 'TSLean.fetch' || e.name === 'URL.parse' || e.name === 'WebSocketPair.new')
        needs.add('TSLean.Runtime.WebAPI');
      if (e.name.startsWith('KV.')) needs.add('TSLean.Workers.KV');
      if (e.name.startsWith('R2.')) needs.add('TSLean.Workers.R2');
      if (e.name.startsWith('D1.')) needs.add('TSLean.Workers.D1');
    }
    if (e.tag === 'App') {
      this.scanExprImports(e.fn, needs);
      for (const a of e.args) this.scanExprImports(a, needs);
    }
    if (e.tag === 'Let') { this.scanExprImports(e.value, needs); this.scanExprImports(e.body, needs); }
    if (e.tag === 'Bind') { this.scanExprImports(e.monad, needs); this.scanExprImports(e.body, needs); }
    if (e.tag === 'IfThenElse') {
      this.scanExprImports(e.cond, needs); this.scanExprImports(e.then, needs); this.scanExprImports(e.else_, needs);
    }
    if (e.tag === 'Sequence') for (const s of e.stmts) this.scanExprImports(s, needs);
    if (e.tag === 'Match') {
      this.scanExprImports(e.scrutinee, needs);
      for (const c of e.cases) this.scanExprImports(c.body, needs);
    }
    if (e.tag === 'Lambda') this.scanExprImports(e.body, needs);
    if (e.tag === 'FieldAccess') this.scanExprImports(e.obj, needs);
    if (e.tag === 'StructUpdate') {
      this.scanExprImports(e.base, needs);
      for (const f of e.fields) this.scanExprImports(f.value, needs);
    }
    if (e.tag === 'StructLit') for (const f of e.fields) this.scanExprImports(f.value, needs);
    if (e.tag === 'ArrayLit') for (const x of e.elems) this.scanExprImports(x, needs);
    if (e.tag === 'Await') this.scanExprImports(e.expr, needs);
    if (e.tag === 'Return') this.scanExprImports(e.value, needs);
    if (e.tag === 'Throw') this.scanExprImports(e.error, needs);
    if (e.tag === 'TryCatch') { this.scanExprImports(e.body, needs); this.scanExprImports(e.handler, needs); }
    if (e.tag === 'Assign') { this.scanExprImports(e.target, needs); this.scanExprImports(e.value, needs); }
  }

  // ─── Missing state structs ──────────────────────────────────────────────────

  emitMissingStateStructs(decls: IRDecl[]): LeanDecl[] {
    const defined = new Set<string>();
    const referenced = new Set<string>();
    for (const d of decls) {
      if (d.tag === 'StructDef') defined.add(d.name);
      if (d.tag === 'FuncDef') {
        for (const p of d.params) if (p.type.tag === 'TypeRef') referenced.add(p.type.name);
        if (d.retType.tag === 'TypeRef') referenced.add(d.retType.name);
      }
      if (d.tag === 'Namespace') {
        for (const inner of d.decls) {
          if (inner.tag === 'FuncDef') {
            for (const p of inner.params) if (p.type.tag === 'TypeRef') referenced.add(p.type.name);
            if (inner.retType.tag === 'TypeRef') referenced.add(inner.retType.name);
          }
        }
      }
    }
    const result: LeanDecl[] = [];
    for (const name of referenced) {
      if (!defined.has(name) && name.endsWith('State')) {
        result.push({
          tag: 'Comment',
          text: `Auto-generated empty state struct for ${name}`,
        });
        result.push({
          tag: 'Structure',
          name,
          tyParams: [],
          fields: [],
          deriving: DEFAULT_DERIVING,
        });
        result.push({ tag: 'Blank' });
        this.structFields.set(name, []);
      }
    }
    return result;
  }

  // ─── Mutual detection and declaration lowering ──────────────────────────────

  lowerDeclsWithMutual(decls: IRDecl[]): LeanDecl[] {
    // Collect type names for mutual detection
    const typeDecls = new Map<string, IRDecl>();
    for (const d of decls) {
      if ((d.tag === 'InductiveDef' || d.tag === 'StructDef') && d.name) {
        typeDecls.set(d.name, d);
      }
    }

    // Collect cross-references between type decls
    const typeRefs = new Map<string, Set<string>>();
    for (const [name, d] of typeDecls) {
      const refs = new Set<string>();
      const collect = (t: IRType): void => {
        if (t.tag === 'TypeRef' && typeDecls.has(t.name) && t.name !== name) refs.add(t.name);
        if ('inner' in t && t.inner) collect(t.inner as IRType);
        if ('elem' in t && t.elem) collect(t.elem as IRType);
        if ('key' in t && t.key) collect(t.key as IRType);
        if ('value' in t && t.value) collect(t.value as IRType);
        if ('ret' in t && t.ret) collect(t.ret as IRType);
        if ('params' in t && Array.isArray(t.params)) (t.params as IRType[]).forEach(collect);
        if ('args' in t && Array.isArray(t.args)) (t.args as IRType[]).forEach(collect);
        if ('elems' in t && Array.isArray(t.elems)) (t.elems as IRType[]).forEach(collect);
      };
      if (d.tag === 'InductiveDef') for (const c of d.ctors) for (const f of c.fields) collect(f.type);
      if (d.tag === 'StructDef') for (const f of d.fields) collect(f.type);
      typeRefs.set(name, refs);
    }

    // Find mutual groups
    const findMutualGroup = (start: string): Set<string> => {
      const group = new Set<string>();
      const queue = [start];
      while (queue.length > 0) {
        const name = queue.pop()!;
        if (group.has(name)) continue;
        group.add(name);
        const refs = typeRefs.get(name);
        if (refs) for (const ref of refs) {
          const backRefs = typeRefs.get(ref);
          if (backRefs && [...group].some(g => backRefs.has(g))) queue.push(ref);
        }
      }
      return group.size > 1 ? group : new Set<string>();
    };

    const mutualGroups: Set<string>[] = [];
    const inMutual = new Set<string>();
    for (const name of typeDecls.keys()) {
      if (inMutual.has(name)) continue;
      const group = findMutualGroup(name);
      if (group.size > 1) {
        mutualGroups.push(group);
        for (const n of group) inMutual.add(n);
      }
    }

    // Emit declarations
    const result: LeanDecl[] = [];
    const emittedMutuals = new Set<string>();

    for (const d of decls) {
      const name = 'name' in d ? (d as any).name : '';
      if (inMutual.has(name) && !emittedMutuals.has(name)) {
        const group = mutualGroups.find(g => g.has(name))!;
        const mutualDecls: LeanDecl[] = [];
        const groupNames: string[] = [];
        for (const memberName of group) {
          const memberDecl = typeDecls.get(memberName);
          if (memberDecl) {
            mutualDecls.push(this.lowerDecl(memberDecl, true));
            groupNames.push(memberName);
          }
          emittedMutuals.add(memberName);
        }
        result.push({ tag: 'Mutual', decls: mutualDecls });
        result.push({ tag: 'Blank' });
        // Standalone instances for mutual types
        for (const tn of groupNames) {
          result.push({ tag: 'StandaloneInstance', code: `instance : Inhabited ${tn} := ⟨sorry⟩` });
          result.push({ tag: 'StandaloneInstance', code: `instance : BEq ${tn} := ⟨fun _ _ => false⟩` });
          result.push({ tag: 'StandaloneInstance', code: `instance : Repr ${tn} := ⟨fun _ _ => .text s!"${tn}"⟩` });
        }
        result.push({ tag: 'Blank' });
        continue;
      }
      if (emittedMutuals.has(name)) continue;
      result.push(this.lowerDecl(d));
      result.push({ tag: 'Blank' });
    }
    return result;
  }

  // ─── Declaration lowering ───────────────────────────────────────────────────

  lowerDecl(d: IRDecl, inMutual = false): LeanDecl {
    switch (d.tag) {
      case 'StructDef': return this.lowerStruct(d, inMutual);
      case 'InductiveDef': return this.lowerInductive(d, inMutual);
      case 'TypeAlias': return this.lowerTypeAlias(d);
      case 'FuncDef': return this.lowerFunc(d);
      case 'VarDecl': return this.lowerVarDecl(d);
      case 'InstanceDef': return this.lowerInstance(d);
      case 'TheoremDef': return this.lowerTheorem(d);
      case 'ClassDecl': return this.lowerClass(d);
      case 'Namespace': return this.lowerNamespace(d);
      case 'RawLean': return { tag: 'Raw', code: d.code };
      case 'SectionDecl': return {
        tag: 'Section',
        name: d.name,
        decls: d.decls.flatMap(x => [this.lowerDecl(x), { tag: 'Blank' as const }]),
      };
      case 'AttributeDecl': return { tag: 'Attribute', attr: d.attr, target: d.target };
      case 'DeriveDecl': return { tag: 'Deriving', classes: d.classes, typeName: d.typeName };
    }
  }

  private lowerStruct(d: Extract<IRDecl, { tag: 'StructDef' }>, inMutual: boolean): LeanDecl {
    const enrichedFields = this.structFields.get(d.name) ?? d.fields;
    const fields: LeanField[] = enrichedFields.map(f => {
      const rawName = (f.name.startsWith('_') && f.name.length > 1 && /[a-zA-Z]/.test(f.name[1]))
        ? f.name.slice(1) : f.name;
      return { name: rawName, ty: this.lowerType(f.type) };
    });
    const isBranded = enrichedFields.length === 1 && enrichedFields[0].name === 'val';
    const deriving = inMutual ? [] : safeDeriving(fields, isBranded);
    return {
      tag: 'Structure',
      name: d.name,
      tyParams: d.typeParams.map(p => ({ name: p.name, explicit: true })),
      fields,
      extends_: d.extends_,
      deriving,
      comment: d.comment,
    };
  }

  private lowerInductive(d: Extract<IRDecl, { tag: 'InductiveDef' }>, inMutual: boolean): LeanDecl {
    const tpArgs = d.typeParams.map(p => p.name).join(' ');
    const ctors: LeanCtor[] = d.ctors.map(c => ({
      name: c.name,
      fields: c.fields.map(f => {
        let ty = this.lowerType(f.type);
        // Fix recursive self-references: bare TypeRef matching the inductive name → apply type params
        if (f.type?.tag === 'TypeRef' && f.type.name === d.name && f.type.args.length === 0 && tpArgs) {
          ty = { tag: 'TyApp', fn: { tag: 'TyName', name: d.name }, args: d.typeParams.map(p => ({ tag: 'TyName' as const, name: p.name })) };
        }
        return { name: f.name, ty };
      }),
    }));
    return {
      tag: 'Inductive',
      name: d.name,
      tyParams: d.typeParams.map(p => ({ name: p.name, explicit: true })),
      ctors,
      deriving: inMutual ? [] :
        (ctors.some(c => c.fields.some(f => containsArrowType(f.ty))) ? ['Inhabited'] : DEFAULT_DERIVING),
      comment: d.comment,
    };
  }

  private lowerTypeAlias(d: Extract<IRDecl, { tag: 'TypeAlias' }>): LeanDecl {
    const bodyStr = irTypeToLean(d.body);
    // Self-referencing type alias → structure with tag+fields (for IR types)
    const knownTaggedTypes = new Set(['IRExpr', 'IRDecl']);
    if (bodyStr === d.name || bodyStr === 'String' || bodyStr === 'TSAny') {
      if (knownTaggedTypes.has(d.name)) {
        const fields: LeanField[] = [
          { name: 'tag', ty: { tag: 'TyName', name: 'String' } },
          { name: 'type', ty: { tag: 'TyName', name: 'IRType' }, default_: { tag: 'Default' } },
          { name: 'effect', ty: { tag: 'TyName', name: 'Effect' }, default_: { tag: 'Default' } },
        ];
        const extraFields: Record<string, string[]> = {
          'IRExpr': ['name', 'value', 'field', 'obj', 'fn', 'args', 'left', 'right', 'op',
                     'cond', 'then_', 'else_', 'body', 'scrutinee', 'cases', 'stmts',
                     'params', 'handler', 'target', 'elems', 'fields', 'base', 'updates',
                     'expr', 'monad', 'index', 'annot', 'targetType', 'errName'],
          'IRDecl': ['name', 'typeParams', 'params', 'retType', 'body', 'fields', 'ctors',
                     'decls', 'code', 'extends_', 'methods', 'isPartial', 'attr',
                     'classes', 'typeName', 'statement', 'proof', 'docComment', 'comment',
                     'mutable', 'value'],
        };
        for (const f of extraFields[d.name] ?? []) {
          fields.push({ name: f, ty: { tag: 'TyName', name: 'String' }, default_: { tag: 'Default' } });
        }
        return {
          tag: 'Structure',
          name: d.name,
          tyParams: d.typeParams.map(p => ({ name: p.name, explicit: true })),
          fields,
          deriving: ['Repr', 'BEq', 'Inhabited'],
          comment: d.comment,
        };
      }
      return {
        tag: 'Abbrev',
        name: d.name,
        tyParams: d.typeParams.map(p => ({ name: p.name, explicit: false })),
        body: { tag: 'TyName', name: 'String' },
        comment: d.comment,
      };
    }
    return {
      tag: 'Abbrev',
      name: d.name,
      tyParams: d.typeParams.map(p => ({ name: p.name, explicit: false })),
      body: this.lowerType(d.body),
      comment: d.comment,
    };
  }

  private lowerFunc(d: Extract<IRDecl, { tag: 'FuncDef' }>): LeanDecl {
    const fixedEffect = fixStateEffect(d.effect, d.params);
    const isRecursive = d.isPartial ?? bodyContainsVarRef(d.body, d.name);
    const body = this.lowerFuncBody(d.body, fixedEffect, d.retType, d.name);

    // Check if body uses default (needs Inhabited constraint)
    const needsInhabited = this.exprUsesDefault(body) && d.typeParams.length > 0;

    const tyParams: LeanTyParam[] = d.typeParams.map(t => {
      const constraints: string[] = [];
      if (needsInhabited) constraints.push('Inhabited');
      if (t.constraint) constraints.push(...constraintToTypeClasses(t.constraint));
      return { name: t.name, explicit: false, constraints: constraints.length ? constraints : undefined };
    });

    const params: LeanParam[] = d.params.map(p => this.lowerParam(p, fixedEffect));
    const retTy = this.lowerRetSig(fixedEffect, this.lowerType(d.retType));

    return {
      tag: 'Def',
      partial: isRecursive,
      name: d.name,
      tyParams,
      params,
      retTy,
      body,
      where_: d.where_?.map(w => this.lowerDecl(w)),
      docComment: d.docComment,
      comment: d.comment,
    };
  }

  private lowerFuncBody(body: IRExpr, effect: Effect, retType: IRType, funcName: string): LeanExpr {
    if (!isPure(effect)) {
      // Effectful function: wrap body in `do`
      const inner = this.lowerExpr(body, effect);
      // For Unit return type, ensure we end with `pure ()`
      if (retType.tag === 'Unit' && !this.exprReturns(inner)) {
        return { tag: 'Do', body: { tag: 'Seq', stmts: [inner, { tag: 'Pure', value: { tag: 'Lit', value: '()' } }] } };
      }
      return { tag: 'Do', body: inner };
    }
    // Pure function
    const retSig = this.lowerRetSig(effect, this.lowerType(retType));
    const isMonadicRet = this.tyStartsWith(retSig, 'IO') || this.tyStartsWith(retSig, 'StateT') || this.tyStartsWith(retSig, 'ExceptT');
    if (isMonadicRet) {
      const ioCtx: Effect = { tag: 'IO' };
      return { tag: 'Do', body: this.lowerExpr(body, ioCtx) };
    }
    const lowered = this.lowerExpr(body, effect);
    // Check if the pure body needs a `do` wrapper (multiple lets)
    if (this.pureBodyNeedsDo(lowered)) {
      return { tag: 'Do', body: lowered };
    }
    return lowered;
  }

  private pureBodyNeedsDo(e: LeanExpr): boolean {
    // A let followed by more lets or complex expressions needs `do` in pure Lean
    if (e.tag === 'Let' && (e.body.tag === 'Let' || e.body.tag === 'If' || e.body.tag === 'Match')) {
      return true;
    }
    if (e.tag === 'Seq') {
      const hasLet = e.stmts.some(s => s.tag === 'Let');
      return hasLet && e.stmts.length > 1;
    }
    return false;
  }

  private exprReturns(e: LeanExpr): boolean {
    switch (e.tag) {
      case 'Return': case 'Pure': case 'Throw': return true;
      case 'If': return this.exprReturns(e.then_) && this.exprReturns(e.else_);
      case 'Match': return e.arms.every(a => this.exprReturns(a.body));
      case 'Seq': return e.stmts.length > 0 && this.exprReturns(e.stmts[e.stmts.length - 1]);
      case 'Do': return this.exprReturns(e.body);
      case 'Let': return this.exprReturns(e.body);
      case 'Bind': return this.exprReturns(e.body);
      default: return false;
    }
  }

  private exprUsesDefault(e: LeanExpr): boolean {
    if (e.tag === 'Default') return true;
    // Shallow check — don't recurse deeply
    if (e.tag === 'Seq') return e.stmts.some(s => this.exprUsesDefault(s));
    if (e.tag === 'Let') return this.exprUsesDefault(e.value) || this.exprUsesDefault(e.body);
    if (e.tag === 'If') return this.exprUsesDefault(e.then_) || this.exprUsesDefault(e.else_);
    if (e.tag === 'Do') return this.exprUsesDefault(e.body);
    return false;
  }

  private tyStartsWith(t: LeanTy, prefix: string): boolean {
    if (t.tag === 'TyName') return t.name === prefix;
    if (t.tag === 'TyApp') return this.tyStartsWith(t.fn, prefix);
    return false;
  }

  private lowerVarDecl(d: Extract<IRDecl, { tag: 'VarDecl' }>): LeanDecl {
    let ty = this.lowerType(d.type);
    let val = this.lowerExpr(d.value, Pure);
    // Anonymous object values lowered to default → infer AssocMap type from field values
    if (val.tag === 'Default' && d.value?.tag === 'StructLit' && d.value.fields.length > 3) {
      const firstField = d.value.fields[0];
      if (firstField?.value?.tag === 'StructLit') {
        // Nested struct values: infer value type from struct fields that match known types
        const valueTypeName = this.inferStructValueType(firstField.value);
        ty = { tag: 'TyApp', fn: { tag: 'TyName', name: 'AssocMap' },
               args: [{ tag: 'TyName', name: 'String' }, { tag: 'TyName', name: valueTypeName }] };
      } else if (firstField?.value?.type?.tag === 'TypeRef' && firstField.value.type.name !== '__object') {
        ty = { tag: 'TyApp', fn: { tag: 'TyName', name: 'AssocMap' },
               args: [{ tag: 'TyName', name: 'String' }, { tag: 'TyName', name: firstField.value.type.name }] };
      }
    }
    if (d.mutable) {
      return { tag: 'Raw', code: `-- mutable binding '${d.name}' modelled as IO.Ref\ndef ${d.name}_ref : IO (IO.Ref ${this.printTyInline(ty)}) := IO.mkRef ${this.printExprInline(val)}` };
    }
    return {
      tag: 'Def',
      partial: false,
      name: d.name,
      tyParams: [],
      params: [],
      retTy: ty,
      body: val,
    };
  }

  /** Infer a struct's type name from its field signatures (for method table objects). */
  private inferStructValueType(structLit: IRExpr): string {
    if (structLit.tag !== 'StructLit') return 'String';
    // Look for known struct patterns by field names
    const fieldNames = new Set(structLit.fields.map(f => f.name));
    if (fieldNames.has('leanFn') || fieldNames.has('resultType') || fieldNames.has('argOrder'))
      return 'MethodTx';
    if (fieldNames.has('leanExpr') || fieldNames.has('maxArgs'))
      return 'GlobalTx';
    // Check if any field's value has a known named type
    for (const f of structLit.fields) {
      if (f.value?.type?.tag === 'TypeRef' && f.value.type.name !== '__object' && f.value.type.name !== 'Any')
        return f.value.type.name;
    }
    return 'String';
  }

  private lowerInstance(d: Extract<IRDecl, { tag: 'InstanceDef' }>): LeanDecl {
    return {
      tag: 'Instance',
      typeClass: d.typeClass,
      args: d.typeArgs.map(t => this.lowerType(t)),
      methods: d.methods.filter(m => m.tag === 'FuncDef').map(m => {
        const fd = m as Extract<IRDecl, { tag: 'FuncDef' }>;
        return {
          name: fd.name,
          params: fd.params.map(p => this.lowerParam(p, fd.effect)),
          body: this.lowerExpr(fd.body, fd.effect),
        };
      }),
    };
  }

  private lowerTheorem(d: Extract<IRDecl, { tag: 'TheoremDef' }>): LeanDecl {
    return {
      tag: 'Theorem',
      name: d.name,
      statement: d.statement,
      proof: d.proof,
      comment: d.comment,
    };
  }

  private lowerClass(d: Extract<IRDecl, { tag: 'ClassDecl' }>): LeanDecl {
    return {
      tag: 'Class',
      name: d.name,
      tyParams: d.typeParams.map(p => ({ name: p.name, explicit: false })),
      methods: d.methods.map(m => ({ name: m.name, ty: this.lowerType(m.type) })),
      comment: d.comment,
    };
  }

  private lowerNamespace(d: Extract<IRDecl, { tag: 'Namespace' }>): LeanDecl {
    // Detect forward refs among functions for mutual blocks
    const funcNames = new Set(d.decls.filter(x => x.tag === 'FuncDef').map(x => (x as any).name as string));
    const hasForwardRefs = d.decls.some(x =>
      x.tag === 'FuncDef' && funcNames.size > 1 &&
      bodyContainsAnyVarRef((x as any).body, funcNames, (x as any).name)
    );

    const decls: LeanDecl[] = [];
    if (hasForwardRefs && funcNames.size > 1) {
      // Non-functions first
      for (const x of d.decls) {
        if (x.tag !== 'FuncDef') { decls.push(this.lowerDecl(x)); decls.push({ tag: 'Blank' }); }
      }
      // Mutual block for functions
      const funcDecls: LeanDecl[] = [];
      for (const x of d.decls) {
        if (x.tag === 'FuncDef') funcDecls.push(this.lowerDecl(x));
      }
      decls.push({ tag: 'Mutual', decls: funcDecls });
    } else {
      for (const x of d.decls) {
        decls.push(this.lowerDecl(x));
        decls.push({ tag: 'Blank' });
      }
    }
    return { tag: 'Namespace', name: d.name, decls };
  }

  // ─── Type lowering ──────────────────────────────────────────────────────────

  lowerType(t: IRType): LeanTy {
    switch (t.tag) {
      case 'Nat': return { tag: 'TyName', name: 'Nat' };
      case 'Int': return { tag: 'TyName', name: 'Int' };
      case 'Float': return { tag: 'TyName', name: 'Float' };
      case 'String': return { tag: 'TyName', name: 'String' };
      case 'Bool': return { tag: 'TyName', name: 'Bool' };
      case 'Unit': return { tag: 'TyName', name: 'Unit' };
      case 'Never': return { tag: 'TyName', name: 'Empty' };
      case 'Option': return { tag: 'TyApp', fn: { tag: 'TyName', name: 'Option' }, args: [this.lowerType(t.inner)] };
      case 'Array': return { tag: 'TyApp', fn: { tag: 'TyName', name: 'Array' }, args: [this.lowerType(t.elem)] };
      case 'Tuple':
        if (t.elems.length === 0) return { tag: 'TyName', name: 'Unit' };
        return { tag: 'TyTuple', elems: t.elems.map(e => this.lowerType(e)) };
      case 'Map': return {
        tag: 'TyApp',
        fn: { tag: 'TyName', name: 'AssocMap' },
        args: [this.lowerType(t.key), this.lowerType(t.value)],
      };
      case 'Set': return { tag: 'TyApp', fn: { tag: 'TyName', name: 'Array' }, args: [this.lowerType(t.elem)] };
      case 'Promise': return { tag: 'TyApp', fn: { tag: 'TyName', name: 'IO' }, args: [this.lowerType(t.inner)] };
      case 'Result': return {
        tag: 'TyApp',
        fn: { tag: 'TyName', name: 'Except' },
        args: [this.lowerType(t.err), this.lowerType(t.ok)],
      };
      case 'Function': {
        const params = t.params.map(p => this.lowerType(p));
        const ret = this.lowerType(t.ret);
        return { tag: 'TyArrow', params: params.length > 0 ? params : [{ tag: 'TyName', name: 'Unit' }], ret };
      }
      case 'TypeRef': {
        const name = t.name === 'Any' ? 'TSAny' : t.name;
        // Inexpressible TS utility types in generic context → sorry
        if (INEXPRESSIBLE_UTILITY_TYPES.has(name) && t.args.some(a => a.tag === 'TypeVar')) {
          return { tag: 'TyName', name: 'String' };
        }
        if (t.args.length === 0) return { tag: 'TyName', name };
        return { tag: 'TyApp', fn: { tag: 'TyName', name }, args: t.args.map(a => this.lowerType(a)) };
      }
      case 'TypeVar': return { tag: 'TyName', name: t.name };
      case 'Structure': return { tag: 'TyName', name: t.name };
      case 'Inductive': return { tag: 'TyName', name: t.name };
      case 'Dependent': return this.lowerType(t.body);
      case 'Subtype': return this.lowerType(t.base);
      case 'Universe': return { tag: 'TyName', name: `Type ${t.level > 0 ? t.level : ''}`.trim() };
    }
  }

  lowerRetSig(eff: Effect, retTy: LeanTy): LeanTy {
    const alreadyIO = this.tyStartsWith(retTy, 'IO');
    const innerRet = alreadyIO ? this.stripIO(retTy) : retTy;
    switch (eff.tag) {
      case 'Pure': return retTy;
      case 'IO': case 'Async':
        return alreadyIO ? retTy : { tag: 'TyApp', fn: { tag: 'TyName', name: 'IO' }, args: [retTy] };
      case 'State': {
        // StateT S IO T — IO is the monad (Type → Type), T is the return type.
        // They must be separate arguments, NOT wrapped as (IO T).
        const stTy = this.lowerType(eff.stateType);
        return { tag: 'TyApp', fn: { tag: 'TyName', name: 'StateT' },
                 args: [stTy, { tag: 'TyName', name: 'IO' }, innerRet] };
      }
      case 'Except': {
        // ExceptT E IO T — same pattern: IO and T are separate arguments.
        const errTy = this.lowerType(eff.errorType);
        return { tag: 'TyApp', fn: { tag: 'TyName', name: 'ExceptT' },
                 args: [errTy, { tag: 'TyName', name: 'IO' }, innerRet] };
      }
      case 'Combined': {
        // Build monad transformer stack: StateT S (ExceptT E IO) T
        // Each transformer takes args + inner monad. Return type is the outermost argument.
        const se = eff.effects.find((e): e is Extract<Effect, { tag: 'State' }> => e.tag === 'State');
        const ee = eff.effects.find((e): e is Extract<Effect, { tag: 'Except' }> => e.tag === 'Except');

        // Build the inner monad (from inside out): IO, then ExceptT E IO, then StateT S (ExceptT E IO)
        let monad: LeanTy = { tag: 'TyName', name: 'IO' };

        if (ee) {
          monad = { tag: 'TyApp', fn: { tag: 'TyName', name: 'ExceptT' },
                    args: [this.lowerType(ee.errorType), monad] };
        } else if (eff.effects.some(e => e.tag === 'Except')) {
          monad = { tag: 'TyApp', fn: { tag: 'TyName', name: 'ExceptT' },
                    args: [{ tag: 'TyName', name: 'TSError' }, monad] };
        }

        if (se) {
          monad = { tag: 'TyApp', fn: { tag: 'TyName', name: 'StateT' },
                    args: [this.lowerType(se.stateType), monad] };
        } else if (eff.effects.some(e => e.tag === 'State')) {
          monad = { tag: 'TyApp', fn: { tag: 'TyName', name: 'StateT' },
                    args: [{ tag: 'TyName', name: 'σ' }, monad] };
        }

        if (monad.tag === 'TyName' && monad.name === 'IO' && alreadyIO) return retTy;
        // Apply the return type as the final argument
        return { tag: 'TyApp', fn: monad.tag === 'TyName' ? monad : monad.fn,
                 args: [...(monad.tag === 'TyApp' ? monad.args : []), innerRet] };
      }
    }
  }

  private stripIO(t: LeanTy): LeanTy {
    if (t.tag === 'TyApp' && t.fn.tag === 'TyName' && t.fn.name === 'IO' && t.args.length === 1) {
      return t.args[0];
    }
    return t;
  }

  // ─── Parameter lowering ─────────────────────────────────────────────────────

  lowerParam(p: IRParam, _eff: Effect): LeanParam {
    let ty = this.lowerType(p.type);
    // Resolve class→state mapping
    ty = this.resolveStateTy(ty);
    return {
      name: p.name,
      ty,
      implicit: p.implicit,
      default_: p.default_ ? this.lowerExpr(p.default_, Pure) : undefined,
    };
  }

  private resolveStateTy(ty: LeanTy): LeanTy {
    if (ty.tag === 'TyName') {
      const state = this.classToState.get(ty.name);
      if (state) return { tag: 'TyName', name: state };
    }
    return ty;
  }

  // ─── Expression lowering ────────────────────────────────────────────────────

  lowerExpr(e: IRExpr, ctx: Effect): LeanExpr {
    if (!e) return { tag: 'Sorry' };
    try { return this._lowerExpr(e, ctx); }
    catch (err) {
      const tag = (e as { tag?: string }).tag ?? 'unknown';
      const msg = err instanceof Error ? err.message : String(err);
      console.warn(`[lower] failed to lower ${tag} expression: ${msg}`);
      currentTracker().add({
        location: `lower:${tag}`, reason: msg,
        category: 'unresolved-expr', hint: 'check if the expression pattern is supported',
      });
      return sorryForType(e.type);
    }
  }

  private _lowerExpr(e: IRExpr, ctx: Effect): LeanExpr {
    switch (e.tag) {
      case 'LitNat': return { tag: 'Lit', value: String(e.value) };
      case 'LitInt': return { tag: 'Lit', value: String(e.value) };
      case 'LitFloat': return Number.isInteger(e.value)
        ? { tag: 'TypeAnnot', expr: { tag: 'Lit', value: String(e.value) }, ty: { tag: 'TyName', name: 'Float' } }
        : { tag: 'Lit', value: String(e.value) };
      case 'LitString': return { tag: 'Lit', value: JSON.stringify(e.value) };
      case 'LitBool': return { tag: 'Lit', value: e.value ? 'true' : 'false' };
      case 'LitUnit': return { tag: 'Lit', value: '()' };
      case 'LitNull': return { tag: 'None' };
      case 'Hole': return defaultForType(e.type);

      case 'Var': {
        if (e.name.startsWith('"') && e.name.endsWith('"')) return { tag: 'Lit', value: e.name };
        if (e.name === 'AssocSet.empty') return { tag: 'ArrayLit', elems: [] };
        if (e.name === 'AssocSet.insert') return { tag: 'Var', name: 'Array.push' };
        if (e.name === 'AssocSet.contains') return { tag: 'Var', name: 'Array.contains' };
        return { tag: 'Var', name: e.name };
      }

      case 'FieldAccess': return this.lowerFieldAccess(e, ctx);
      case 'IndexAccess': {
        const obj = this.lowerExprP(e.obj, ctx);
        const idx = this.lowerExprP(e.index, ctx);
        return { tag: 'App', fn: { tag: 'FieldAccess', obj, field: 'getD' }, args: [idx, { tag: 'Default' }] };
      }

      case 'Lambda': {
        const ps = e.params.map(p => p.name);
        const lambdaCtx = e.effect ?? ctx;
        const body = this.lowerExpr(e.body, lambdaCtx);
        const needsDo = !isPure(lambdaCtx) && this.exprHasBinds(body);
        if (needsDo) {
          return { tag: 'Lam', params: ps.length > 0 ? ps : ['_'], body: { tag: 'Do', body } };
        }
        return { tag: 'Lam', params: ps.length > 0 ? ps : ['_'], body };
      }

      case 'App': return this.lowerApp(e, ctx);
      case 'TypeApp': {
        const fn = this.lowerExpr(e.fn, ctx);
        // Type args are applied as explicit args in Lean
        const tArgs = e.typeArgs.map(t => ({ tag: 'Paren' as const, inner: { tag: 'Lit' as const, value: irTypeToLean(t) } }));
        return { tag: 'App', fn, args: tArgs };
      }

      case 'Let': {
        const val = this.lowerExpr(e.value, ctx);
        const body = this.lowerExpr(e.body, ctx);
        const isRec = e.value.tag === 'Lambda' && bodyContainsVarRef(e.value.body, e.name);
        const ty = e.annot ? this.lowerType(e.annot) : undefined;
        return { tag: 'Let', name: e.name, ty, value: val, body, rec: isRec };
      }

      case 'Bind': {
        const monad = this.lowerExpr(e.monad, ctx);
        const body = this.lowerExpr(e.body, ctx);
        // Bind IR nodes always represent monadic operations (← in Lean)
        return { tag: 'Bind', name: e.name, value: monad, body };
      }

      case 'IfThenElse': return this.lowerIf(e, ctx);

      case 'Match': {
        const scrut = this.lowerExpr(e.scrutinee, ctx);
        const arms: LeanMatchArm[] = e.cases.map(c => ({
          pat: this.lowerPat(c.pattern),
          guard: c.guard ? this.lowerExpr(c.guard, ctx) : undefined,
          body: this.lowerExpr(c.body, ctx),
        }));
        return { tag: 'Match', scrutinee: scrut, arms };
      }

      case 'Sequence': {
        if (e.stmts.length === 0) return { tag: 'Lit', value: '()' };
        if (e.stmts.length === 1) return this.lowerExpr(e.stmts[0], ctx);
        // Chain sequential ifs
        const chained = this.chainSequentialIfs(e.stmts);
        if (chained.length === 1) return this.lowerExpr(chained[0], ctx);
        return { tag: 'Seq', stmts: chained.map(s => this.lowerExpr(s, ctx)) };
      }

      case 'DoBlock': return this.lowerDoBlock(e.stmts, ctx);

      case 'Return': {
        const val = this.lowerExpr(e.value, ctx);
        return !isPure(ctx) ? { tag: 'Pure', value: val } : val;
      }

      case 'StructLit': return this.lowerStructLit(e, ctx);
      case 'StructUpdate': return this.lowerStructUpdate(e, ctx);

      case 'CtorApp': {
        const args = e.args.map(a => this.lowerExprP(a, ctx));
        const name = e.ctor;
        // Map known constructors to their Lean equivalents
        const knownCtors: Record<string, string> = {
          'TextEncoder': 'TSLean.Stubs.WebAPIs.TextEncoder.mk\'',
          'TextDecoder': 'TSLean.Stubs.WebAPIs.TextDecoder.mk\'',
          'Headers': 'TSLean.Stubs.WebAPIs.Headers.mk\'',
          'AbortController': 'TSLean.Stubs.WebAPIs.AbortController.mk\'',
          'EventTarget': 'TSLean.Stubs.WebAPIs.EventTarget.mk\'',
          'WebSocket': 'TSLean.Stubs.WebAPIs.WebSocket.mk\'',
          'Uint8Array': 'default',
          'AsyncLocalStorage': 'default',
          'ReadableStream': 'default',
          'WritableStream': 'default',
          'Map': 'AssocMap.empty',
          'Set': '#[]',
          'Error': 'default',
          'TypeError': 'default',
          'RangeError': 'default',
        };
        const mapped = knownCtors[name];
        if (mapped) {
          if (mapped === 'default' || mapped === '#[]') return { tag: mapped === '#[]' ? 'ArrayLit' : 'Default', elems: [] } as LeanExpr;
          return args.length === 0
            ? { tag: 'Var', name: mapped }
            : { tag: 'App', fn: { tag: 'Var', name: mapped }, args };
        }
        // Unknown uppercase constructor with args → default
        if (args.length > 0 && /^[A-Z][a-zA-Z]*$/.test(name) && !name.includes('.')) {
          return { tag: 'Default' };
        }
        return args.length === 0
          ? { tag: 'Var', name }
          : { tag: 'App', fn: { tag: 'Var', name }, args };
      }

      case 'ArrayLit': {
        if (e.type?.tag === 'Tuple') {
          return { tag: 'TupleLit', elems: e.elems.map(x => this.lowerExpr(x, ctx)) };
        }
        return { tag: 'ArrayLit', elems: e.elems.map(x => this.lowerExpr(x, ctx)) };
      }

      case 'TupleLit': return { tag: 'TupleLit', elems: e.elems.map(x => this.lowerExpr(x, ctx)) };
      case 'Pure_': return { tag: 'Pure', value: this.lowerExprP(e.value, ctx) };
      case 'StateGet': return { tag: 'Var', name: 'get' };
      case 'StateSet': return { tag: 'App', fn: { tag: 'Var', name: 'set' }, args: [this.lowerExprP(e.value, ctx)] };

      case 'Throw': {
        const err = this.lowerExpr(e.error, ctx);
        return { tag: 'Throw', value: err };
      }

      case 'TryCatch': {
        if (isPure(ctx)) return { tag: 'Default' };
        const body = this.lowerExprP(e.body, ctx);
        const handler = this.lowerExpr(e.handler, ctx);
        const tc: LeanExpr = { tag: 'TryCatch', body, errName: e.errName, handler };
        // finally: bind result, run cleanup, return result
        if (e.finally_) {
          const fin = this.lowerExpr(e.finally_, ctx);
          return {
            tag: 'Let', name: '_tc_result', value: tc,
            body: { tag: 'Seq', stmts: [fin, { tag: 'Var', name: '_tc_result' }] },
          };
        }
        return tc;
      }

      case 'Await': return this.lowerExpr(e.expr, ctx);

      case 'Assign': return this.lowerAssign(e, ctx);
      case 'BinOp': return this.lowerBinOp(e, ctx);
      case 'UnOp': {
        const op = e.op === 'Not' ? '!' : e.op === 'Neg' ? '-' : '~~~';
        return { tag: 'UnOp', op, operand: this.lowerExprP(e.operand, ctx) };
      }

      case 'Cast': return this.lowerCast(e, ctx);
      case 'IsType': {
        const typeName = e.testType?.tag === 'TypeRef' ? e.testType.name : (e.testType?.tag ?? 'unknown');
        // typeof checks on known types → compile-time true/false
        const exprType = e.expr?.type;
        if (typeName === 'string' && exprType?.tag === 'String') return { tag: 'Lit', value: 'true' };
        if (typeName === 'number' && (exprType?.tag === 'Float' || exprType?.tag === 'Nat')) return { tag: 'Lit', value: 'true' };
        if (typeName === 'boolean' && exprType?.tag === 'Bool') return { tag: 'Lit', value: 'true' };
        if (typeName === 'function') return { tag: 'Lit', value: 'true' }; // functions always exist in Lean
        if (typeName === 'undefined') return { tag: 'Lit', value: 'false' }; // no undefined in Lean
        // typeof on Option → .isSome (undefined check)
        if (typeName === 'undefined' && exprType?.tag === 'Option') {
          return { tag: 'UnOp', op: '!', operand: { tag: 'FieldAccess', obj: this.lowerExpr(e.expr, ctx), field: 'isSome' } };
        }
        // instanceof with discriminated unions → check if the variant matches
        if (e.testType?.tag === 'TypeRef' && exprType?.tag === 'TypeRef') {
          const inner = this.lowerExpr(e.expr, ctx);
          // For Error types: always true in catch blocks
          if (typeName === 'Error' || typeName.endsWith('Error')) return { tag: 'Lit', value: 'true' };
          // For known struct types → true (nominal type check)
          return { tag: 'Lit', value: 'true' };
        }
        // Fallback: emit false for unknown typeof, with tracker entry
        currentTracker().add({
          location: `IsType:${typeName}`, reason: `typeof/instanceof on unknown type`,
          category: 'type-test', hint: 'use discriminated unions instead',
        });
        return { tag: 'Lit', value: 'false' };
      }
      case 'Panic': return { tag: 'Panic', msg: e.msg };
      case 'OptChain': return this.lowerExpr(e.expr, ctx);
      case 'TypeNarrow': return this.lowerExpr(e.expr, ctx);
      case 'YieldExpr': {
        const val = e.value ? this.lowerExpr(e.value, ctx) : { tag: 'Lit' as const, value: '()' };
        return { tag: 'App', fn: { tag: 'Var', name: 'yield' }, args: [val] };
      }
      case 'MultiLet': {
        let result = this.lowerExpr(e.body, ctx);
        for (const b of [...e.bindings].reverse()) {
          result = { tag: 'Let', name: b.name, ty: this.lowerType(b.type), value: this.lowerExpr(b.value, ctx), body: result };
        }
        return result;
      }
      case 'Labeled': return this.lowerExpr(e.body, ctx);
      case 'Break': return { tag: 'LineComment', text: 'break', expr: { tag: 'Lit', value: '()' } };
      case 'Continue': return { tag: 'LineComment', text: 'continue', expr: { tag: 'Lit', value: '()' } };
      default: return { tag: 'Default' };
    }
  }

  /** Lower an expression and wrap in Paren if it's compound. */
  private lowerExprP(e: IRExpr, ctx: Effect): LeanExpr {
    const lowered = this.lowerExpr(e, ctx);
    if (needsParens(e)) return { tag: 'Paren', inner: lowered };
    return lowered;
  }

  // ─── Complex expression helpers ─────────────────────────────────────────────

  private lowerFieldAccess(e: Extract<IRExpr, { tag: 'FieldAccess' }>, ctx: Effect): LeanExpr {
    // self.state.X → self.X
    if (e.obj.tag === 'FieldAccess' && e.obj.field === 'state' &&
        e.obj.obj.tag === 'Var' && e.obj.obj.name === 'self') {
      if (e.field === 'storage') return { tag: 'Default' };
      return { tag: 'FieldAccess', obj: { tag: 'Var', name: 'self' }, field: e.field };
    }
    // self.storage.X → default
    if (e.obj.tag === 'FieldAccess' && e.obj.field === 'storage' &&
        e.obj.obj.tag === 'Var' && e.obj.obj.name === 'self') {
      return { tag: 'Default' };
    }

    // .tag on inductive types → sorry
    const objType = e.obj?.type;
    const isInductiveType = objType?.tag === 'Inductive' ||
      (objType?.tag === 'TypeRef' && ['Effect', 'IRType', 'BinOp', 'UnOp'].includes(objType?.name ?? ''));
    if (isInductiveType && (e.field === 'tag' || e.field === 'effects' ||
        e.field === 'stateType' || e.field === 'errorType')) {
      if (e.field === 'tag') return { tag: 'Sorry', ty: { tag: 'TyName', name: 'String' } };
      if (e.field === 'effects') return { tag: 'Sorry', ty: { tag: 'TyApp', fn: { tag: 'TyName', name: 'Array' }, args: [{ tag: 'TyName', name: 'Effect' }] } };
      return { tag: 'Sorry' };
    }

    const obj = this.lowerExpr(e.obj, ctx);

    // Optional chaining: .bind on sorry/default → none (chain terminates gracefully)
    if (e.field === 'bind' && (obj.tag === 'Sorry' || obj.tag === 'Default')) {
      return { tag: 'None' };
    }
    // .getD on sorry → return the default value directly
    if (e.field === 'getD' && (obj.tag === 'Sorry' || obj.tag === 'Default')) {
      return obj;
    }

    const isString = e.obj?.type?.tag === 'String';

    // Map JS field/method names to Lean equivalents
    const fieldMap: Record<string, string> = {
      'json': 'toJson', 'text': 'text', 'toLowerCase': 'toLower', 'toUpperCase': 'toUpper',
      'trim': 'trim', 'startsWith': 'startsWith', 'endsWith': 'endsWith',
      'pop': 'back?', 'push': 'push', 'reduce': 'foldl', 'filter': 'filter',
      'map': 'map', 'find': 'find?', 'some': 'any', 'every': 'all',
      'reverse': 'reverse', 'flat': 'join', 'flatMap': 'flatMap', 'concat': 'append',
      'indexOf': 'indexOf?', 'slice': 'extract',
      'split': isString ? 'splitOn' : 'split',
      'join': isString ? 'intercalate' : 'foldl (· ++ ·) ""',
      'length': isString ? 'length' : 'size',
      'size': isString ? 'length' : 'size',
      'includes': isString ? 'includes' : 'contains',
    };
    let mappedField = (e.field && fieldMap[e.field]) ?? e.field ?? 'default';
    if (typeof mappedField !== 'string') mappedField = String(mappedField);

    if (mappedField === 'toString' || mappedField.startsWith('function'))
      return { tag: 'App', fn: { tag: 'Var', name: 'toString' }, args: [obj] };

    // JS-specific methods with no Lean equivalent
    if (['test', 'getSourceFile', 'fileExists', 'readFile', 'writeFile', 'existsSync'].includes(mappedField))
      return sorryForType(e.type);

    // Strip leading underscore from private fields
    if (mappedField.startsWith('_') && mappedField.length > 1 && /[a-zA-Z]/.test(mappedField[1]))
      mappedField = mappedField.slice(1);

    // TS API types → sorry for non-string methods
    const isAnyType = e.obj?.type?.tag === 'TypeRef' && TS_API_TYPES.has(e.obj?.type?.name ?? '');
    const stringMethods = ['length', 'size', 'includes', 'trim', 'toLower', 'toUpper', 'startsWith', 'endsWith', 'splitOn', 'replace'];
    if (isAnyType && !stringMethods.includes(mappedField)) return { tag: 'Sorry' };

    // Check if field exists on known struct type
    if (e.obj?.type?.tag === 'TypeRef') {
      const rawName = e.obj.type.name;
      const stateName = this.classToState.get(rawName) ?? rawName;
      const knownFields = this.structFields.get(stateName) ?? this.structFields.get(rawName) ?? this.structFields.get(rawName + 'State');
      if (knownFields && !knownFields.some(f => f.name === mappedField)) return sorryForType(e.type);
    }

    return { tag: 'FieldAccess', obj, field: mappedField };
  }

  private lowerApp(e: Extract<IRExpr, { tag: 'App' }>, ctx: Effect): LeanExpr {
    // self.method(args) → method self args
    if (e.fn.tag === 'FieldAccess' && e.fn.obj.tag === 'Var' && e.fn.obj.name === 'self') {
      const args = e.args.map(a => this.lowerExprP(a, ctx));
      return { tag: 'App', fn: { tag: 'Var', name: e.fn.field },
               args: [{ tag: 'Var', name: 'self' }, ...args] };
    }

    // Method calls on known types → Lean function-call style
    if (e.fn.tag === 'FieldAccess') {
      const result = this.lowerMethodCall(e, ctx);
      if (result) return result;
    }

    const fn = this.lowerExpr(e.fn, ctx);
    // Unresolved functions → sorry
    if (fn.tag === 'Sorry' || fn.tag === 'Default') return sorryForType(e.type);
    // Node.js module calls → dispatch to stubs
    if (fn.tag === 'Var') {
      const stubMap: Record<string, string> = {
        'path.join': 'TSLean.Stubs.NodePath.join',
        'path.resolve': 'TSLean.Stubs.NodePath.resolve',
        'path.dirname': 'TSLean.Stubs.NodePath.dirname',
        'path.basename': 'TSLean.Stubs.NodePath.basename',
        'path.extname': 'TSLean.Stubs.NodePath.extname',
        'path.relative': 'TSLean.Stubs.NodePath.relative',
        'path.normalize': 'TSLean.Stubs.NodePath.normalize',
        'path.isAbsolute': 'TSLean.Stubs.NodePath.isAbsolute',
        'path.sep': 'TSLean.Stubs.NodePath.sep',
        'fs.readFileSync': 'TSLean.Stubs.NodeFs.readFileSync',
        'fs.writeFileSync': 'TSLean.Stubs.NodeFs.writeFileSync',
        'fs.existsSync': 'TSLean.Stubs.NodeFs.existsSync',
        'fs.mkdirSync': 'TSLean.Stubs.NodeFs.mkdirSync',
        'fs.readdirSync': 'TSLean.Stubs.NodeFs.readdirSync',
        'fs.statSync': 'TSLean.Stubs.NodeFs.statSync',
        'fs.unlinkSync': 'TSLean.Stubs.NodeFs.unlinkSync',
        'process.cwd': 'TSLean.Stubs.Process.cwd',
        'process.exit': 'TSLean.Stubs.Process.exit',
        'process.env': 'TSLean.Stubs.Process.env',
      };
      const stub = stubMap[fn.name];
      if (stub) {
        const args = e.args.map(a => this.lowerExprP(a, ctx));
        const stubFn: LeanExpr = { tag: 'Var', name: stub };
        return args.length === 0 ? stubFn : { tag: 'App', fn: stubFn, args };
      }
      // TS compiler API calls → sorry (no Lean equivalent)
      if (fn.name.startsWith('ts.')) return { tag: 'Sorry' };
      // Remaining unresolved path/fs/process → sorry with tracker
      if (fn.name.startsWith('path.') || fn.name.startsWith('fs.') || fn.name.startsWith('process.')) {
        currentTracker().add({
          location: fn.name, reason: `Node API '${fn.name}' not in stub map`,
          category: 'runtime-api', hint: `add mapping to stubMap in lower.ts`,
        });
        return { tag: 'Sorry' };
      }
    }
    // Storage operations → DOMonad calls against the storage model
    if (fn.tag === 'Var' && fn.name.startsWith('Storage.')) {
      const storageMethod = fn.name.slice('Storage.'.length);
      const args = e.args.map(a => this.lowerExprP(a, ctx));
      return this.lowerStorageOp(storageMethod, args, e.type, ctx);
    }
    // DO context operations → DOMonad calls
    if (fn.tag === 'Var' && fn.name.startsWith('DOCtx.')) {
      const ctxMethod = fn.name.slice('DOCtx.'.length);
      const args = e.args.map(a => this.lowerExprP(a, ctx));
      return this.lowerDOCtxOp(ctxMethod, args, e.type);
    }

    const args = e.args.map(a => this.lowerExprP(a, ctx));
    return args.length === 0 ? fn : { tag: 'App', fn, args };
  }

  private lowerMethodCall(e: Extract<IRExpr, { tag: 'App' }>, ctx: Effect): LeanExpr | null {
    const fa = e.fn as Extract<IRExpr, { tag: 'FieldAccess' }>;
    const obj = this.lowerExprP(fa.obj, ctx);
    const method = fa.field;
    const isStr = fa.obj?.type?.tag === 'String' || (fa.obj?.type?.tag === 'TypeRef' && fa.obj?.type?.name === 'String');
    const isArr = fa.obj?.type?.tag === 'Array';
    const args = e.args.map(a => this.lowerExprP(a, ctx));

    // TS API object methods → sorry
    const isTsApi = fa.obj?.type?.tag === 'TypeRef' && TS_API_TYPES.has(fa.obj?.type?.name ?? '');
    if (isTsApi) return { tag: 'Sorry' };

    // String methods
    if (isStr && method === 'split') return { tag: 'App', fn: { tag: 'FieldAccess', obj, field: 'splitOn' }, args: args.length > 0 ? args : [{ tag: 'Lit', value: '""' }] };
    if (isStr && method === 'replace' && args.length >= 2) return { tag: 'App', fn: { tag: 'FieldAccess', obj, field: 'replace' }, args: [args[0], args[1]] };
    if (isStr && method === 'startsWith' && args.length > 0) return { tag: 'App', fn: { tag: 'FieldAccess', obj, field: 'startsWith' }, args };
    if (isStr && method === 'endsWith' && args.length > 0) return { tag: 'App', fn: { tag: 'FieldAccess', obj, field: 'endsWith' }, args };
    if (isStr && method === 'includes' && args.length > 0) return { tag: 'App', fn: { tag: 'FieldAccess', obj, field: 'includes' }, args };

    // Array methods → function-call style
    if (isArr && method === 'join' && args.length > 0) return { tag: 'App', fn: { tag: 'Var', name: 'String.intercalate' }, args: [args[0], obj] };
    if (isArr && method === 'push' && args.length > 0) return { tag: 'App', fn: { tag: 'Var', name: 'Array.push' }, args: [obj, args[0]] };
    if (isArr && method === 'filter' && args.length > 0) return { tag: 'App', fn: { tag: 'Var', name: 'Array.filter' }, args: [args[0], obj] };
    if (isArr && method === 'map' && args.length > 0) return { tag: 'App', fn: { tag: 'Var', name: 'Array.map' }, args: [args[0], obj] };

    // Collection methods
    const isSet = fa.obj?.type?.tag === 'Set' || (fa.obj?.type?.tag === 'TypeRef' && ['Set', 'AssocSet'].includes(fa.obj?.type?.name ?? ''));
    const collMethods: Record<string, string> = isSet ? {
      'add': 'AssocSet.insert', 'has': 'AssocSet.contains', 'delete': 'AssocSet.erase',
    } : {
      'set': 'AssocMap.insert', 'get': 'AssocMap.find?', 'has': 'AssocMap.contains',
      'delete': 'AssocMap.erase', 'add': 'Array.push', 'keys': 'AssocMap.keys',
      'values': 'AssocMap.values', 'entries': 'AssocMap.toList',
    };
    if (collMethods[method]) {
      return { tag: 'App', fn: { tag: 'Var', name: collMethods[method] },
               args: args.length > 0 ? [obj, ...args] : [obj] };
    }

    return null; // not a recognized method call
  }

  private lowerIf(e: Extract<IRExpr, { tag: 'IfThenElse' }>, ctx: Effect): LeanExpr {
    let cond = this.lowerExpr(e.cond, ctx);
    // Fix non-Bool conditions
    if (e.cond.type?.tag === 'Option' && cond.tag !== 'App') {
      cond = { tag: 'FieldAccess', obj: cond, field: 'isSome' };
    }
    let then_ = this.lowerExpr(e.then, ctx);
    let else_ = this.lowerExpr(e.else_, ctx);

    // In monadic context, ensure branches return the monad type
    if (!isPure(ctx)) {
      if (else_.tag === 'Lit' && else_.value === '()') else_ = { tag: 'Pure', value: { tag: 'Lit', value: '()' } };
    }

    return { tag: 'If', cond, then_, else_ };
  }

  private lowerBinOp(e: Extract<IRExpr, { tag: 'BinOp' }>, ctx: Effect): LeanExpr {
    if (e.op === 'NullCoalesce') {
      const l = this.lowerExprP(e.left, ctx);
      const r = this.lowerExprP(e.right, ctx);
      // Sorry/Default LHS → use RHS directly (graceful degradation)
      if (l.tag === 'Default' || l.tag === 'Sorry' || l.tag === 'None') return r;
      return { tag: 'App', fn: { tag: 'Var', name: 'Option.getD' }, args: [l, r] };
    }
    // Equality with none → .isNone/.isSome
    if (e.op === 'Eq' && (e.right.tag === 'LitNull' || (e.right.tag === 'Var' && e.right.name === 'none'))) {
      return { tag: 'FieldAccess', obj: this.lowerExprP(e.left, ctx), field: 'isNone' };
    }
    if (e.op === 'Ne' && (e.right.tag === 'LitNull' || (e.right.tag === 'Var' && e.right.name === 'none'))) {
      return { tag: 'FieldAccess', obj: this.lowerExprP(e.left, ctx), field: 'isSome' };
    }
    // String interpolation for Concat chains
    if (e.op === 'Concat' || (e.op === 'Add' && e.left?.type?.tag === 'String')) {
      const interp = this.trySInterp(e, ctx);
      if (interp) return interp;
    }

    const l = this.lowerExprP(e.left, ctx);
    const r = this.lowerExprP(e.right, ctx);
    const op = translateBinOp(e.op, e.left?.type ?? { tag: 'Unit' });
    return { tag: 'BinOp', op, left: l, right: r };
  }

  private trySInterp(e: IRExpr, ctx: Effect): LeanExpr | null {
    const parts = flattenConcat(e);
    if (!parts) return null;
    const hasInterp = parts.some(p => p.tag !== 'LitString');
    const hasLiteral = parts.some(p => p.tag === 'LitString' && p.value !== '');
    if (!hasInterp || !hasLiteral) return null;
    if (!parts.every(isSafeInterp)) return null;
    // Check for unsafe chars in string parts
    if (parts.some(p => p.tag === 'LitString' && /[{}"\\]/.test(p.value))) return null;

    const sinterpParts: SInterpPart[] = parts.map(p => {
      if (p.tag === 'LitString') return { tag: 'Str' as const, value: p.value };
      return { tag: 'Expr' as const, expr: this.lowerExpr(p, ctx) };
    });
    return { tag: 'SInterp', parts: sinterpParts };
  }

  private lowerAssign(e: Extract<IRExpr, { tag: 'Assign' }>, ctx: Effect): LeanExpr {
    const val = this.lowerExpr(e.value, ctx);
    if (e.target.tag === 'FieldAccess' && e.target.obj.tag === 'Var' && e.target.obj.name === 'self') {
      let field = e.target.field;
      if (field.startsWith('_') && field.length > 1 && /[a-zA-Z]/.test(field[1]))
        field = field.slice(1);
      return {
        tag: 'Modify',
        fn: { tag: 'Lam', params: ['s'], body: { tag: 'StructUpdate', base: { tag: 'Var', name: 's' }, fields: [{ name: field, value: val }] } },
      };
    }
    if (e.target.tag === 'Var') {
      // Variable reassignment → let rebinding (Lean is immutable, this shadows the old value)
      return { tag: 'Let', name: e.target.name, value: val, body: { tag: 'Lit', value: '()' } };
    }
    // FieldAccess on a non-self variable → struct update via let rebinding
    if (e.target.tag === 'FieldAccess' && e.target.obj.tag === 'Var') {
      const objName = e.target.obj.name;
      let field = e.target.field;
      if (field.startsWith('_') && field.length > 1 && /[a-zA-Z]/.test(field[1]))
        field = field.slice(1);
      return {
        tag: 'Let', name: objName,
        value: { tag: 'StructUpdate', base: { tag: 'Var', name: objName },
                 fields: [{ name: field, value: val }] },
        body: { tag: 'Lit', value: '()' },
      };
    }
    // IndexAccess → Array.set or AssocMap.insert
    if (e.target.tag === 'IndexAccess') {
      const obj = this.lowerExpr(e.target.obj, ctx);
      const idx = this.lowerExpr(e.target.index, ctx);
      const objType = e.target.obj.type;
      if (objType?.tag === 'Array') {
        return { tag: 'Let', name: '_arr', value: { tag: 'App', fn: { tag: 'Var', name: 'Array.set' }, args: [obj, idx, val] }, body: { tag: 'Lit', value: '()' } };
      }
      if (objType?.tag === 'Map' || (objType?.tag === 'TypeRef' && (objType.name === 'Map' || objType.name === 'AssocMap'))) {
        return { tag: 'Let', name: '_map', value: { tag: 'App', fn: { tag: 'Var', name: 'AssocMap.insert' }, args: [obj, idx, val] }, body: { tag: 'Lit', value: '()' } };
      }
      // Generic index assignment → sorry with context
      return { tag: 'Sorry', reason: `assign: IndexAccess on ${objType?.tag ?? 'unknown'}` };
    }
    return { tag: 'Sorry', reason: `assign: ${e.target.tag}` };
  }

  private lowerCast(e: Extract<IRExpr, { tag: 'Cast' }>, ctx: Effect): LeanExpr {
    const from = e.expr?.type;
    const to = e.targetType;
    if (to.tag === 'Tuple' && e.expr.tag === 'ArrayLit') {
      return { tag: 'TupleLit', elems: e.expr.elems.map(x => this.lowerExpr(x, ctx)) };
    }
    const inner = this.lowerExpr(e.expr, ctx);
    if (to.tag === 'TypeRef' && from.tag === 'String') {
      return { tag: 'App', fn: { tag: 'Var', name: `${to.name}.mk` }, args: [inner] };
    }
    if (from.tag === 'TypeRef' && to.tag === 'String') {
      return { tag: 'FieldAccess', obj: inner, field: 'val' };
    }
    return inner;
  }

  private lowerStructLit(e: Extract<IRExpr, { tag: 'StructLit' }>, ctx: Effect): LeanExpr {
    // Anonymous object literals (type collapsed to String/Any/TSAny) → AssocMap construction
    if (e.type?.tag === 'String' || (e.type?.tag === 'TypeRef' && (e.type.name === 'Any' || e.type.name === 'TSAny'))) {
      const realFields = e.fields.filter(f => !f.name.startsWith('_spread') && !f.name.startsWith('_computed'));
      if (realFields.length > 0) {
        // Build AssocMap from fields: #[("key1", val1), ("key2", val2)]
        const pairs: LeanExpr[] = realFields.map(f => ({
          tag: 'TupleLit' as const,
          elems: [{ tag: 'Lit' as const, value: `"${f.name}"` }, this.lowerExpr(f.value, ctx)],
        }));
        return { tag: 'App', fn: { tag: 'Var', name: 'AssocMap.ofList' },
                 args: [{ tag: 'ArrayLit', elems: pairs }] };
      }
      return { tag: 'Default' };
    }
    // Large anonymous object literals with nested structs of unknown type → AssocMap
    const hasNestedStructs = e.fields.some(f => f.value?.tag === 'StructLit');
    if (hasNestedStructs && e.fields.length > 5 && !this.structFields.has(e.typeName ?? '')) {
      const realFields = e.fields.filter(f => !f.name.startsWith('_spread') && !f.name.startsWith('_computed'));
      if (realFields.length > 0) {
        const pairs: LeanExpr[] = realFields.map(f => ({
          tag: 'TupleLit' as const,
          elems: [{ tag: 'Lit' as const, value: `"${f.name}"` }, this.lowerExpr(f.value, ctx)],
        }));
        return { tag: 'App', fn: { tag: 'Var', name: 'AssocMap.ofList' },
                 args: [{ tag: 'ArrayLit', elems: pairs }] };
      }
      return { tag: 'Default' };
    }
    // Detect struct-update pattern: _base field + other fields
    const baseField = e.fields.find(f => f.name === '_base');
    const realFields = e.fields.filter(f => f.name !== '_base' && f.name !== '_spread' && !f.name.startsWith('_computed'));
    if (baseField && realFields.length > 0) {
      const baseType = baseField.value?.type;
      if (baseType?.tag === 'String' || (baseType?.tag === 'TypeRef' && (baseType.name === 'Any' || baseType.name === 'TSAny'))) {
        return sorryForType(e.type);
      }
      const base = this.lowerExpr(baseField.value, ctx);
      const fields = realFields.map(f => ({ name: f.name, value: this.lowerExpr(f.value, ctx) }));
      return { tag: 'StructUpdate', base, fields };
    }
    const fields = e.fields
      .filter(f => f.name !== '_spread' && !f.name.startsWith('_computed'))
      .map(f => ({ name: f.name, value: this.lowerExpr(f.value, ctx) }));
    if (fields.length === 0) return { tag: 'Default' };
    return { tag: 'StructLit', fields };
  }

  private lowerStructUpdate(e: Extract<IRExpr, { tag: 'StructUpdate' }>, ctx: Effect): LeanExpr {
    const base = this.lowerExpr(e.base, ctx);
    const realFields = e.fields.filter(f => !f.name.startsWith('_computed'));
    if (realFields.length === 0) return base;
    const fields = realFields.map(f => ({ name: f.name, value: this.lowerExpr(f.value, ctx) }));
    return { tag: 'StructUpdate', base, fields };
  }

  private lowerDoBlock(stmts: DoStmt[], ctx: Effect): LeanExpr {
    const leanStmts: LeanExpr[] = [];
    for (const s of stmts) {
      switch (s.tag) {
        case 'DoBind':
          leanStmts.push({ tag: 'Bind', name: s.name, value: this.lowerExpr(s.expr, ctx),
                          body: { tag: 'Lit', value: '()' } }); // body filled by Seq
          break;
        case 'DoLet':
          leanStmts.push({ tag: 'Let', name: s.name, value: this.lowerExpr(s.value, ctx),
                          body: { tag: 'Lit', value: '()' } });
          break;
        case 'DoExpr':
          leanStmts.push(this.lowerExpr(s.expr, ctx));
          break;
        case 'DoReturn':
          leanStmts.push({ tag: 'Return', value: this.lowerExpr(s.value, ctx) });
          break;
      }
    }
    return { tag: 'Do', body: { tag: 'Seq', stmts: leanStmts } };
  }

  private chainSequentialIfs(stmts: IRExpr[]): IRExpr[] {
    const result: IRExpr[] = [];
    let i = 0;
    while (i < stmts.length) {
      const s = stmts[i];
      if (s.tag === 'IfThenElse' && isEmptyElse(s.else_) && i + 1 < stmts.length) {
        const chain: Array<{ cond: IRExpr; then: IRExpr }> = [{ cond: s.cond, then: s.then }];
        i++;
        while (i < stmts.length && stmts[i].tag === 'IfThenElse' && isEmptyElse((stmts[i] as any).else_)) {
          const next = stmts[i] as Extract<IRExpr, { tag: 'IfThenElse' }>;
          chain.push({ cond: next.cond, then: next.then });
          i++;
        }
        const finalElse: IRExpr = i < stmts.length ? stmts[i] : { tag: 'LitUnit', type: s.type, effect: s.effect };
        if (i < stmts.length) i++;
        let chained: IRExpr = finalElse;
        for (let j = chain.length - 1; j >= 0; j--) {
          chained = { tag: 'IfThenElse', cond: chain[j].cond, then: chain[j].then, else_: chained, type: s.type, effect: s.effect };
        }
        result.push(chained);
      } else {
        result.push(s);
        i++;
      }
    }
    return result;
  }

  // ─── Pattern lowering ───────────────────────────────────────────────────────

  lowerPat(p: IRPattern): LeanPat {
    switch (p.tag) {
      case 'PVar': return { tag: 'PVar', name: p.name };
      case 'PWild': return { tag: 'PWild' };
      case 'PLit': return { tag: 'PLit', value: typeof p.value === 'string' ? JSON.stringify(p.value) : String(p.value) };
      case 'PString': return { tag: 'PLit', value: JSON.stringify(p.value) };
      case 'PNone': return { tag: 'PNone' };
      case 'PSome': return { tag: 'PSome', inner: this.lowerPat(p.inner) };
      case 'PCtor': {
        const localName = p.ctor.includes('.') ? p.ctor.split('.').pop()! : p.ctor;
        return { tag: 'PCtor', name: localName, args: p.args.map(a => this.lowerPat(a)) };
      }
      case 'PTuple': return { tag: 'PTuple', elems: p.elems.map(x => this.lowerPat(x)) };
      case 'PStruct': return { tag: 'PStruct', fields: p.fields.map(f => ({ name: f.name, pat: this.lowerPat(f.pattern) })) };
      case 'POr': return { tag: 'POr', pats: p.pats.map(x => this.lowerPat(x)) };
      case 'PAs': return { tag: 'PAs', pattern: this.lowerPat(p.pattern), name: p.name };
    }
  }

  // ─── Helpers ────────────────────────────────────────────────────────────────

  private isPureValue(e: LeanExpr): boolean {
    return e.tag === 'ArrayLit' || e.tag === 'StructLit' || e.tag === 'Default' ||
           e.tag === 'Sorry' || e.tag === 'Lit' || e.tag === 'None' ||
           (e.tag === 'Var' && !e.name.includes('.'));
  }

  private exprHasBinds(e: LeanExpr): boolean {
    if (e.tag === 'Bind') return true;
    if (e.tag === 'Seq') return e.stmts.some(s => this.exprHasBinds(s));
    if (e.tag === 'Let') return this.exprHasBinds(e.body);
    return false;
  }

  private printTyInline(t: LeanTy): string {
    return printTyStr(t);
  }

  private printExprInline(e: LeanExpr): string {
    return printExprStr(e, 0);
  }

  // ─── Storage operation lowering ───────────────────────────────────────────────
  // Maps DO storage method calls to Lean DurableObjects.Model operations.
  // Storage is modeled as AssocMap StorageKey StorageValue in the DOMonad.

  private lowerStorageOp(method: string, args: LeanExpr[], ty: IRType, ctx: Effect): LeanExpr {
    // Storage operations are lowered to Lean DurableObjects.Model calls.
    // For reads: Storage.get/keys on a storage handle.
    // For writes: modify fun s => { s with storage := Storage.put/delete s.storage ... }
    switch (method) {
      case 'get':
        // Storage.get key → sorry-free structural call
        return args.length > 0
          ? { tag: 'App', fn: { tag: 'Var', name: 'Storage.get' }, args }
          : { tag: 'Sorry' };
      case 'put':
        // Storage.put key value → modify fun s => { s with storage := Storage.put s.storage key value }
        if (args.length >= 2) {
          return {
            tag: 'Modify', fn: {
              tag: 'Lam', params: ['s'], body: {
                tag: 'StructUpdate', base: { tag: 'Var', name: 's' },
                fields: [{ name: 'storage', value: { tag: 'App', fn: { tag: 'Var', name: 'Storage.put' }, args: [{ tag: 'FieldAccess', obj: { tag: 'Var', name: 's' }, field: 'storage' }, ...args] } }]
              }
            }
          };
        }
        return { tag: 'Sorry' };
      case 'delete':
        return args.length > 0
          ? { tag: 'Modify', fn: { tag: 'Lam', params: ['s'], body: { tag: 'StructUpdate', base: { tag: 'Var', name: 's' }, fields: [{ name: 'storage', value: { tag: 'App', fn: { tag: 'Var', name: 'Storage.delete' }, args: [{ tag: 'FieldAccess', obj: { tag: 'Var', name: 's' }, field: 'storage' }, ...args] } }] } } }
          : { tag: 'Sorry' };
      case 'deleteAll':
        return { tag: 'Modify', fn: { tag: 'Lam', params: ['s'], body: { tag: 'StructUpdate', base: { tag: 'Var', name: 's' }, fields: [{ name: 'storage', value: { tag: 'Var', name: 'Storage.clear' } }] } } };
      case 'list':
        return { tag: 'App', fn: { tag: 'Var', name: 'Storage.keys' }, args };
      case 'getAlarm':
        // getAlarm → AlarmState.next
        return { tag: 'App', fn: { tag: 'Var', name: 'AlarmState.next' }, args };
      case 'setAlarm':
        // setAlarm(t) → AlarmState.schedule
        return args.length > 0
          ? { tag: 'App', fn: { tag: 'Var', name: 'AlarmState.schedule' }, args }
          : { tag: 'Sorry' };
      case 'deleteAlarm':
        return { tag: 'Var', name: 'AlarmState.empty' };
      case 'transaction':
        // Storage.transaction(fn) → modify with Transaction model
        if (args.length > 0) {
          return { tag: 'Modify', fn: {
            tag: 'Lam', params: ['s'], body: {
              tag: 'StructUpdate', base: { tag: 'Var', name: 's' },
              fields: [{ name: 'storage', value: {
                tag: 'App', fn: { tag: 'Var', name: 'Transaction.commit' },
                args: [{ tag: 'App', fn: args[0], args: [{ tag: 'Var', name: 'Transaction.empty' }] }, { tag: 'FieldAccess', obj: { tag: 'Var', name: 's' }, field: 'storage' }]
              } }]
            }
          } };
        }
        return { tag: 'Sorry' };
      default:
        currentTracker().add({ location: `Storage.${method}`, reason: `Storage method '${method}' not mapped`, category: 'runtime-api', hint: 'add mapping in lowerStorageOp' });
        return { tag: 'Sorry' };
    }
  }

  // ─── DO context operation lowering ────────────────────────────────────────────
  // Maps DurableObjectState method calls to Lean equivalents.

  private lowerDOCtxOp(method: string, args: LeanExpr[], ty: IRType): LeanExpr {
    switch (method) {
      case 'acceptWebSocket':
        // DOCtx.acceptWebSocket(ws, tags?) → openConnWithTags / openConn
        return args.length > 1
          ? { tag: 'App', fn: { tag: 'Var', name: 'openConnWithTags' }, args }
          : { tag: 'App', fn: { tag: 'Var', name: 'openConn' }, args };
      case 'getWebSockets':
        // DOCtx.getWebSockets(tag?) → getByTag / allConnections
        return args.length > 0
          ? { tag: 'App', fn: { tag: 'Var', name: 'getByTag' }, args }
          : { tag: 'App', fn: { tag: 'Var', name: 'allConnections' }, args: [] };
      case 'getTags':
        return { tag: 'App', fn: { tag: 'Var', name: 'getTags' }, args };
      case 'blockConcurrencyWhile':
        // blockConcurrencyWhile(cb) → cb executed during init (semantically: just run cb)
        return args.length > 0
          ? { tag: 'App', fn: args[0], args: [{ tag: 'Lit', value: '()' }] }
          : { tag: 'Sorry' };
      case 'waitUntil':
        // waitUntil is fire-and-forget; in the pure model, just evaluate the promise
        return args.length > 0 ? args[0] : { tag: 'Lit', value: '()' };
      case 'setWebSocketAutoResponse':
        return { tag: 'App', fn: { tag: 'Var', name: 'setAutoResponse' }, args };
      case 'getWebSocketAutoResponse':
        return { tag: 'Var', name: 'getAutoResponse' };
      case 'setHibernatableWebSocketEventTimeout':
        return { tag: 'Lit', value: '()' }; // no-op in pure model
      case 'getHibernatableWebSocketEventTimeout':
        return { tag: 'Lit', value: '0' };
      default:
        return { tag: 'Sorry' };
    }
  }
}

// ─── Standalone helpers ─────────────────────────────────────────────────────────

function sorryForType(t?: IRType): LeanExpr {
  if (!t) return { tag: 'Sorry' };
  switch (t.tag) {
    case 'Bool': return { tag: 'Sorry', ty: { tag: 'TyName', name: 'Bool' } };
    case 'String': return { tag: 'Sorry', ty: { tag: 'TyName', name: 'String' } };
    case 'Nat': return { tag: 'Sorry', ty: { tag: 'TyName', name: 'Nat' } };
    case 'Int': return { tag: 'Sorry', ty: { tag: 'TyName', name: 'Int' } };
    case 'Float': return { tag: 'Sorry', ty: { tag: 'TyName', name: 'Float' } };
    case 'Unit': return { tag: 'Lit', value: '()' };
    case 'Option': return { tag: 'None' };
    case 'Array': return { tag: 'ArrayLit', elems: [] };
    case 'TypeRef': return { tag: 'Sorry', ty: { tag: 'TyName', name: t.name } };
    default: return { tag: 'Sorry' };
  }
}

function defaultForType(t: IRType): LeanExpr {
  switch (t.tag) {
    case 'Nat': return { tag: 'Lit', value: '0' };
    case 'Int': return { tag: 'Lit', value: '0' };
    case 'Float': return { tag: 'TypeAnnot', expr: { tag: 'Lit', value: '0' }, ty: { tag: 'TyName', name: 'Float' } };
    case 'String': return { tag: 'Lit', value: '""' };
    case 'Bool': return { tag: 'Lit', value: 'false' };
    case 'Unit': return { tag: 'Lit', value: '()' };
    case 'Array': return { tag: 'ArrayLit', elems: [] };
    case 'Option': return { tag: 'None' };
    default: return { tag: 'Default' };
  }
}

function needsParens(e: IRExpr): boolean {
  return e.tag === 'App' || e.tag === 'BinOp' || e.tag === 'UnOp' ||
         e.tag === 'IfThenElse' || e.tag === 'Lambda' || e.tag === 'Let' ||
         e.tag === 'Bind' || e.tag === 'TryCatch' || e.tag === 'Match' ||
         e.tag === 'LitFloat';
}

function isEmptyElse(e: IRExpr): boolean {
  if (e.tag === 'LitUnit') return true;
  if (e.tag === 'Pure_' && e.value.tag === 'LitUnit') return true;
  return false;
}

function fixStateEffect(eff: Effect, params: IRParam[]): Effect {
  const selfParam = params.find(p => p.name === 'self');
  if (!selfParam) return eff;
  if (eff.tag === 'State' && eff.stateType.tag === 'Unit')
    return { tag: 'State', stateType: selfParam.type };
  if (eff.tag === 'Combined')
    return { tag: 'Combined', effects: eff.effects.map(e =>
      e.tag === 'State' && e.stateType.tag === 'Unit' ? { tag: 'State' as const, stateType: selfParam.type } : e) };
  return eff;
}

function bodyContainsVarRef(expr: IRExpr, name: string): boolean {
  function check(e: IRExpr): boolean {
    if (e.tag === 'Var' && e.name === name) return true;
    switch (e.tag) {
      case 'App': return check(e.fn) || e.args.some(check);
      case 'Lambda': return check(e.body);
      case 'Let': return check(e.value) || check(e.body);
      case 'Bind': return check(e.monad) || check(e.body);
      case 'IfThenElse': return check(e.cond) || check(e.then) || check(e.else_);
      case 'Match': return check(e.scrutinee) || e.cases.some(c => check(c.body));
      case 'Sequence': return e.stmts.some(check);
      case 'BinOp': return check(e.left) || check(e.right);
      case 'UnOp': return check(e.operand);
      case 'FieldAccess': return check(e.obj);
      case 'IndexAccess': return check(e.obj) || check(e.index);
      case 'Assign': return check(e.target) || check(e.value);
      case 'TryCatch': return check(e.body) || check(e.handler);
      case 'Throw': return check(e.error);
      case 'Return': return check(e.value);
      case 'Await': return check(e.expr);
      case 'Cast': return check(e.expr);
      case 'CtorApp': return e.args.some(check);
      case 'ArrayLit': return e.elems.some(check);
      case 'TupleLit': return e.elems.some(check);
      case 'StructLit': return e.fields.some(f => check(f.value));
      default: return false;
    }
  }
  return check(expr);
}

function bodyContainsAnyVarRef(expr: IRExpr, names: Set<string>, selfName: string): boolean {
  function check(e: IRExpr): boolean {
    if (!e || typeof e !== 'object') return false;
    if (e.tag === 'Var' && names.has(e.name) && e.name !== selfName) return true;
    for (const v of Object.values(e)) {
      if (v && typeof v === 'object') {
        if (Array.isArray(v)) {
          for (const item of v) {
            if (item && typeof item === 'object' && 'tag' in item && check(item as IRExpr)) return true;
            if (item && typeof item === 'object') {
              for (const sub of Object.values(item)) {
                if (sub && typeof sub === 'object' && 'tag' in (sub as any) && check(sub as IRExpr)) return true;
              }
            }
          }
        } else if ('tag' in v) {
          if (check(v as IRExpr)) return true;
        }
      }
    }
    return false;
  }
  return check(expr);
}

function collectFieldAccesses(expr: IRExpr, varName: string): Map<string, IRType> {
  const fields = new Map<string, IRType>();
  const methodCalls = new Set<string>();
  function walk(e: IRExpr): void {
    if (!e || typeof e !== 'object') return;
    if (e.tag === 'App' && e.fn.tag === 'FieldAccess' && e.fn.obj.tag === 'Var' && e.fn.obj.name === varName)
      methodCalls.add(e.fn.field);
    if (e.tag === 'FieldAccess' && e.obj.tag === 'Var' && e.obj.name === varName)
      fields.set(e.field, e.type);
    for (const v of Object.values(e)) {
      if (v && typeof v === 'object') {
        if (Array.isArray(v)) {
          for (const item of v) {
            if (item && typeof item === 'object' && 'tag' in item) walk(item as IRExpr);
            if (item && typeof item === 'object') {
              for (const sub of Object.values(item)) {
                if (sub && typeof sub === 'object' && 'tag' in (sub as any)) walk(sub as IRExpr);
              }
            }
          }
        } else if ('tag' in v) walk(v as IRExpr);
      }
    }
  }
  walk(expr);
  for (const m of methodCalls) fields.delete(m);
  return fields;
}

function flattenConcat(e: IRExpr): IRExpr[] | null {
  if (e.tag === 'LitString') return [e];
  if (e.tag === 'BinOp' && (e.op === 'Concat' || (e.op === 'Add' && e.left?.type?.tag === 'String'))) {
    const left = flattenConcat(e.left);
    const right = flattenConcat(e.right);
    if (!left || !right) return null;
    return [...left, ...right];
  }
  if (isSafeInterp(e)) return [e];
  return null;
}

function isSafeInterp(e: IRExpr): boolean {
  switch (e.tag) {
    case 'LitString': case 'LitNat': case 'LitFloat': case 'LitBool': case 'Var': return true;
    case 'FieldAccess': return isSafeInterp(e.obj);
    case 'Cast': return isSafeInterp(e.expr);
    default: return false;
  }
}

// ─── Constraint → type class mapping ────────────────────────────────────────────

/**
 * Map a TypeScript generic constraint (IRType) to Lean type class names.
 *
 * Tier 1 (primitive): string→ToString, number→OfNat/OfScientific, boolean→DecidableEq
 * Tier 2 (named interface/class): Comparable→Comparable, Serializable→Serializable
 * Tier 3 (structural): { name: string } → HasField "name" String (deferred)
 */
function constraintToTypeClasses(constraint: IRType): string[] {
  switch (constraint.tag) {
    case 'String':  return ['ToString'];
    case 'Nat':     return ['OfNat'];
    case 'Int':     return ['OfNat'];
    case 'Float':   return ['OfScientific'];
    case 'Bool':    return ['DecidableEq'];
    case 'TypeRef':
      // Named interface/class constraint: <T extends Comparable> → [Comparable T]
      return [constraint.name];
    case 'TypeVar':
      // <T extends U> where U is another type param — not directly expressible
      return [];
    default:
      return [];
  }
}


