-- Auto-generated by ts-lean-transpiler
-- Source: /workspace/tslean/src/codegen/v2.ts

import TSLean.Runtime.Basic
import TSLean.Runtime.Coercions
import TSLean.Runtime.Monad

open TSLean

namespace TSLean.Generated.V2

structure CodegenOptions where
  mk ::
  selfHost : Option Bool
  baseName : Option (Option String)
  deriving Repr, BEq, Inhabited

/-- Generate Lean 4 source code from an IR module using the V2 pipeline. -/
def generateLeanV2 (mod : IRModule) (opts : Option CodegenOptions) : StateT Unit IO String :=
  do
    let leanFile : LeanFile := lowerModule mod
    if opts.bind (fun _oc => some _oc.selfHost) then
      let leanFile := applySelfHostTransforms leanFile (Option.getD opts.baseName mod.name)
      ()
    else
      pure printFile leanFile

def NS_MAP : String :=
  { 'TSLean.Generated.Types' := "TSLean.Generated.SelfHost.ir_types", 'TSLean.Generated.EffectsIndex' := "TSLean.Generated.SelfHost.EffectsIndex", 'TSLean.Generated.StdlibIndex' := "TSLean.Generated.SelfHost.StdlibIndex", 'TSLean.Generated.TypemapIndex' := "TSLean.Generated.SelfHost.TypemapIndex", 'TSLean.Generated.RewriteIndex' := "TSLean.Generated.SelfHost.RewriteIndex", 'TSLean.Generated.VerificationIndex' := "TSLean.Generated.SelfHost.VerificationIndex", 'TSLean.Generated.DoModelAmbient' := "TSLean.Generated.SelfHost.DoModelAmbient", 'TSLean.Generated.CodegenIndex' := "TSLean.Generated.SelfHost.CodegenIndex", 'TSLean.Generated.ParserIndex' := "TSLean.Generated.SelfHost.ParserIndex", 'TSLean.Generated.ProjectIndex' := "TSLean.Generated.SelfHost.ProjectIndex", 'TSLean.Generated.SrcCli' := "TSLean.Generated.SelfHost.SrcCli" }

def IMPORT_MAP : String :=
  { 'TSLean.Generated.Ir.Types' := "TSLean.Generated.SelfHost.ir_types", 'TSLean.Generated.Effects.Index' := "TSLean.Generated.SelfHost.effects_index", 'TSLean.Generated.Stdlib.Index' := "TSLean.Generated.SelfHost.stdlib_index", 'TSLean.Generated.Typemap.Index' := "TSLean.Generated.SelfHost.typemap_index", 'TSLean.Generated.DoModel.Ambient' := "TSLean.Generated.SelfHost.DoModel_Ambient", 'TSLean.Generated.Codegen.Index' := "TSLean.Generated.SelfHost.codegen_index", 'TSLean.Generated.Parser.Index' := "TSLean.Generated.SelfHost.parser_index", 'TSLean.Generated.Rewrite.Index' := "TSLean.Generated.SelfHost.rewrite_index", 'TSLean.Generated.Verification.Index' := "TSLean.Generated.SelfHost.verification_index", 'TSLean.Generated.Project.Index' := "TSLean.Generated.SelfHost.project_index" }

def applySelfHostTransforms (file : LeanFile) (baseName : String) : LeanFile :=
  do
    let newDecls : Array LeanDecl := #[]
    let isIrTypes : Bool := baseName == "ir_types"
    Array.forM file.decls (fun d => if d.tag == "Import" then let mapped : String := IMPORT_MAP.getD d.module default; if mapped then Array.push newDecls { tag := "Import", module := mapped } else Array.push newDecls d else if d.tag == "Open" then let hasTypes : Bool := newDecls.any (fun x => (x.tag == "Import") && (x.module.includes "ir_types")); if hasTypes then Array.push newDecls { tag := "Open", namespaces := #[d.namespaces, "TSLean.Generated.Types"] } else Array.push newDecls d else if d.tag == "Namespace" then let mappedName : String := Option.getD NS_MAP.getD d.name default ("TSLean.Generated.SelfHost." ++ (capitalize baseName)); Array.push newDecls { d with name := mappedName } else Array.push newDecls d)
    if !isIrTypes then
      let firstNonImport : Float := newDecls.findIndex (fun d => (d.tag != "Import") && (d.tag != "Blank"))
      let preludeImports : Array LeanDecl := #[{ tag := "Import", module := "TSLean.Generated.SelfHost.Prelude" }]
      if !(newDecls.any (fun d => (d.tag == "Import") && (d.module.includes "ir_types"))) then
        Array.push preludeImports { tag := "Import", module := "TSLean.Generated.SelfHost.ir_types" }
      else
        newDecls.splice (if firstNonImport >= 0 then firstNonImport else 0) 0 preludeImports
    else
      { file with decls := newDecls }

def capitalize (s : String) : String := (s.charAt 0.toUpper) ++ (s.extract 1)

end TSLean.Generated.V2