-- Auto-generated by ts-lean-transpiler
-- Source: /workspace/tslean/src/cli.ts

import TSLean.Generated.SelfHost.Prelude
import TSLean.Generated.SelfHost.Prelude
import TSLean.Generated.SelfHost.ir_types
import TSLean.Runtime.Basic
import TSLean.Runtime.Coercions
import TSLean.Runtime.Monad

open TSLean TSLean.Generated.Types

namespace TSLean.Generated.SelfHost.SrcCli

-- // ─── Argument parsing ─────────────────────────────────────────────────────────
structure Args where
  mk ::
  mode : String
  input : String
  output : String
  verify : Bool
  ns : String
  deriving Repr, BEq, Inhabited

def parseArgs (argv : Array String) : StateT Unit IO Args :=
  do
    let args := sorry
    let mode := "single"
    let input := ""
    do
      let rec _loop_916 := fun i => do
        if i < args.size then do
            let a := args.getD i default
            _loop_916 (i + 1)
        else
          pure ()
      do
        if !input then do
            sorry
            sorry
        else do
            if !output then
              let output := if mode == "single" then
                input.replace "/\\.ts$/" ".lean"
              else
                (input.replace "/\\/$/" "") ++ "_lean"
            else
              pure { mode := mode, input := input, output := output, verify := verify, ns := ns }

-- // ─── Single file ──────────────────────────────────────────────────────────────
def single (opts : Args) : StateT Unit IO Unit :=
  do
    let input := opts.input
    let output := opts.output
    let verify : Bool := opts.verify
    do
      if !(sorry) then do
          sorry
          sorry
      else
        tryCatch (let src := sorry
        let mod := default /- cross-file: parseFile -/
        let rw := default /- cross-file: rewriteModule -/
        let code := default /- cross-file: generateLean -/
        do
          if verify then
            let leanCode := default /- cross-file: generateVerification -/.leanCode
            let obligations : Array ProofObligation := default /- cross-file: generateVerification -/.obligations
            do
              if leanCode then
                let code := s!"{code}

-- Verification obligations
{leanCode}"
              else
                if obligations.size then
                  sorry
                else
                  pure ()
          else do
              sorry
              do
                sorry
                sorry) (fun err => do
          sorry
          do
            if default.getD "DEBUG" default then
              sorry
            else
              sorry)

-- // ─── Project mode ─────────────────────────────────────────────────────────────
def project (opts : Args) : Unit :=
  default

def opts : Args := parseArgs default

end TSLean.Generated.SelfHost.SrcCli