-- Auto-generated by ts-lean-transpiler
-- Source: /workspace/tslean/src/typemap/index.ts

import TSLean.Generated.SelfHost.Prelude
import TSLean.Generated.SelfHost.Prelude
import TSLean.Generated.SelfHost.ir_types
import TSLean.Runtime.Basic
import TSLean.Runtime.Coercions
import TSLean.Stdlib.HashMap

open TSLean TSLean.Generated.Types TSLean.Stdlib.HashMap

namespace TSLean.Generated.SelfHost.TypemapIndex

def MAX_TYPE_DEPTH : Float := 20

def FALLBACK_TYPE_VAR : String := "α"

def TS_ANON_TYPE : String := "__type"

def DISCRIMINANT_FIELDS : Array String := #["kind", "type", "tag", "ok", "hasValue", "_type"]

/-- Map a TypeScript compiler type to an IR type. Handles primitives, unions, intersections, arrays, tuples, object types, generic references, conditional types, and branded newtypes. -/
partial def mapType (t : Type) (checker : String) (depth : Float := 0) : String :=
  if depth > MAX_TYPE_DEPTH then
    TyRef "TSAny"
  else
    let f : TypeFlags := t.flags
    if f &&& ts.TypeFlags.String then
      TyString
    else
      if f &&& ts.TypeFlags.Number then
        TyFloat
      else
        if f &&& ts.TypeFlags.Boolean then
          TyBool
        else
          if f &&& ts.TypeFlags.Undefined then
            TyOption TyUnit
          else
            if f &&& ts.TypeFlags.Null then
              TyOption TyUnit
            else
              if f &&& ts.TypeFlags.Void then
                TyUnit
              else
                if f &&& ts.TypeFlags.Never then
                  TyNever
                else
                  if f &&& ts.TypeFlags.Any then
                    TyRef "TSAny"
                  else
                    if f &&& ts.TypeFlags.Unknown then
                      TyRef "TSAny"
                    else
                      if f &&& ts.TypeFlags.BigInt then
                        TyInt
                      else
                        if f &&& ts.TypeFlags.StringLiteral then
                          TyString
                        else
                          if f &&& ts.TypeFlags.NumberLiteral then
                            TyFloat
                          else
                            if f &&& ts.TypeFlags.BooleanLiteral then
                              TyBool
                            else
                              if f &&& ts.TypeFlags.TypeParameter then
                                TyVar (Option.getD (sorry) FALLBACK_TYPE_VAR)
                              else
                                if sorry then
                                  mapUnion t checker depth
                                else
                                  if sorry then
                                    mapIntersection t checker depth
                                  else
                                    if sorry then
                                      let elem : Type := (sorry).getD 0 default
                                      TyArray (if elem then
                                        default /- cross-file: mapType -/
                                      else
                                        TyRef "TSAny")
                                    else
                                      if sorry then
                                        let args : Array Type := sorry
                                        TyTuple (Array.map (fun a => default /- cross-file: mapType -/) args)
                                      else
                                        if f &&& ts.TypeFlags.Object then
                                          mapObject t checker depth
                                        else
                                          if f &&& ts.TypeFlags.Conditional then
                                            let c : ConditionalType := t
                                            let resolved : Option Type := default
                                            default /- cross-file: mapType -/
                                          else
                                            if f &&& ts.TypeFlags.Index then
                                              TyString
                                            else
                                              TyRef (sorry)

-- // ─── Union types ────────────────────────────────────────────────────────────────
def mapUnion (t : UnionType) (checker : String) (depth : Float) : String :=
  let types : Array Type := t.types
  let withoutNil : Array Type := Array.filter (fun x => !(x.flags &&& (ts.TypeFlags.Undefined ||| ts.TypeFlags.Null))) types
  if (withoutNil.size == 1) && (withoutNil.size < types.size) then
    TyOption (default /- cross-file: mapType -/)
  else
    if sorry then
      let alias := getAliasName t
      if alias then
        TyRef alias
      else
        TyString
    else
      if (types.size == 2) && (sorry) then
        TyBool
      else
        let alias := getAliasName t
        if alias then
          let aliasArgs : Option (Array Type) := default
          if aliasArgs && (aliasArgs.size > 0) then
            TyRef alias (Array.map (fun a => default /- cross-file: mapType -/) aliasArgs)
          else
            TyRef alias
        else
          if withoutNil.size > 0 then
            default /- cross-file: mapType -/
          else
            TyRef "TSAny"

-- // ─── Intersection types ─────────────────────────────────────────────────────────
def mapIntersection (t : IntersectionType) (checker : String) (depth : Float) : String :=
  let base : Option Type := sorry
  let brand : Option Type := sorry
  if base && brand then
    let alias := getAliasName t
    if alias then
      TyRef alias
    else
      if base.flags &&& ts.TypeFlags.String then
        TyString
      else
        TyFloat
  else
    let alias := getAliasName t
    if alias then
      TyRef alias
    else
      let concrete : Option Type := sorry
      if concrete then
        default /- cross-file: mapType -/
      else
        TyRef "TSAny"

-- // ─── Object types ───────────────────────────────────────────────────────────────
def mapObject (t : ObjectType) (checker : String) (depth : Float) : String :=
  if t.objectFlags &&& ts.ObjectFlags.Reference then
    mapTypeRef t checker depth
  else
    let sym : Symbol := t.symbol
    if !sym then
      TyRef "TSAny"
    else
      let calls : Array Signature := sorry
      if calls.size > 0 then
        let sig : Signature := calls.getD 0 default
        let params : Array IRType := Array.map (fun p =>
          let pt : Type := sorry
          default /- cross-file: mapType -/) (sorry)
        TyFn params (default /- cross-file: mapType -/) Pure
      else
        let name := sym.name
        if name == TS_ANON_TYPE then
          TyRef "String"
        else
          if (name == "Error") || (name.endsWith "Error") then
            TyString
          else
            TyRef name

-- // ─── Generic type references ────────────────────────────────────────────────────
def mapTypeRef (t : TypeReference) (checker : String) (depth : Float) : String :=
  let name := Option.getD (sorry) ""
  let args : Array Type := sorry
  let map1 : Unit → IRType := fun _ =>
    if args.getD 0 default then
      default /- cross-file: mapType -/
    else
      TyRef "TSAny"
  let map2 : Float → IRType := fun i =>
    if args.getD i default then
      default /- cross-file: mapType -/
    else
      TyRef "TSAny"
  match name with
    | "Array" => TyArray (map1)
    | "ReadonlyArray" => TyArray (map1)
    | "Map" => TyMap (map1) (map2 1)
    | "WeakMap" => TyMap (map1) (map2 1)
    | "Set" => TySet (map1)
    | "WeakSet" => TySet (map1)
    | "Promise" => TyPromise (map1)
    | "Record" => TyMap (map1) (map2 1)
    | "Readonly" => map1
    | "NonNullable" => map1
    | _ => if args.size == 0 then
      TyRef name
    else
      TyRef name (Array.map (fun a => default /- cross-file: mapType -/) args)

/-- Convert an IR type to its Lean 4 syntax string. -/
def irTypeToLean (t : String) (parens : Bool := false) : String :=
  let s := typeStr t
  if parens && (s.includes " ") then
    s!"({s})"
  else
    s

partial def typeStr (t : String) : String :=
  match default with
    | "Nat" => "Nat"
    | "Int" => "Int"
    | "Float" => "Float"
    | "String" => "String"
    | "Bool" => "Bool"
    | "Unit" => "Unit"
    | "Never" => "Empty"
    | "Option" => "Option " ++ (default /- cross-file: irTypeToLean -/)
    | "Array" => "Array " ++ (default /- cross-file: irTypeToLean -/)
    | "Tuple" => if default.size == 0 then
      "Unit"
    else
      ("(" ++ (String.intercalate " × " (Array.map typeStr default))) ++ ")"
    | "Function" => let paramStr := if default.size == 0 then
      "Unit"
    else
      String.intercalate " → " (Array.map (fun p => default /- cross-file: irTypeToLean -/) default)
    (s!"{paramStr} → ") ++ (typeStr default)
    | "Map" => (("AssocMap " ++ (default /- cross-file: irTypeToLean -/)) ++ " ") ++ (default /- cross-file: irTypeToLean -/)
    | "Set" => "Array " ++ (default /- cross-file: irTypeToLean -/)
    | "Promise" => let inner := default
    if default == "Promise" then
      "IO " ++ (default /- cross-file: irTypeToLean -/)
    else
      "IO " ++ (default /- cross-file: irTypeToLean -/)
    | "Result" => (("Except " ++ (default /- cross-file: irTypeToLean -/)) ++ " ") ++ (default /- cross-file: irTypeToLean -/)
    | "TypeRef" => let tsOnlyTypes := #[]
    if sorry then
      "TSAny"
    else
      if default.size == 0 then
        default
      else
        (s!"{default} ") ++ (String.intercalate " " (Array.map (fun a => default /- cross-file: irTypeToLean -/) default))
    | "TypeVar" => default
    | "Structure" => default
    | "Inductive" => default
    | "Dependent" => (((s!"({default} : ") ++ (typeStr default)) ++ ") → ") ++ (typeStr default)
    | "Subtype" => ((("{x : " ++ (typeStr default)) ++ " // ") ++ default) ++ "}"
    | "Universe" => if default == 0 then
      "Prop"
    else
      s!"Type {default}"
    | _ => "TSAny"

-- // ─── Struct field extraction ────────────────────────────────────────────────────
-- A single field extracted from a TypeScript interface or class declaration.
structure StructField where
  mk ::
  name : String
  type : String
  optional : Bool
  mutable : Bool
  deriving Repr, BEq, Inhabited

/-- Extract struct fields from a TypeScript interface or class declaration. Handles optional fields (`?`), readonly modifiers, and resolves types via the type checker. -/
def extractStructFields (node : String) (checker : String) : Array StructField :=
  default

-- // ─── Discriminated union detection ──────────────────────────────────────────────
-- Result of detecting a discriminated union in a TypeScript union type.
structure DiscriminantInfo where
  mk ::
  field : String
  variants : Array String
  deriving Repr, BEq, Inhabited

/-- Detect whether a TypeScript union type is a discriminated union. Checks each known discriminant field name in priority order.  Returns the first field for which every union member has a unique string literal value. -/
def detectDiscriminatedUnion (t : UnionType) (checker : String) : Option DiscriminantInfo :=
  default

def tryField (types : Array ObjectType) (field : String) (checker : String) : Option DiscriminantInfo :=
  default

/-- Extract type parameter names from a TypeScript declaration. -/
def extractTypeParams (node : String) : Array String :=
  Array.map (fun tp => tp.name.text) (Option.getD node.typeParameters #[])

/-- Access the `aliasSymbol.name` on a TypeScript type. This property is not in the public TS API typings but is stable across TypeScript versions (4.x–5.x).  It gives the user-defined alias name for union and intersection types. -/
def getAliasName (t : Type) : Option String :=
  sorry

end TSLean.Generated.SelfHost.TypemapIndex