-- Auto-generated by ts-lean-transpiler
-- Source: /workspace/tslean/src/verification/index.ts

import TSLean.Generated.SelfHost.Prelude
import TSLean.Generated.SelfHost.Prelude
import TSLean.Generated.SelfHost.ir_types
import TSLean.Runtime.Basic
import TSLean.Runtime.Coercions

open TSLean TSLean.Generated.Types

namespace TSLean.Generated.SelfHost.VerificationIndex

-- // ─── Types ────────────────────────────────────────────────────────────────────
inductive ObligationKind where
  | ArrayBounds
  | DivisionSafe
  | OptionIsSome
  | InvariantPreserved
  | TerminationBy
  deriving Repr, BEq, Inhabited

structure ProofObligation where
  mk ::
  kind : ObligationKind
  funcName : String
  detail : String
  deriving Repr, BEq, Inhabited

structure VerificationResult where
  mk ::
  obligations : Array ProofObligation
  leanCode : String
  deriving Repr, BEq, Inhabited

-- // ─── Public API ───────────────────────────────────────────────────────────────
def generateVerification (mod : String) : VerificationResult :=
  default

-- // ─── Collection ───────────────────────────────────────────────────────────────
partial def collectDecl (d : String) (acc : Array ProofObligation) : Unit :=
  if d.tag == "FuncDef" then
    collectExpr default default acc
  else
    ()
  if d.tag == "Namespace" then
    sorry
  else
    ()

partial def collectExpr (e : String) (fn : String) (acc : Array ProofObligation) : Unit :=
  match e.tag with
    | "IndexAccess" => Array.push acc ObligationKind.ArrayBounds fn ((((exprSummary default) ++ "[") ++ (exprSummary default)) ++ "]")
    collectExpr default fn acc
    collectExpr default fn acc
    | "BinOp" => if (default == "Div") || (default == "Mod") then
      Array.push acc ObligationKind.DivisionSafe fn (exprSummary default)
    else
      ()
    collectExpr default fn acc
    collectExpr default fn acc
    | "FieldAccess" => if ((default == "value") || (default == "get")) && (default == "Option") then
      Array.push acc ObligationKind.OptionIsSome fn (exprSummary default)
    else
      ()
    collectExpr default fn acc
    | "Let" => collectExpr default fn acc
    collectExpr default fn acc
    | "Bind" => collectExpr default fn acc
    collectExpr default fn acc
    | "IfThenElse" => collectExpr default fn acc
    collectExpr default fn acc
    collectExpr default fn acc
    | "Match" => collectExpr default fn acc
    sorry
    | "Sequence" => sorry
    | "App" => collectExpr default fn acc
    sorry
    | "Lambda" => collectExpr default fn acc
    | "Assign" => collectExpr default fn acc
    | "TryCatch" => collectExpr default fn acc
    collectExpr default fn acc
    | "Return" => collectExpr default fn acc
    | "Throw" => collectExpr default fn acc
    | "BinOp" => ()
    | _ => ()

partial def exprSummary (e : String) : String :=
  match e.tag with
    | "Var" => default
    | "FieldAccess" => ((exprSummary default) ++ ".") ++ default
    | "LitNat" => String default
    | "LitString" => serialize default
    | _ => "_"

-- // ─── Emission ─────────────────────────────────────────────────────────────────
def emitObligation (o : ProofObligation) : String :=
  let safeName := o.funcName.replace "/[^a-zA-Z0-9_]/g" "_"
  match o.kind with
    | "ArrayBounds" => String.intercalate "\n" #[s!"-- Array bounds safety for `{o.funcName}` accessing {o.detail}", s!"theorem {safeName}_idx_in_bounds", "    (arr : Array α) (idx : Nat) (h : idx < arr.size) :", "    arr[idx]! = arr[⟨idx, h⟩] := by", "  simp [Array.get!_eq_getElem]"]
    | "DivisionSafe" => String.intercalate "\n" #[s!"-- Division safety for `{o.funcName}` divisor: {o.detail}", s!"theorem {safeName}_divisor_nonzero", "    (n d : Float) (h : d ≠ 0) : n / d = n / d := rfl"]
    | "OptionIsSome" => String.intercalate "\n" #[s!"-- Option safety for `{o.funcName}` accessing {o.detail}", s!"theorem {safeName}_val_is_some", "    {α : Type} (opt : Option α) (h : opt.isSome) :", "    opt.get!.isSome := by cases opt <;> simp_all"]
    | "InvariantPreserved" => String.intercalate "\n" #[s!"-- Invariant preserved by `{o.funcName}`", s!"theorem {safeName}_invariant_preserved", "    (s : σ) (h : invariant s) : ∃ s', invariant s' := ⟨s, h⟩"]
    | "TerminationBy" => s!"-- termination_by {o.detail} -- for `{o.funcName}`"

end TSLean.Generated.SelfHost.VerificationIndex