import type { RuntimeCertificateBinding, RuntimeConformanceAttestation } from './certificates.js';

/**
 * Which plane an input belongs to. A semantic input is a versioned source that decides what
 * the compiler emits; an environment input is a binary that happened to run the compiler.
 * Only the semantic plane may reach the generated bytes, so a runtime upgrade cannot make a
 * committed artifact stale while its Lean source is unchanged.
 */
export type LeanToTypeScriptPlane = 'semantic' | 'environment';

export type LeanToTypeScriptInputKind =
  'compiler-runtime' | 'compiler-source' | 'lean-module' | 'lean-project' | 'lean-source' | 'lean-toolchain';

export const LEAN_TO_TYPESCRIPT_INPUT_PLANES: Readonly<Record<LeanToTypeScriptInputKind, LeanToTypeScriptPlane>> =
  Object.freeze({
    'compiler-runtime': 'environment',
    'compiler-source': 'semantic',
    'lean-module': 'environment',
    'lean-project': 'semantic',
    'lean-source': 'semantic',
    'lean-toolchain': 'environment',
  });

export interface LeanToTypeScriptInput {
  readonly kind: LeanToTypeScriptInputKind;
  readonly identity: string;
  readonly sha256: string;
}

export interface LeanToTypeScriptLeanToolchain {
  readonly identity: string;
  readonly leanVersion: string;
  readonly lakeVersion: string;
}

/**
 * What the compiler did with one constant in the reachable closure. Every reachable constant
 * carries exactly one role, so the record accounts for the whole closure instead of only the
 * part that reached a generated file. Anything the compiler cannot place under one of these
 * roles is a hard diagnostic and no artifact is produced.
 *
 * - `emitted`: lowered into a generated module.
 * - `erased`: kernel-level scaffolding with no emitted form of its own — a proof, a `match`
 *   auxiliary, a projection, a constructor, or a recursor. `reason` names which.
 * - `runtime-boundary`: a constant the fragment admits without lowering it, because the
 *   TypeScript representation is fixed by the type mapping rather than by Lean's definition.
 */
export type LeanToTypeScriptDeclarationRole = 'emitted' | 'erased' | 'runtime-boundary';

export interface LeanToTypeScriptClosureEntry {
  readonly declaration: string;
  /** The declaring Lean module, or the empty string for a constant outside the target closure. */
  readonly module: string;
  readonly role: LeanToTypeScriptDeclarationRole;
  /** Why the constant carries that role. Empty exactly for `emitted`. */
  readonly reason: string;
}

/** Where a generated declaration came from, in its own Lean source file. */
export interface LeanToTypeScriptSourceSpan {
  /** The Lean source path relative to the target project root. */
  readonly source: string;
  readonly startLine: number;
  readonly startColumn: number;
  readonly endLine: number;
  readonly endColumn: number;
}

/** One generated declaration, and the Lean declaration it is the image of. */
export interface LeanToTypeScriptGeneratedDeclaration {
  readonly declaration: string;
  readonly emitted: string;
  /** 1-based line of the declaration in the generated module, provenance header included. */
  readonly line: number;
  readonly span: LeanToTypeScriptSourceSpan;
}

/** One generated module: what it carries, what it imports, and what its bytes hash to. */
export interface LeanToTypeScriptModuleIdentity {
  readonly path: string;
  /** The Lean module this file is the image of, or the empty string for the shared runtime. */
  readonly leanModule: string;
  /** Generated module paths this module imports, in emitted order. */
  readonly imports: readonly string[];
  readonly declarations: readonly LeanToTypeScriptGeneratedDeclaration[];
  readonly bodySha256: string;
  /** Digest of the module's source map, or the empty string when it has no Lean source. */
  readonly sourceMapSha256: string;
}

/** Everything the generated bytes are a function of, and nothing else. */
export interface LeanToTypeScriptSemanticIdentity {
  readonly fragmentVersion: string;
  /** The Lean module Lake builds and the exporter imports to reach every requested root. */
  readonly entryModule: string;
  readonly declarations: readonly string[];
  readonly leanToolchain: LeanToTypeScriptLeanToolchain;
  /** Where the Lean project root sits relative to the generated package root. */
  readonly leanProjectPath: string;
  readonly modules: readonly LeanToTypeScriptModuleIdentity[];
  readonly closure: readonly LeanToTypeScriptClosureEntry[];
  readonly inputs: readonly LeanToTypeScriptInput[];
  readonly inputClosureSha256: string;
  readonly semanticIrSha256: string;
  /** Every used opcode certificate, bound to its emitted runtime body. */
  readonly certificates: readonly RuntimeCertificateBinding[];
  /** One digest over every generated module body, in path order. */
  readonly generatedBodySha256: string;
}

/** The machine that produced the artifact. Recorded, never binding on the artifact bytes. */
export interface LeanToTypeScriptEnvironmentAttestation {
  readonly runtime: string;
  readonly typescriptVersion: string;
  readonly platform: string;
  readonly inputs: readonly LeanToTypeScriptInput[];
  readonly inputClosureSha256: string;
  /** Observed supported-engine evidence for the conditional certificates this package uses. */
  readonly runtimeConformance: readonly RuntimeConformanceAttestation[];
}

export interface LeanToTypeScriptManifest {
  readonly schemaVersion: 4;
  readonly semantic: LeanToTypeScriptSemanticIdentity;
  readonly environment: LeanToTypeScriptEnvironmentAttestation;
}

/** One generated file and, where it has a Lean source, its declaration-level source map. */
export interface LeanToTypeScriptModuleArtifact {
  readonly path: string;
  readonly code: string;
  readonly sourceMap: { readonly path: string; readonly contents: string } | undefined;
}

export interface LeanToTypeScriptPackage {
  readonly modules: readonly LeanToTypeScriptModuleArtifact[];
  readonly manifest: LeanToTypeScriptManifest;
}

export function leanToTypeScriptInputPlane(kind: LeanToTypeScriptInputKind): LeanToTypeScriptPlane {
  return LEAN_TO_TYPESCRIPT_INPUT_PLANES[kind];
}
