/**
 * Which plane an input belongs to. A semantic input is a versioned source that decides what
 * the compiler emits; an environment input is a binary that happened to run the compiler.
 * Only the semantic plane may reach the generated bytes, so a runtime upgrade cannot make a
 * committed artifact stale while its Lean source is unchanged.
 */
export type LeanToTypeScriptPlane = 'semantic' | 'environment';

export type LeanToTypeScriptInputKind =
  'compiler-runtime' | 'compiler-source' | 'lean-module' | 'lean-project' | 'lean-source' | 'lean-toolchain';

export const LEAN_TO_TYPESCRIPT_INPUT_PLANES: Readonly<Record<LeanToTypeScriptInputKind, LeanToTypeScriptPlane>> =
  Object.freeze({
    'compiler-runtime': 'environment',
    'compiler-source': 'semantic',
    'lean-module': 'environment',
    'lean-project': 'semantic',
    'lean-source': 'semantic',
    'lean-toolchain': 'environment',
  });

export interface LeanToTypeScriptInput {
  readonly kind: LeanToTypeScriptInputKind;
  readonly identity: string;
  readonly sha256: string;
}

export interface LeanToTypeScriptLeanToolchain {
  readonly identity: string;
  readonly leanVersion: string;
  readonly lakeVersion: string;
}

/** Everything the generated bytes are a function of, and nothing else. */
export interface LeanToTypeScriptSemanticIdentity {
  readonly fragmentVersion: string;
  readonly sourceModule: string;
  readonly declarations: readonly string[];
  readonly leanToolchain: LeanToTypeScriptLeanToolchain;
  readonly inputs: readonly LeanToTypeScriptInput[];
  readonly inputClosureSha256: string;
  readonly semanticIrSha256: string;
  readonly generatedBodySha256: string;
}

/** The machine that produced the artifact. Recorded, never binding on the artifact bytes. */
export interface LeanToTypeScriptEnvironmentAttestation {
  readonly runtime: string;
  readonly typescriptVersion: string;
  readonly platform: string;
  readonly inputs: readonly LeanToTypeScriptInput[];
  readonly inputClosureSha256: string;
}

export interface LeanToTypeScriptManifest {
  readonly schemaVersion: 2;
  readonly semantic: LeanToTypeScriptSemanticIdentity;
  readonly environment: LeanToTypeScriptEnvironmentAttestation;
}

export interface LeanToTypeScriptArtifact {
  readonly code: string;
  readonly manifest: LeanToTypeScriptManifest;
}

export function leanToTypeScriptInputPlane(kind: LeanToTypeScriptInputKind): LeanToTypeScriptPlane {
  return LEAN_TO_TYPESCRIPT_INPUT_PLANES[kind];
}
