import ts from 'typescript';
import { createHash } from 'node:crypto';
import type { LeanToTypeScriptArtifact, LeanToTypeScriptManifest } from './artifact.js';
import type { LeanDeclaration, LeanExpression, LeanSemanticProgram, LeanType } from './ir.js';
import { compareCodePoints } from './ordering.js';

export function emitTypeScript(
  program: LeanSemanticProgram,
  provenance: Omit<LeanToTypeScriptManifest, 'generatedBodySha256'>,
): LeanToTypeScriptArtifact {
  const declarations = orderedDeclarations(program);
  const roots = new Set(program.roots);
  const declarationNames = new Map(
    program.declarations.map((declaration) => [declaration.name, localName(declaration.name)]),
  );
  const statements = declarations.map((declaration) => emitDeclaration(declaration, roots, declarationNames));
  const file = ts.factory.updateSourceFile(
    ts.createSourceFile('generated.ts', '', ts.ScriptTarget.Latest, false, ts.ScriptKind.TS),
    statements,
  );
  const body = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed }).printFile(file);
  const manifest = canonicalManifest({
    ...provenance,
    generatedBodySha256: sha256(body),
  });
  const artifact = { code: `${provenanceHeader(manifest)}${body}`, manifest };
  verifyLeanToTypeScriptArtifact(artifact);
  return artifact;
}

export function verifyLeanToTypeScriptArtifact(value: unknown): asserts value is LeanToTypeScriptArtifact {
  const artifact = decodeArtifact(value);
  const header = provenanceHeader(artifact.manifest);
  if (!artifact.code.startsWith(header)) {
    throw new TypeError('generated TypeScript provenance header does not match its manifest');
  }
  const body = artifact.code.slice(header.length);
  if (sha256(body) !== artifact.manifest.generatedBodySha256) {
    throw new TypeError('generated TypeScript body does not match its manifest');
  }
}

function provenanceHeader(manifest: LeanToTypeScriptManifest): string {
  const canonical = canonicalManifest(manifest);
  return [
    '/*',
    ' * Generated by TSLean from a kernel-checked Lean declaration.',
    ` * Fragment: ${canonical.fragmentVersion}`,
    ` * Source module: ${canonical.sourceModule}`,
    ` * Manifest: ${sha256(JSON.stringify(canonical))}`,
    ` * Input closure: ${canonical.inputClosureSha256}`,
    ` * Semantic IR: ${canonical.semanticIrSha256}`,
    ` * Generated body: ${canonical.generatedBodySha256}`,
    ` * TypeScript: ${canonical.typescriptVersion}`,
    ` * Runtime: ${canonical.runtime}`,
    ` * Lean toolchain: ${canonical.leanToolchain.identity}`,
    ` * Lean: ${canonical.leanToolchain.leanVersion}`,
    ` * Lake: ${canonical.leanToolchain.lakeVersion}`,
    ' * Evidence boundary: generation is checked and differential tests are empirical; no refinement theorem is claimed.',
    ' */',
    '',
  ].join('\n');
}

function canonicalManifest(manifest: LeanToTypeScriptManifest): LeanToTypeScriptManifest {
  return {
    schemaVersion: manifest.schemaVersion,
    fragmentVersion: manifest.fragmentVersion,
    sourceModule: manifest.sourceModule,
    declarations: manifest.declarations,
    semanticIrSha256: manifest.semanticIrSha256,
    inputClosureSha256: manifest.inputClosureSha256,
    generatedBodySha256: manifest.generatedBodySha256,
    inputs: manifest.inputs,
    typescriptVersion: manifest.typescriptVersion,
    runtime: manifest.runtime,
    leanToolchain: manifest.leanToolchain,
  };
}

function sha256(value: string): string {
  return `sha256:${createHash('sha256').update(value).digest('hex')}`;
}

function decodeArtifact(value: unknown): LeanToTypeScriptArtifact {
  const artifact = record(value, 'Lean to TypeScript artifact');
  exactKeys(artifact, ['code', 'manifest'], 'Lean to TypeScript artifact');
  return {
    code: string(artifact['code'], 'Lean to TypeScript artifact code'),
    manifest: decodeManifest(artifact['manifest']),
  };
}

function decodeManifest(value: unknown): LeanToTypeScriptManifest {
  const manifest = record(value, 'Lean to TypeScript manifest');
  exactKeys(
    manifest,
    [
      'schemaVersion',
      'fragmentVersion',
      'sourceModule',
      'declarations',
      'semanticIrSha256',
      'inputClosureSha256',
      'generatedBodySha256',
      'inputs',
      'typescriptVersion',
      'runtime',
      'leanToolchain',
    ],
    'Lean to TypeScript manifest',
  );
  if (manifest['schemaVersion'] !== 1) throw new TypeError('unsupported Lean to TypeScript manifest schema');
  const declarations = strings(manifest['declarations'], 'Lean to TypeScript manifest declarations');
  requireCanonicalOrder(declarations, 'Lean to TypeScript manifest declarations');
  const inputs = array(manifest['inputs'], 'Lean to TypeScript manifest inputs').map(decodeInput);
  if (inputs.length === 0) throw new TypeError('Lean to TypeScript manifest inputs must be nonempty');
  requireCanonicalOrder(
    inputs.map((input) => input.identity),
    'Lean to TypeScript manifest input identities',
  );
  const inputClosureSha256 = digest(manifest['inputClosureSha256'], 'Lean to TypeScript manifest input closure');
  if (sha256(JSON.stringify(inputs)) !== inputClosureSha256) {
    throw new TypeError('Lean to TypeScript manifest input closure does not match its inputs');
  }
  const leanToolchain = record(manifest['leanToolchain'], 'Lean to TypeScript manifest Lean toolchain');
  exactKeys(leanToolchain, ['identity', 'leanVersion', 'lakeVersion'], 'Lean to TypeScript manifest Lean toolchain');
  return canonicalManifest({
    schemaVersion: 1,
    fragmentVersion: string(manifest['fragmentVersion'], 'Lean to TypeScript manifest fragment version'),
    sourceModule: string(manifest['sourceModule'], 'Lean to TypeScript manifest source module'),
    declarations,
    semanticIrSha256: digest(manifest['semanticIrSha256'], 'Lean to TypeScript manifest semantic IR'),
    inputClosureSha256,
    generatedBodySha256: digest(manifest['generatedBodySha256'], 'Lean to TypeScript manifest generated body'),
    inputs,
    typescriptVersion: string(manifest['typescriptVersion'], 'Lean to TypeScript manifest TypeScript version'),
    runtime: string(manifest['runtime'], 'Lean to TypeScript manifest runtime'),
    leanToolchain: {
      identity: string(leanToolchain['identity'], 'Lean to TypeScript manifest toolchain identity'),
      leanVersion: string(leanToolchain['leanVersion'], 'Lean to TypeScript manifest Lean version'),
      lakeVersion: string(leanToolchain['lakeVersion'], 'Lean to TypeScript manifest Lake version'),
    },
  });
}

function decodeInput(value: unknown, index: number): LeanToTypeScriptManifest['inputs'][number] {
  const location = `Lean to TypeScript manifest inputs[${index}]`;
  const input = record(value, location);
  exactKeys(input, ['kind', 'identity', 'sha256'], location);
  const kind = inputKind(input['kind'], `${location} kind`);
  return {
    kind,
    identity: string(input['identity'], `${location} identity`),
    sha256: digest(input['sha256'], `${location} digest`),
  };
}

function record(value: unknown, location: string): Record<string, unknown> {
  if (!isRecord(value)) throw new TypeError(`${location} must be an object`);
  return value;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function array(value: unknown, location: string): readonly unknown[] {
  if (!Array.isArray(value)) throw new TypeError(`${location} must be an array`);
  return value;
}

function string(value: unknown, location: string): string {
  if (typeof value !== 'string' || value.length === 0) throw new TypeError(`${location} must be a nonempty string`);
  return value;
}

function inputKind(value: unknown, location: string): LeanToTypeScriptManifest['inputs'][number]['kind'] {
  switch (value) {
    case 'compiler':
    case 'lean-module':
    case 'lean-project':
    case 'lean-source':
    case 'typescript':
      return value;
    default:
      throw new TypeError(`${location} has unknown kind ${String(value)}`);
  }
}

function strings(value: unknown, location: string): readonly string[] {
  const values = array(value, location).map((entry, index) => string(entry, `${location}[${index}]`));
  if (values.length === 0) throw new TypeError(`${location} must be nonempty`);
  return values;
}

function digest(value: unknown, location: string): string {
  const hash = string(value, location);
  if (!/^sha256:[0-9a-f]{64}$/u.test(hash)) throw new TypeError(`${location} must be a SHA-256 digest`);
  return hash;
}

function exactKeys(value: Record<string, unknown>, expected: readonly string[], location: string): void {
  const actual = Object.keys(value).sort(compareCodePoints);
  const canonical = [...expected].sort(compareCodePoints);
  if (actual.length !== canonical.length || actual.some((key, index) => key !== canonical[index])) {
    throw new TypeError(`${location} fields must be exactly ${canonical.join(', ')}`);
  }
}

function requireCanonicalOrder(values: readonly string[], location: string): void {
  for (let index = 1; index < values.length; index += 1) {
    const previous = values[index - 1];
    const current = values[index];
    if (previous === undefined || current === undefined || compareCodePoints(previous, current) >= 0) {
      throw new TypeError(`${location} must be strictly ordered and unique`);
    }
  }
}

function orderedDeclarations(program: LeanSemanticProgram): readonly LeanDeclaration[] {
  const types = program.declarations
    .filter((declaration) => declaration.kind !== 'function')
    .sort((left, right) => {
      const kindOrder = Number(left.kind === 'record') - Number(right.kind === 'record');
      return kindOrder || compareCodePoints(left.name, right.name);
    });
  const functions = new Map(
    program.declarations
      .filter(
        (declaration): declaration is Extract<LeanDeclaration, { kind: 'function' }> => declaration.kind === 'function',
      )
      .map((declaration) => [declaration.name, declaration]),
  );
  const orderedFunctions: Extract<LeanDeclaration, { kind: 'function' }>[] = [];
  const visiting = new Set<string>();
  const visited = new Set<string>();
  const visit = (name: string): void => {
    if (visited.has(name)) return;
    if (visiting.has(name)) throw new TypeError(`recursive function cycle is outside the fragment: ${name}`);
    const declaration = functions.get(name);
    if (declaration === undefined) return;
    visiting.add(name);
    for (const dependency of calledFunctions(declaration.body)) visit(dependency);
    visiting.delete(name);
    visited.add(name);
    orderedFunctions.push(declaration);
  };
  for (const root of program.roots) visit(root);
  for (const name of [...functions.keys()].sort(compareCodePoints)) visit(name);
  return [...types, ...orderedFunctions];
}

function calledFunctions(expression: LeanExpression): readonly string[] {
  const names = new Set<string>();
  const visit = (node: LeanExpression): void => {
    switch (node.kind) {
      case 'call':
        names.add(node.function);
        node.arguments.forEach(visit);
        return;
      case 'let':
        visit(node.value);
        visit(node.body);
        return;
      case 'field':
        visit(node.target);
        return;
      case 'if':
        visit(node.condition);
        visit(node.consequent);
        visit(node.alternate);
        return;
      case 'equals':
      case 'and':
      case 'or':
        visit(node.left);
        visit(node.right);
        return;
      case 'not':
        visit(node.operand);
        return;
      case 'some':
        visit(node.value);
        return;
      case 'record':
        node.fields.forEach((field) => visit(field.value));
        return;
      case 'variable':
      case 'boolean':
      case 'none':
      case 'variant':
        return;
    }
  };
  visit(expression);
  return [...names].sort(compareCodePoints);
}

function emitDeclaration(
  declaration: LeanDeclaration,
  roots: ReadonlySet<string>,
  declarationNames: ReadonlyMap<string, string>,
): ts.Statement {
  switch (declaration.kind) {
    case 'enum':
      return ts.factory.createTypeAliasDeclaration(
        [exportModifier()],
        localName(declaration.name),
        undefined,
        ts.factory.createUnionTypeNode(
          declaration.constructors.map((constructor) =>
            ts.factory.createLiteralTypeNode(ts.factory.createStringLiteral(constructor)),
          ),
        ),
      );
    case 'record':
      return ts.factory.createInterfaceDeclaration(
        [exportModifier()],
        localName(declaration.name),
        undefined,
        undefined,
        declaration.fields.map((field) =>
          ts.factory.createPropertySignature(
            [ts.factory.createModifier(ts.SyntaxKind.ReadonlyKeyword)],
            field.name === '__proto__'
              ? ts.factory.createStringLiteral(field.name)
              : ts.factory.createIdentifier(field.name),
            undefined,
            emitType(field.type, declarationNames),
          ),
        ),
      );
    case 'function': {
      const allocator = new IdentifierAllocator([...declarationNames.values(), 'undefined']);
      const parameters = declaration.parameters.map((parameter) => ({
        ...parameter,
        emittedName: allocator.allocate(parameter.name),
      }));
      const scope = parameters.map((parameter) => parameter.emittedName).reverse();
      return ts.factory.createFunctionDeclaration(
        roots.has(declaration.name) ? [exportModifier()] : undefined,
        undefined,
        localName(declaration.name),
        undefined,
        parameters.map((parameter) =>
          ts.factory.createParameterDeclaration(
            undefined,
            undefined,
            parameter.emittedName,
            undefined,
            emitType(parameter.type, declarationNames),
          ),
        ),
        emitType(declaration.result, declarationNames),
        emitFunctionBody(declaration.body, scope, allocator, declarationNames),
      );
    }
  }
}

function exportModifier(): ts.Modifier {
  return ts.factory.createModifier(ts.SyntaxKind.ExportKeyword);
}

function emitType(type: LeanType, declarationNames: ReadonlyMap<string, string>): ts.TypeNode {
  switch (type.kind) {
    case 'boolean':
      return ts.factory.createKeywordTypeNode(ts.SyntaxKind.BooleanKeyword);
    case 'named':
      return ts.factory.createTypeReferenceNode(requiredDeclarationName(declarationNames, type.name));
    case 'option':
      return ts.factory.createUnionTypeNode([
        emitType(type.inner, declarationNames),
        ts.factory.createKeywordTypeNode(ts.SyntaxKind.UndefinedKeyword),
      ]);
  }
}

function emitFunctionBody(
  expression: LeanExpression,
  scope: readonly string[],
  allocator: IdentifierAllocator,
  declarationNames: ReadonlyMap<string, string>,
): ts.Block {
  const statements: ts.Statement[] = [];
  let current = expression;
  let currentScope = scope;
  while (current.kind === 'let') {
    const emittedName = allocator.allocate(current.name);
    statements.push(
      ts.factory.createVariableStatement(
        undefined,
        ts.factory.createVariableDeclarationList(
          [
            ts.factory.createVariableDeclaration(
              emittedName,
              undefined,
              undefined,
              emitExpression(current.value, currentScope, declarationNames),
            ),
          ],
          ts.NodeFlags.Const,
        ),
      ),
    );
    currentScope = [emittedName, ...currentScope];
    current = current.body;
  }
  statements.push(ts.factory.createReturnStatement(emitExpression(current, currentScope, declarationNames)));
  return ts.factory.createBlock(statements, true);
}

function emitExpression(
  expression: LeanExpression,
  scope: readonly string[],
  declarationNames: ReadonlyMap<string, string>,
): ts.Expression {
  switch (expression.kind) {
    case 'variable': {
      const name = scope[expression.index];
      if (name === undefined) throw new TypeError(`unbound de Bruijn index ${expression.index}`);
      return ts.factory.createIdentifier(name);
    }
    case 'boolean':
      return expression.value ? ts.factory.createTrue() : ts.factory.createFalse();
    case 'let':
      throw new TypeError('nested let expressions must be normalized before emission');
    case 'field':
      return expression.field === '__proto__'
        ? ts.factory.createElementAccessExpression(
            emitExpression(expression.target, scope, declarationNames),
            ts.factory.createStringLiteral(expression.field),
          )
        : ts.factory.createPropertyAccessExpression(
            emitExpression(expression.target, scope, declarationNames),
            expression.field,
          );
    case 'if':
      return ts.factory.createConditionalExpression(
        emitExpression(expression.condition, scope, declarationNames),
        undefined,
        emitExpression(expression.consequent, scope, declarationNames),
        undefined,
        emitExpression(expression.alternate, scope, declarationNames),
      );
    case 'equals':
      if (expression.right.kind === 'boolean' && expression.right.value) {
        return emitExpression(expression.left, scope, declarationNames);
      }
      if (expression.left.kind === 'boolean' && expression.left.value) {
        return emitExpression(expression.right, scope, declarationNames);
      }
      return ts.factory.createBinaryExpression(
        emitExpression(expression.left, scope, declarationNames),
        ts.SyntaxKind.EqualsEqualsEqualsToken,
        emitExpression(expression.right, scope, declarationNames),
      );
    case 'and':
    case 'or':
      return ts.factory.createBinaryExpression(
        emitExpression(expression.left, scope, declarationNames),
        expression.kind === 'and' ? ts.SyntaxKind.AmpersandAmpersandToken : ts.SyntaxKind.BarBarToken,
        emitExpression(expression.right, scope, declarationNames),
      );
    case 'not':
      return ts.factory.createPrefixUnaryExpression(
        ts.SyntaxKind.ExclamationToken,
        emitExpression(expression.operand, scope, declarationNames),
      );
    case 'some':
      return emitExpression(expression.value, scope, declarationNames);
    case 'none':
      return ts.factory.createIdentifier('undefined');
    case 'variant':
      return ts.factory.createStringLiteral(expression.name);
    case 'record':
      return ts.factory.createObjectLiteralExpression(
        expression.fields.map((field) =>
          ts.factory.createPropertyAssignment(
            field.name === '__proto__'
              ? ts.factory.createComputedPropertyName(ts.factory.createStringLiteral(field.name))
              : ts.factory.createIdentifier(field.name),
            emitExpression(field.value, scope, declarationNames),
          ),
        ),
        true,
      );
    case 'call':
      return ts.factory.createCallExpression(
        ts.factory.createIdentifier(requiredDeclarationName(declarationNames, expression.function)),
        undefined,
        expression.arguments.map((argument) => emitExpression(argument, scope, declarationNames)),
      );
  }
}

class IdentifierAllocator {
  readonly #used: Set<string>;

  public constructor(reserved: Iterable<string>) {
    this.#used = new Set(reserved);
  }

  public allocate(hint: string): string {
    const stem = safeIdentifierStem(hint);
    let candidate = stem;
    let suffix = 2;
    while (this.#used.has(candidate)) {
      candidate = `${stem}$${suffix}`;
      suffix += 1;
    }
    this.#used.add(candidate);
    return candidate;
  }
}

function safeIdentifierStem(hint: string): string {
  const sanitized = hint.replace(/[^$0-9A-Z_a-z]/gu, '_');
  const prefixed = /^[$A-Z_a-z]/u.test(sanitized) ? sanitized : `value_${sanitized}`;
  const candidate = prefixed.length === 0 ? 'value' : prefixed;
  const scanner = ts.createScanner(ts.ScriptTarget.Latest, false, ts.LanguageVariant.Standard, candidate);
  if (
    scanner.scan() !== ts.SyntaxKind.Identifier ||
    scanner.scan() !== ts.SyntaxKind.EndOfFileToken ||
    candidate === 'arguments' ||
    candidate === 'eval'
  ) {
    return `value_${candidate}`;
  }
  return candidate;
}

function requiredDeclarationName(names: ReadonlyMap<string, string>, name: string): string {
  const emitted = names.get(name);
  if (emitted === undefined) throw new TypeError(`missing emitted declaration name for ${name}`);
  return emitted;
}

function localName(name: string): string {
  const part = name.split('.').at(-1);
  if (part === undefined) throw new TypeError('empty Lean name');
  return part;
}
