import { createHash } from 'node:crypto';
import {
  LEAN_TO_TYPESCRIPT_INPUT_PLANES,
  type LeanToTypeScriptClosureEntry,
  type LeanToTypeScriptCodecSurface,
  type LeanToTypeScriptDeclarationRole,
  type LeanToTypeScriptEnvironmentAttestation,
  type LeanToTypeScriptGeneratedDeclaration,
  type LeanToTypeScriptHelperDeclaration,
  type LeanToTypeScriptHostBoundary,
  type LeanToTypeScriptInput,
  type LeanToTypeScriptInputKind,
  type LeanToTypeScriptManifest,
  type LeanToTypeScriptModuleIdentity,
  type LeanToTypeScriptPackage,
  type LeanToTypeScriptPlane,
  type LeanToTypeScriptSemanticIdentity,
  type LeanToTypeScriptSourceSpan,
} from './artifact.js';
import {
  assertRuntimeCertificateBindings,
  loadRuntimeCertificateRegistry,
  taggedRuntimeSymbol,
  RUNTIME_BINARY_INPUT,
  RUNTIME_EVIDENCE_INPUT,
  type RuntimeCertificateBinding,
  type RuntimeConformanceAttestation,
} from './certificates.js';
import { LEAN_HOST_OPCODES, LEAN_RUNTIME_HELPER_ROLES } from './ir.js';
import { LEAN_TO_TYPESCRIPT_HOST_MODULE_PATH } from './package-layout.js';
import { compareCodePoints } from './ordering.js';
/**
 * One shared manifest schema version, split as major.minor. A minor bump adds an optional field
 * and every reader in the major accepts it; only a major bump may remove or reinterpret a field,
 * and that is the only change that strands an older reader. The v6 surface adds the host, helper
 * and codec inventories as required fields, which no v5 writer supplies, so it is a major bump.
 */
export const LEAN_TO_TYPESCRIPT_MANIFEST_SCHEMA_VERSION = 5_001;

/**
 * How many lines the provenance header occupies. The header is a fixed template of one line per
 * field, so the count is a property of the template and not of the values. Emission needs it
 * before the manifest exists, to place each declaration's generated line, and
 * `provenanceHeader` asserts the rendered header still matches, so it cannot drift.
 */
export const PROVENANCE_HEADER_LINES = 18;

/**
 * The provenance header carries the semantic identity only. Nothing about the machine that
 * ran the compiler appears in the generated bytes, so re-running the same compiler over the
 * same Lean sources under a different runtime reproduces the artifact byte for byte.
 *
 * Each generated module names itself and the package it belongs to: `Lean module` is the source
 * this file is the image of, `Generated module` is its path inside the package, and the digests
 * bind the whole package, so no single file can be refreshed in isolation.
 */
export function provenanceHeader(manifest: LeanToTypeScriptManifest, path: string): string {
  const semantic = canonicalSemanticIdentity(manifest.semantic);
  const module = requiredModuleIdentity(semantic, path);
  const lines = [
    '/*',
    ' * Generated by TSLean from kernel-checked Lean declarations.',
    ` * Fragment: ${semantic.fragmentVersion}`,
    ` * Lean module: ${module.leanModule === '' ? '(generated package runtime)' : module.leanModule}`,
    ` * Generated module: ${module.path}`,
    ` * Package entry module: ${semantic.entryModule}`,
    ` * Semantic identity: ${semanticIdentityDigest(semantic)}`,
    ` * Input closure: ${semantic.inputClosureSha256}`,
    ` * Semantic IR: ${semantic.semanticIrSha256}`,
    ` * Generated module body: ${module.bodySha256}`,
    ` * Generated package body: ${semantic.generatedBodySha256}`,
    ` * Lean toolchain: ${semantic.leanToolchain.identity}`,
    ` * Lean: ${semantic.leanToolchain.leanVersion}`,
    ` * Lake: ${semantic.leanToolchain.lakeVersion}`,
    ` * Runtime certificates: ${runtimeCertificateDigest(semantic.certificates)}`,
    ' * Environment attestation: recorded in the manifest sidecar; it does not affect these bytes.',
    ' * Evidence boundary: Lean certificates prove source-to-model refinement conditionally; engine conformance remains an explicit obligation.',
    ' */',
    '',
  ];
  if (lines.length - 1 !== PROVENANCE_HEADER_LINES) {
    throw new TypeError('provenance header line count no longer matches PROVENANCE_HEADER_LINES');
  }
  return lines.join('\n');
}

/** One digest over every generated module body, in path order: the package's own identity. */
export function generatedPackageDigest(
  modules: readonly { readonly path: string; readonly bodySha256: string }[],
): string {
  return sha256(JSON.stringify(modules.map((module) => [module.path, module.bodySha256])));
}

/** One digest over the exact proof records the generated package actually uses. */
export function runtimeCertificateDigest(certificates: readonly RuntimeCertificateBinding[]): string {
  return sha256(JSON.stringify(certificates));
}

export function semanticIdentityDigest(semantic: LeanToTypeScriptSemanticIdentity): string {
  return sha256(JSON.stringify(canonicalSemanticIdentity(semantic)));
}

export function environmentAttestationDigest(environment: LeanToTypeScriptEnvironmentAttestation): string {
  return sha256(JSON.stringify(canonicalEnvironmentAttestation(environment)));
}

export function canonicalManifest(manifest: LeanToTypeScriptManifest): LeanToTypeScriptManifest {
  const semantic = canonicalSemanticIdentity(manifest.semantic);
  const environment = canonicalEnvironmentAttestation(manifest.environment);
  assertCertificateConformance(semantic, environment);
  return {
    schemaVersion: LEAN_TO_TYPESCRIPT_MANIFEST_SCHEMA_VERSION,
    semantic,
    environment,
  };
}

/**
 * Every generated module agrees with the manifest that describes it: its header is the exact
 * header the semantic identity produces, its body hashes to the digest recorded for its path,
 * and the recorded module set is exactly the emitted one.
 */
export function verifyLeanToTypeScriptPackage(value: unknown): asserts value is LeanToTypeScriptPackage {
  const emitted = decodePackage(value);
  const recorded = emitted.manifest.semantic.modules;
  const emittedPaths = emitted.modules.map((module) => module.path);
  if (
    emittedPaths.length !== recorded.length ||
    recorded.some((module, index) => module.path !== emittedPaths[index])
  ) {
    throw new TypeError('generated package modules do not match its manifest');
  }
  for (const module of emitted.modules) {
    const identity = requiredModuleIdentity(emitted.manifest.semantic, module.path);
    const header = provenanceHeader(emitted.manifest, module.path);
    if (!module.code.startsWith(header)) {
      throw new TypeError(`generated provenance header does not match its manifest: ${module.path}`);
    }
    if (sha256(module.code.slice(header.length)) !== identity.bodySha256) {
      throw new TypeError(`generated module body does not match its manifest: ${module.path}`);
    }
    const sourceMapDigest = module.sourceMap === undefined ? '' : sha256(module.sourceMap.contents);
    if (sourceMapDigest !== identity.sourceMapSha256) {
      throw new TypeError(`generated source map does not match its manifest: ${module.path}`);
    }
  }
  assertHostBoundaries(emitted);
  assertCertificateBodies(emitted);
  if (generatedPackageDigest(recorded) !== emitted.manifest.semantic.generatedBodySha256) {
    throw new TypeError('generated package digest does not match its module bodies');
  }
}

/**
 * A package that declares a host boundary imports the substrate's implementation through one module
 * the consumer provides, and it deliberately contains no second implementation of a host operation:
 * the refinement is about the exported reference body, and a generated definition would be the
 * compiler claiming the boundary instead of naming it. Verification therefore checks the join the
 * artifact can see: no emitted module claims the reserved host path, the emitted tree imports the
 * declared host bindings under the names the manifest records, and nothing else imports the module.
 */
function assertHostBoundaries(emitted: LeanToTypeScriptPackage): void {
  const hosts = emitted.manifest.semantic.hosts;
  if (hosts.length === 0) return;
  const bindings = new Set(hosts.map((host) => host.binding));
  // The substrate provides the host module; a package that declared a boundary must not carry a
  // second implementation of a host operation, so no emitted module may claim its reserved path.
  if (emitted.modules.some((module) => module.path === LEAN_TO_TYPESCRIPT_HOST_MODULE_PATH)) {
    throw new TypeError(
      `the emitted package contains a host module, which the substrate provides: ${LEAN_TO_TYPESCRIPT_HOST_MODULE_PATH}`,
    );
  }
  // Every import of the host module is recorded against its importing module, resolved to the
  // reserved path, so the join reads the artifact's own record rather than re-parsing printed
  // syntax: each declared host binding is imported exactly once, and nothing else is.
  const imported = new Map<string, readonly string[]>();
  for (const module of emitted.modules) {
    const identity = requiredModuleIdentity(emitted.manifest.semantic, module.path);
    if (!identity.imports.includes(LEAN_TO_TYPESCRIPT_HOST_MODULE_PATH)) continue;
    const hostLine = module.code
      .split('\n')
      .find((line) => line.includes(LEAN_TO_TYPESCRIPT_HOST_MODULE_PATH.replace(/\.ts$/u, '.js')));
    if (hostLine === undefined) {
      throw new TypeError(`${module.path} records the substrate's host module as an import but prints no import of it`);
    }
    const names = [...hostLine.matchAll(/\{([^}]*)\}/gu)]
      .flatMap((match) => match[1].split(','))
      .map((name) => name.trim().replace(/^type /u, ''))
      .filter((name) => name.length > 0);
    imported.set(module.path, names);
  }
  for (const [path, names] of imported) {
    const undeclared = names.filter((name) => !bindings.has(name));
    if (undeclared.length > 0) {
      throw new TypeError(
        `${path} imports ${undeclared.join(', ')} from the substrate's host module, which its manifest does not declare`,
      );
    }
  }
  for (const host of hosts) {
    const importing = [...imported.entries()].filter(([, names]) => names.includes(host.binding));
    if (importing.length === 0) {
      throw new TypeError(`the declared host binding ${host.binding} is imported by no emitted module: ${host.host}`);
    }
  }
}

/**
 * A certificate may only claim what the package actually emits: a helper symbol must resolve to
 * exactly one declaration in the generated tree and hash to the recorded digest, and an inline
 * opcode must hash to the one emitted form the registry gives it.
 */
function assertCertificateBodies(emitted: LeanToTypeScriptPackage): void {
  assertRuntimeCertificateBindings(
    loadRuntimeCertificateRegistry().catalog,
    emitted.manifest.semantic.certificates,
    emitted.modules.map((module) => module.code),
  );
}

function requiredModuleIdentity(
  semantic: LeanToTypeScriptSemanticIdentity,
  path: string,
): LeanToTypeScriptModuleIdentity {
  const module = semantic.modules.find((candidate) => candidate.path === path);
  if (module === undefined) throw new TypeError(`generated module is absent from its manifest: ${path}`);
  return module;
}

/** Which recorded environment fields drifted from the environment that just ran. */
export function environmentAttestationDrift(
  recorded: LeanToTypeScriptEnvironmentAttestation,
  observed: LeanToTypeScriptEnvironmentAttestation,
): readonly string[] {
  const drift: string[] = [];
  if (recorded.runtime !== observed.runtime) drift.push(`runtime ${recorded.runtime} -> ${observed.runtime}`);
  if (recorded.typescriptVersion !== observed.typescriptVersion) {
    drift.push(`typescript ${recorded.typescriptVersion} -> ${observed.typescriptVersion}`);
  }
  if (recorded.printerVersion !== observed.printerVersion) {
    drift.push(`typescript printer ${recorded.printerVersion} -> ${observed.printerVersion}`);
  }
  if (recorded.platform !== observed.platform) drift.push(`platform ${recorded.platform} -> ${observed.platform}`);
  const observedInputs = new Map(observed.inputs.map((input) => [input.identity, input.sha256]));
  for (const input of recorded.inputs) {
    const current = observedInputs.get(input.identity);
    if (current === undefined) drift.push(`removed ${input.identity}`);
    else if (current !== input.sha256) drift.push(`changed ${input.identity}`);
  }
  const recordedInputs = new Set(recorded.inputs.map((input) => input.identity));
  for (const input of observed.inputs) {
    if (!recordedInputs.has(input.identity)) drift.push(`added ${input.identity}`);
  }
  if (JSON.stringify(recorded.runtimeConformance) !== JSON.stringify(observed.runtimeConformance)) {
    drift.push('runtime certificate conformance changed');
  }
  return drift.sort(compareCodePoints);
}

function canonicalSemanticIdentity(semantic: LeanToTypeScriptSemanticIdentity): LeanToTypeScriptSemanticIdentity {
  return {
    fragmentVersion: semantic.fragmentVersion,
    entryModule: semantic.entryModule,
    leanProjectPath: semantic.leanProjectPath,
    declarations: semantic.declarations,
    leanToolchain: {
      identity: semantic.leanToolchain.identity,
      leanVersion: semantic.leanToolchain.leanVersion,
      lakeVersion: semantic.leanToolchain.lakeVersion,
    },
    modules: semantic.modules.map((module) => ({
      path: module.path,
      leanModule: module.leanModule,
      imports: module.imports,
      declarations: module.declarations.map((declaration) => ({
        declaration: declaration.declaration,
        emitted: declaration.emitted,
        line: declaration.line,
        span: {
          source: declaration.span.source,
          startLine: declaration.span.startLine,
          startColumn: declaration.span.startColumn,
          endLine: declaration.span.endLine,
          endColumn: declaration.span.endColumn,
        },
      })),
      bodySha256: module.bodySha256,
      sourceMapSha256: module.sourceMapSha256,
    })),
    closure: semantic.closure.map((entry) => ({
      declaration: entry.declaration,
      module: entry.module,
      role: entry.role,
      reason: entry.reason,
    })),
    inputs: semantic.inputs,
    inputClosureSha256: semantic.inputClosureSha256,
    semanticIrSha256: semantic.semanticIrSha256,
    certificates: semantic.certificates.map((certificate) => ({
      opcode: certificate.opcode,
      runtimeSymbol: certificate.runtimeSymbol,
      declaration: certificate.declaration,
      runtimeBodySha256: certificate.runtimeBodySha256,
    })),
    generatedBodySha256: semantic.generatedBodySha256,
    hosts: semantic.hosts.map((host) => ({
      declaration: host.declaration,
      host: host.host,
      binding: host.binding,
      module: host.module,
    })),
    helpers: semantic.helpers.map((helper) => ({ role: helper.role, declaration: helper.declaration })),
    codecs: semantic.codecs.map((codec) => ({
      declaration: codec.declaration,
      type: codec.type,
      statics: codec.statics,
    })),
  };
}
/**
 * Joins the artifact against the one registry on disk. A recorded certificate must name an opcode
 * the registry certifies, with the runtime symbol the registry gives it, and the attestations must
 * cover exactly that opcode's assumption closure. Drift between artifact and proof is a refusal,
 * not a discrepancy the reader has to notice.
 */
function assertCertificateConformance(
  semantic: LeanToTypeScriptSemanticIdentity,
  environment: LeanToTypeScriptEnvironmentAttestation,
): void {
  const { catalog } = loadRuntimeCertificateRegistry();
  const expected = semantic.certificates.flatMap((binding) => {
    const certificate = catalog.certificates.find((entry) => entry.opcode === binding.opcode);
    if (certificate === undefined) {
      throw new TypeError(`recorded certificate names an opcode the registry does not certify: ${binding.opcode}`);
    }
    if (certificate.runtimeSymbol !== binding.runtimeSymbol) {
      throw new TypeError(`recorded certificate drifts from the registry runtime symbol: ${binding.opcode}`);
    }
    return certificate.assumptions.map((id) => {
      const assumption = catalog.assumptions.find((entry) => entry.id === id);
      if (assumption === undefined) {
        throw new TypeError(`registry certificate ${binding.opcode} names unknown assumption ${id}`);
      }
      return { binding, assumption };
    });
  });
  if (environment.runtimeConformance.length !== expected.length) {
    throw new TypeError('runtime conformance does not exactly cover the certified assumption closure');
  }
  const semanticInputs = new Map(semantic.inputs.map((input) => [input.identity, input.sha256]));
  const environmentInputs = new Map(environment.inputs.map((input) => [input.identity, input.sha256]));
  const seen = new Set<string>();
  for (const attestation of environment.runtimeConformance) {
    const key = `${attestation.certificate}:${attestation.assumption}`;
    if (seen.has(key)) throw new TypeError(`duplicate runtime conformance attestation: ${key}`);
    seen.add(key);
    const matched = expected.find(
      ({ binding, assumption }) =>
        binding.opcode === attestation.certificate && assumption.id === attestation.assumption,
    );
    if (matched === undefined) throw new TypeError(`unknown runtime conformance attestation: ${key}`);
    if (
      attestation.binaryInput !== RUNTIME_BINARY_INPUT ||
      attestation.evidenceInput !== RUNTIME_EVIDENCE_INPUT ||
      attestation.oracle !== matched.assumption.oracle ||
      attestation.runtimeSymbol !== matched.binding.runtimeSymbol ||
      attestation.runtimeBodySha256 !== matched.binding.runtimeBodySha256 ||
      environmentInputs.get(RUNTIME_BINARY_INPUT) !== attestation.binarySha256 ||
      semanticInputs.get(RUNTIME_EVIDENCE_INPUT) !== attestation.oracleSha256
    ) {
      throw new TypeError(`runtime conformance attestation does not match certificate: ${key}`);
    }
  }
}

function canonicalEnvironmentAttestation(
  environment: LeanToTypeScriptEnvironmentAttestation,
): LeanToTypeScriptEnvironmentAttestation {
  return {
    runtime: environment.runtime,
    typescriptVersion: environment.typescriptVersion,
    printerVersion: environment.printerVersion,
    platform: environment.platform,
    inputs: environment.inputs,
    inputClosureSha256: environment.inputClosureSha256,
    runtimeConformance: environment.runtimeConformance.map((attestation) => ({ ...attestation })),
  };
}

function sha256(value: string): string {
  return `sha256:${createHash('sha256').update(value).digest('hex')}`;
}

export function decodePackage(value: unknown): LeanToTypeScriptPackage {
  const emitted = record(value, 'Lean to TypeScript package');
  exactKeys(emitted, ['modules', 'manifest'], 'Lean to TypeScript package');
  const modules = array(emitted['modules'], 'Lean to TypeScript package modules');
  if (modules.length === 0) throw new TypeError('Lean to TypeScript package must emit at least one module');
  return {
    modules: modules.map((module, index) => {
      const location = `Lean to TypeScript package modules[${index}]`;
      const decoded = record(module, location);
      exactKeys(decoded, ['path', 'code', 'sourceMap'], location);
      const sourceMap = decoded['sourceMap'];
      if (sourceMap === undefined) {
        return {
          path: generatedPath(decoded['path'], `${location} path`),
          code: string(decoded['code'], `${location} code`),
          sourceMap: undefined,
        };
      }
      const map = record(sourceMap, `${location} source map`);
      exactKeys(map, ['path', 'contents'], `${location} source map`);
      return {
        path: generatedPath(decoded['path'], `${location} path`),
        code: string(decoded['code'], `${location} code`),
        sourceMap: {
          path: generatedPath(map['path'], `${location} source map path`),
          contents: string(map['contents'], `${location} source map contents`),
        },
      };
    }),
    manifest: decodeManifest(emitted['manifest']),
  };
}

/**
 * One shared major. Every decoder — generation, verification, roundtrip — reads the same constant
 * and accepts any minor revision within it, so a schema bump that adds a field does not strand
 * the other readers at a refusal until each one is updated.
 */
export function decodeManifest(value: unknown): LeanToTypeScriptManifest {
  const manifest = record(value, 'Lean to TypeScript manifest');
  const schemaVersion = manifest['schemaVersion'];
  if (
    typeof schemaVersion !== 'number' ||
    !Number.isSafeInteger(schemaVersion) ||
    Math.floor(schemaVersion / 1000) !== Math.floor(LEAN_TO_TYPESCRIPT_MANIFEST_SCHEMA_VERSION / 1000)
  ) {
    throw new TypeError('unsupported Lean to TypeScript manifest schema');
  }
  return canonicalManifest({
    schemaVersion: LEAN_TO_TYPESCRIPT_MANIFEST_SCHEMA_VERSION,
    semantic: decodeSemanticIdentity(manifest['semantic']),
    environment: decodeEnvironmentAttestation(manifest['environment']),
  });
}

function decodeSemanticIdentity(value: unknown): LeanToTypeScriptSemanticIdentity {
  const location = 'Lean to TypeScript manifest semantic identity';
  const semantic = record(value, location);
  exactKeys(
    semantic,
    [
      'fragmentVersion',
      'entryModule',
      'leanProjectPath',
      'declarations',
      'leanToolchain',
      'modules',
      'closure',
      'inputs',
      'inputClosureSha256',
      'semanticIrSha256',
      'certificates',
      'generatedBodySha256',
      'hosts',
      'helpers',
      'codecs',
    ],
    location,
  );
  const declarations = strings(semantic['declarations'], `${location} declarations`);
  requireCanonicalOrder(declarations, `${location} declarations`);
  const leanToolchain = record(semantic['leanToolchain'], `${location} Lean toolchain`);
  exactKeys(leanToolchain, ['identity', 'leanVersion', 'lakeVersion'], `${location} Lean toolchain`);
  const modules = array(semantic['modules'], `${location} modules`).map((module, index) =>
    decodeModuleIdentity(module, `${location} modules[${index}]`),
  );
  if (modules.length === 0) throw new TypeError(`${location} modules must be nonempty`);
  requireCanonicalOrder(
    modules.map((module) => module.path),
    `${location} module paths`,
  );
  const closure = array(semantic['closure'], `${location} closure`).map((entry, index) =>
    decodeClosureEntry(entry, `${location} closure[${index}]`),
  );
  requireCanonicalOrder(
    closure.map((entry) => entry.declaration),
    `${location} closure declarations`,
  );
  return {
    fragmentVersion: string(semantic['fragmentVersion'], `${location} fragment version`),
    entryModule: string(semantic['entryModule'], `${location} entry module`),
    leanProjectPath: relativeDirectory(semantic['leanProjectPath'], `${location} Lean project path`),
    declarations,
    leanToolchain: {
      identity: string(leanToolchain['identity'], `${location} toolchain identity`),
      leanVersion: string(leanToolchain['leanVersion'], `${location} Lean version`),
      lakeVersion: string(leanToolchain['lakeVersion'], `${location} Lake version`),
    },
    modules,
    closure,
    ...decodeInputClosure(semantic, 'semantic', location),
    semanticIrSha256: digest(semantic['semanticIrSha256'], `${location} semantic IR`),
    certificates: decodeCertificateBindings(semantic['certificates'], `${location} certificates`),
    generatedBodySha256: digest(semantic['generatedBodySha256'], `${location} generated body`),
    hosts: decodeHostBoundaries(semantic['hosts'], `${location} hosts`),
    helpers: decodeHelperDeclarations(semantic['helpers'], `${location} helpers`),
    codecs: decodeCodecSurfaces(semantic['codecs'], `${location} codecs`),
  };
}

function decodeModuleIdentity(value: unknown, location: string): LeanToTypeScriptModuleIdentity {
  const module = record(value, location);
  exactKeys(module, ['path', 'leanModule', 'imports', 'declarations', 'bodySha256', 'sourceMapSha256'], location);
  const imports = array(module['imports'], `${location} imports`).map((entry, index) =>
    generatedPath(entry, `${location} imports[${index}]`),
  );
  requireCanonicalOrder(imports, `${location} imports`);
  const declarations = array(module['declarations'], `${location} declarations`).map((entry, index) =>
    decodeGeneratedDeclaration(entry, `${location} declarations[${index}]`),
  );
  const sourceMapSha256 = module['sourceMapSha256'];
  return {
    path: generatedPath(module['path'], `${location} path`),
    leanModule: optionalName(module['leanModule'], `${location} Lean module`),
    imports,
    declarations,
    bodySha256: digest(module['bodySha256'], `${location} body digest`),
    sourceMapSha256: sourceMapSha256 === '' ? '' : digest(sourceMapSha256, `${location} source map digest`),
  };
}

function decodeGeneratedDeclaration(value: unknown, location: string): LeanToTypeScriptGeneratedDeclaration {
  const declaration = record(value, location);
  exactKeys(declaration, ['declaration', 'emitted', 'line', 'span'], location);
  return {
    declaration: string(declaration['declaration'], `${location} declaration`),
    emitted: string(declaration['emitted'], `${location} emitted name`),
    line: position(declaration['line'], `${location} line`),
    span: decodeSourceSpan(declaration['span'], `${location} span`),
  };
}

function decodeSourceSpan(value: unknown, location: string): LeanToTypeScriptSourceSpan {
  const span = record(value, location);
  exactKeys(span, ['source', 'startLine', 'startColumn', 'endLine', 'endColumn'], location);
  return {
    source: string(span['source'], `${location} source`),
    startLine: position(span['startLine'], `${location} start line`),
    startColumn: offset(span['startColumn'], `${location} start column`),
    endLine: position(span['endLine'], `${location} end line`),
    endColumn: offset(span['endColumn'], `${location} end column`),
  };
}

function decodeClosureEntry(value: unknown, location: string): LeanToTypeScriptClosureEntry {
  const entry = record(value, location);
  exactKeys(entry, ['declaration', 'module', 'role', 'reason'], location);
  const role = declarationRole(entry['role'], `${location} role`);
  const reason = entry['reason'];
  if (typeof reason !== 'string') throw new TypeError(`${location} reason must be a string`);
  if ((role === 'emitted') !== (reason === '')) {
    throw new TypeError(`${location} reason must be empty exactly for an emitted declaration`);
  }
  return {
    declaration: string(entry['declaration'], `${location} declaration`),
    module: optionalName(entry['module'], `${location} module`),
    role,
    reason,
  };
}

function declarationRole(value: unknown, location: string): LeanToTypeScriptDeclarationRole {
  switch (value) {
    case 'emitted':
    case 'erased':
    case 'runtime-boundary':
      return value;
    default:
      throw new TypeError(`${location} has unknown role ${String(value)}`);
  }
}

function decodeEnvironmentAttestation(value: unknown): LeanToTypeScriptEnvironmentAttestation {
  const location = 'Lean to TypeScript manifest environment attestation';
  const environment = record(value, location);
  exactKeys(
    environment,
    [
      'runtime',
      'typescriptVersion',
      'printerVersion',
      'platform',
      'inputs',
      'inputClosureSha256',
      'runtimeConformance',
    ],
    location,
  );
  return {
    runtime: string(environment['runtime'], `${location} runtime`),
    typescriptVersion: string(environment['typescriptVersion'], `${location} TypeScript version`),
    printerVersion: string(environment['printerVersion'], `${location} TypeScript printer version`),
    platform: string(environment['platform'], `${location} platform`),
    ...decodeInputClosure(environment, 'environment', location),
    runtimeConformance: decodeRuntimeConformance(environment['runtimeConformance'], `${location} runtime conformance`),
  };
}
function decodeCertificateBindings(value: unknown, location: string): readonly RuntimeCertificateBinding[] {
  const bindings = array(value, location).map((entry, index): RuntimeCertificateBinding => {
    const bindingLocation = `${location}[${index}]`;
    const binding = record(entry, bindingLocation);
    exactKeys(binding, ['opcode', 'runtimeSymbol', 'declaration', 'runtimeBodySha256'], bindingLocation);
    const declaration = binding['declaration'];
    if (typeof declaration !== 'string') throw new TypeError(`${bindingLocation}.declaration must be a string`);
    return {
      opcode: certificateOpcode(binding['opcode'], `${bindingLocation}.opcode`),
      runtimeSymbol: taggedRuntimeSymbol(binding['runtimeSymbol'], `${bindingLocation}.runtimeSymbol`),
      declaration: declaration === '' ? '' : bindingName(declaration, `${bindingLocation}.declaration`),
      runtimeBodySha256: digest(binding['runtimeBodySha256'], `${bindingLocation}.runtimeBodySha256`),
    };
  });
  requireCanonicalOrder(
    bindings.map((binding) => binding.opcode),
    location,
  );
  return bindings;
}

/**
 * The host surface the package imports. Every row names a host identity the compiler admits, so a
 * manifest cannot record a boundary against an operation the substrate never published, and the
 * rows are ordered by the Lean declaration they came from so the record is a function of the
 * program rather than of emission order.
 */
function decodeHostBoundaries(value: unknown, location: string): readonly LeanToTypeScriptHostBoundary[] {
  const hosts = array(value, location).map((entry, index): LeanToTypeScriptHostBoundary => {
    const hostLocation = `${location}[${index}]`;
    const host = record(entry, hostLocation);
    exactKeys(host, ['declaration', 'host', 'binding', 'module'], hostLocation);
    const wire = string(host['host'], `${hostLocation}.host`);
    if (!Object.hasOwn(LEAN_HOST_OPCODES, wire)) {
      throw new TypeError(`${hostLocation}.host is not a registered host opcode: ${wire}`);
    }
    return {
      declaration: string(host['declaration'], `${hostLocation}.declaration`),
      host: wire,
      binding: bindingName(host['binding'], `${hostLocation}.binding`),
      module: string(host['module'], `${hostLocation}.module`),
    };
  });
  requireCanonicalOrder(
    hosts.map((host) => host.declaration),
    location,
  );
  return hosts;
}

function decodeHelperDeclarations(value: unknown, location: string): readonly LeanToTypeScriptHelperDeclaration[] {
  const helpers = array(value, location).map((entry, index): LeanToTypeScriptHelperDeclaration => {
    const helperLocation = `${location}[${index}]`;
    const helper = record(entry, helperLocation);
    exactKeys(helper, ['role', 'declaration'], helperLocation);
    const role = string(helper['role'], `${helperLocation}.role`);
    if (!LEAN_RUNTIME_HELPER_ROLES.some((admitted) => admitted === role)) {
      throw new TypeError(`${helperLocation}.role is not a generated helper role: ${role}`);
    }
    return { role, declaration: bindingName(helper['declaration'], `${helperLocation}.declaration`) };
  });
  requireCanonicalOrder(
    helpers.map((helper) => helper.role),
    location,
  );
  return helpers;
}

/** The three statics a structure's generated codec carries, recorded per data type. */
const CODEC_STATICS: readonly string[] = ['equals', 'fromData', 'toData'];

function decodeCodecSurfaces(value: unknown, location: string): readonly LeanToTypeScriptCodecSurface[] {
  const codecs = array(value, location).map((entry, index): LeanToTypeScriptCodecSurface => {
    const codecLocation = `${location}[${index}]`;
    const codec = record(entry, codecLocation);
    exactKeys(codec, ['declaration', 'type', 'statics'], codecLocation);
    const statics = strings(codec['statics'], `${codecLocation}.statics`);
    requireCanonicalOrder(statics, `${codecLocation}.statics`);
    for (const member of statics) {
      if (!CODEC_STATICS.includes(member)) {
        throw new TypeError(`${codecLocation}.statics names ${member}, which is not a generated codec static`);
      }
    }
    return {
      declaration: string(codec['declaration'], `${codecLocation}.declaration`),
      type: bindingName(codec['type'], `${codecLocation}.type`),
      statics,
    };
  });
  requireCanonicalOrder(
    codecs.map((codec) => codec.declaration),
    location,
  );
  return codecs;
}

function decodeRuntimeConformance(value: unknown, location: string): readonly RuntimeConformanceAttestation[] {
  const attestations = array(value, location).map((entry, index): RuntimeConformanceAttestation => {
    const attestationLocation = `${location}[${index}]`;
    const attestation = record(entry, attestationLocation);
    exactKeys(
      attestation,
      [
        'certificate',
        'assumption',
        'oracle',
        'binaryInput',
        'binarySha256',
        'evidenceInput',
        'oracleSha256',
        'runtimeSymbol',
        'runtimeBodySha256',
      ],
      attestationLocation,
    );
    return {
      certificate: certificateOpcode(attestation['certificate'], `${attestationLocation}.certificate`),
      assumption: string(attestation['assumption'], `${attestationLocation}.assumption`),
      oracle: string(attestation['oracle'], `${attestationLocation}.oracle`),
      binaryInput: string(attestation['binaryInput'], `${attestationLocation}.binaryInput`),
      binarySha256: digest(attestation['binarySha256'], `${attestationLocation}.binarySha256`),
      evidenceInput: string(attestation['evidenceInput'], `${attestationLocation}.evidenceInput`),
      oracleSha256: digest(attestation['oracleSha256'], `${attestationLocation}.oracleSha256`),
      runtimeSymbol: taggedRuntimeSymbol(attestation['runtimeSymbol'], `${attestationLocation}.runtimeSymbol`),
      runtimeBodySha256: digest(attestation['runtimeBodySha256'], `${attestationLocation}.runtimeBodySha256`),
    };
  });
  requireCanonicalOrder(
    attestations.map((attestation) => `${attestation.certificate}:${attestation.assumption}`),
    location,
  );
  return attestations;
}

function decodeInputClosure(
  value: Record<string, unknown>,
  plane: LeanToTypeScriptPlane,
  location: string,
): { readonly inputs: readonly LeanToTypeScriptInput[]; readonly inputClosureSha256: string } {
  const inputs = array(value['inputs'], `${location} inputs`).map((input, index) =>
    decodeInput(input, `${location} inputs[${index}]`),
  );
  if (inputs.length === 0) throw new TypeError(`${location} inputs must be nonempty`);
  requireCanonicalOrder(
    inputs.map((input) => input.identity),
    `${location} input identities`,
  );
  for (const input of inputs) {
    if (LEAN_TO_TYPESCRIPT_INPUT_PLANES[input.kind] !== plane) {
      throw new TypeError(`${location} input ${input.identity} belongs to the other identity plane`);
    }
  }
  const inputClosureSha256 = digest(value['inputClosureSha256'], `${location} input closure`);
  if (sha256(JSON.stringify(inputs)) !== inputClosureSha256) {
    throw new TypeError(`${location} input closure does not match its inputs`);
  }
  return { inputs, inputClosureSha256 };
}

function decodeInput(value: unknown, location: string): LeanToTypeScriptInput {
  const input = record(value, location);
  exactKeys(input, ['kind', 'identity', 'sha256'], location);
  return {
    kind: inputKind(input['kind'], `${location} kind`),
    identity: string(input['identity'], `${location} identity`),
    sha256: digest(input['sha256'], `${location} digest`),
  };
}

function certificateOpcode(value: unknown, location: string): string {
  const decoded = string(value, location);
  if (!/^[a-z][A-Za-z0-9]*(?:[.-][a-zA-Z0-9]+)*$/u.test(decoded)) {
    throw new TypeError(`${location} is not a canonical runtime opcode`);
  }
  return decoded;
}

function bindingName(value: unknown, location: string): string {
  const decoded = string(value, location);
  if (!/^[$A-Z_a-z][$\w]*$/u.test(decoded) || decoded === 'arguments' || decoded === 'eval') {
    throw new TypeError(`${location} is not a safe TypeScript binding name`);
  }
  return decoded;
}

function record(value: unknown, location: string): Record<string, unknown> {
  if (!isRecord(value)) throw new TypeError(`${location} must be an object`);
  return value;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function array(value: unknown, location: string): readonly unknown[] {
  if (!Array.isArray(value)) throw new TypeError(`${location} must be an array`);
  return value;
}

function string(value: unknown, location: string): string {
  if (typeof value !== 'string' || value.length === 0) throw new TypeError(`${location} must be a nonempty string`);
  return value;
}

function inputKind(value: unknown, location: string): LeanToTypeScriptInputKind {
  switch (value) {
    case 'compiler-runtime':
    case 'compiler-source':
    case 'lean-module':
    case 'lean-project':
    case 'lean-source':
    case 'lean-toolchain':
      return value;
    default:
      throw new TypeError(`${location} has unknown kind ${String(value)}`);
  }
}

function strings(value: unknown, location: string): readonly string[] {
  const values = array(value, location).map((entry, index) => string(entry, `${location}[${index}]`));
  if (values.length === 0) throw new TypeError(`${location} must be nonempty`);
  return values;
}

function digest(value: unknown, location: string): string {
  const hash = string(value, location);
  if (!/^sha256:[0-9a-f]{64}$/u.test(hash)) throw new TypeError(`${location} must be a SHA-256 digest`);
  return hash;
}

/**
 * A path inside the generated package: relative, forward-slashed, and free of `.` or `..`, so a
 * manifest can never name a destination outside the tree the compiler was asked to write.
 */
function generatedPath(value: unknown, location: string): string {
  const path = string(value, location);
  const segments = path.split('/');
  if (path.startsWith('/') || segments.some((segment) => segment === '' || segment === '.' || segment === '..')) {
    throw new TypeError(`${location} must be a relative path inside the generated package: ${path}`);
  }
  return path;
}

/**
 * A relative directory inside or above the generated package: forward-slashed, never absolute,
 * and never a bare `.` segment, so a recorded base can be joined without re-parsing it.
 */
function relativeDirectory(value: unknown, location: string): string {
  const path = string(value, location);
  const segments = path.split('/');
  if (path.startsWith('/') || segments.some((segment) => segment === '' || segment === '.')) {
    throw new TypeError(`${location} must be a relative forward-slashed directory: ${path}`);
  }
  return path;
}

/** A name the schema allows to be absent, recorded as the empty string rather than omitted. */
function optionalName(value: unknown, location: string): string {
  if (value === '') return '';
  return string(value, location);
}

function position(value: unknown, location: string): number {
  if (!Number.isSafeInteger(value) || Number(value) < 1) throw new TypeError(`${location} must be a 1-based line`);
  return Number(value);
}

function offset(value: unknown, location: string): number {
  if (!Number.isSafeInteger(value) || Number(value) < 0) throw new TypeError(`${location} must be a column offset`);
  return Number(value);
}

function exactKeys(value: Record<string, unknown>, expected: readonly string[], location: string): void {
  const actual = Object.keys(value).sort(compareCodePoints);
  const canonical = [...expected].sort(compareCodePoints);
  if (actual.length !== canonical.length || actual.some((key, index) => key !== canonical[index])) {
    throw new TypeError(`${location} fields must be exactly ${canonical.join(', ')}`);
  }
}

function requireCanonicalOrder(values: readonly string[], location: string): void {
  for (let index = 1; index < values.length; index += 1) {
    const previous = values[index - 1];
    const current = values[index];
    if (previous === undefined || current === undefined || compareCodePoints(previous, current) >= 0) {
      throw new TypeError(`${location} must be strictly ordered and unique`);
    }
  }
}
