import { createHash } from 'node:crypto';
import {
  LEAN_TO_TYPESCRIPT_INPUT_PLANES,
  type LeanToTypeScriptClosureEntry,
  type LeanToTypeScriptDeclarationRole,
  type LeanToTypeScriptEnvironmentAttestation,
  type LeanToTypeScriptGeneratedDeclaration,
  type LeanToTypeScriptInput,
  type LeanToTypeScriptInputKind,
  type LeanToTypeScriptManifest,
  type LeanToTypeScriptModuleIdentity,
  type LeanToTypeScriptPackage,
  type LeanToTypeScriptPlane,
  type LeanToTypeScriptSemanticIdentity,
  type LeanToTypeScriptSourceSpan,
} from './artifact.js';
import { compareCodePoints } from './ordering.js';

export const LEAN_TO_TYPESCRIPT_MANIFEST_SCHEMA_VERSION = 3;

/**
 * How many lines the provenance header occupies. The header is a fixed template of one line per
 * field, so the count is a property of the template and not of the values. Emission needs it
 * before the manifest exists, to place each declaration's generated line, and
 * `provenanceHeader` asserts the rendered header still matches, so it cannot drift.
 */
export const PROVENANCE_HEADER_LINES = 17;

/**
 * The provenance header carries the semantic identity only. Nothing about the machine that
 * ran the compiler appears in the generated bytes, so re-running the same compiler over the
 * same Lean sources under a different runtime reproduces the artifact byte for byte.
 *
 * Each generated module names itself and the package it belongs to: `Lean module` is the source
 * this file is the image of, `Generated module` is its path inside the package, and the digests
 * bind the whole package, so no single file can be refreshed in isolation.
 */
export function provenanceHeader(manifest: LeanToTypeScriptManifest, path: string): string {
  const semantic = canonicalSemanticIdentity(manifest.semantic);
  const module = requiredModuleIdentity(semantic, path);
  const lines = [
    '/*',
    ' * Generated by TSLean from kernel-checked Lean declarations.',
    ` * Fragment: ${semantic.fragmentVersion}`,
    ` * Lean module: ${module.leanModule === '' ? '(generated package runtime)' : module.leanModule}`,
    ` * Generated module: ${module.path}`,
    ` * Package entry module: ${semantic.entryModule}`,
    ` * Semantic identity: ${semanticIdentityDigest(semantic)}`,
    ` * Input closure: ${semantic.inputClosureSha256}`,
    ` * Semantic IR: ${semantic.semanticIrSha256}`,
    ` * Generated module body: ${module.bodySha256}`,
    ` * Generated package body: ${semantic.generatedBodySha256}`,
    ` * Lean toolchain: ${semantic.leanToolchain.identity}`,
    ` * Lean: ${semantic.leanToolchain.leanVersion}`,
    ` * Lake: ${semantic.leanToolchain.lakeVersion}`,
    ' * Environment attestation: recorded in the manifest sidecar; it does not affect these bytes.',
    ' * Evidence boundary: generation is checked and differential tests are empirical; no refinement theorem is claimed.',
    ' */',
    '',
  ];
  if (lines.length - 1 !== PROVENANCE_HEADER_LINES) {
    throw new TypeError('provenance header line count no longer matches PROVENANCE_HEADER_LINES');
  }
  return lines.join('\n');
}

/** One digest over every generated module body, in path order: the package's own identity. */
export function generatedPackageDigest(
  modules: readonly { readonly path: string; readonly bodySha256: string }[],
): string {
  return sha256(JSON.stringify(modules.map((module) => [module.path, module.bodySha256])));
}

export function semanticIdentityDigest(semantic: LeanToTypeScriptSemanticIdentity): string {
  return sha256(JSON.stringify(canonicalSemanticIdentity(semantic)));
}

export function environmentAttestationDigest(environment: LeanToTypeScriptEnvironmentAttestation): string {
  return sha256(JSON.stringify(canonicalEnvironmentAttestation(environment)));
}

export function canonicalManifest(manifest: LeanToTypeScriptManifest): LeanToTypeScriptManifest {
  return {
    schemaVersion: LEAN_TO_TYPESCRIPT_MANIFEST_SCHEMA_VERSION,
    semantic: canonicalSemanticIdentity(manifest.semantic),
    environment: canonicalEnvironmentAttestation(manifest.environment),
  };
}

/**
 * Every generated module agrees with the manifest that describes it: its header is the exact
 * header the semantic identity produces, its body hashes to the digest recorded for its path,
 * and the recorded module set is exactly the emitted one.
 */
export function verifyLeanToTypeScriptPackage(value: unknown): asserts value is LeanToTypeScriptPackage {
  const emitted = decodePackage(value);
  const recorded = emitted.manifest.semantic.modules;
  const emittedPaths = emitted.modules.map((module) => module.path);
  if (
    emittedPaths.length !== recorded.length ||
    recorded.some((module, index) => module.path !== emittedPaths[index])
  ) {
    throw new TypeError('generated package modules do not match its manifest');
  }
  for (const module of emitted.modules) {
    const identity = requiredModuleIdentity(emitted.manifest.semantic, module.path);
    const header = provenanceHeader(emitted.manifest, module.path);
    if (!module.code.startsWith(header)) {
      throw new TypeError(`generated provenance header does not match its manifest: ${module.path}`);
    }
    if (sha256(module.code.slice(header.length)) !== identity.bodySha256) {
      throw new TypeError(`generated module body does not match its manifest: ${module.path}`);
    }
    const sourceMapDigest = module.sourceMap === undefined ? '' : sha256(module.sourceMap.contents);
    if (sourceMapDigest !== identity.sourceMapSha256) {
      throw new TypeError(`generated source map does not match its manifest: ${module.path}`);
    }
  }
  if (generatedPackageDigest(recorded) !== emitted.manifest.semantic.generatedBodySha256) {
    throw new TypeError('generated package digest does not match its module bodies');
  }
}

function requiredModuleIdentity(
  semantic: LeanToTypeScriptSemanticIdentity,
  path: string,
): LeanToTypeScriptModuleIdentity {
  const module = semantic.modules.find((candidate) => candidate.path === path);
  if (module === undefined) throw new TypeError(`generated module is absent from its manifest: ${path}`);
  return module;
}

/** Which recorded environment fields drifted from the environment that just ran. */
export function environmentAttestationDrift(
  recorded: LeanToTypeScriptEnvironmentAttestation,
  observed: LeanToTypeScriptEnvironmentAttestation,
): readonly string[] {
  const drift: string[] = [];
  if (recorded.runtime !== observed.runtime) drift.push(`runtime ${recorded.runtime} -> ${observed.runtime}`);
  if (recorded.typescriptVersion !== observed.typescriptVersion) {
    drift.push(`typescript ${recorded.typescriptVersion} -> ${observed.typescriptVersion}`);
  }
  if (recorded.platform !== observed.platform) drift.push(`platform ${recorded.platform} -> ${observed.platform}`);
  const observedInputs = new Map(observed.inputs.map((input) => [input.identity, input.sha256]));
  for (const input of recorded.inputs) {
    const current = observedInputs.get(input.identity);
    if (current === undefined) drift.push(`removed ${input.identity}`);
    else if (current !== input.sha256) drift.push(`changed ${input.identity}`);
  }
  const recordedInputs = new Set(recorded.inputs.map((input) => input.identity));
  for (const input of observed.inputs) {
    if (!recordedInputs.has(input.identity)) drift.push(`added ${input.identity}`);
  }
  return drift.sort(compareCodePoints);
}

function canonicalSemanticIdentity(semantic: LeanToTypeScriptSemanticIdentity): LeanToTypeScriptSemanticIdentity {
  return {
    fragmentVersion: semantic.fragmentVersion,
    entryModule: semantic.entryModule,
    declarations: semantic.declarations,
    leanToolchain: {
      identity: semantic.leanToolchain.identity,
      leanVersion: semantic.leanToolchain.leanVersion,
      lakeVersion: semantic.leanToolchain.lakeVersion,
    },
    modules: semantic.modules.map((module) => ({
      path: module.path,
      leanModule: module.leanModule,
      imports: module.imports,
      declarations: module.declarations.map((declaration) => ({
        declaration: declaration.declaration,
        emitted: declaration.emitted,
        line: declaration.line,
        span: {
          source: declaration.span.source,
          startLine: declaration.span.startLine,
          startColumn: declaration.span.startColumn,
          endLine: declaration.span.endLine,
          endColumn: declaration.span.endColumn,
        },
      })),
      bodySha256: module.bodySha256,
      sourceMapSha256: module.sourceMapSha256,
    })),
    closure: semantic.closure.map((entry) => ({
      declaration: entry.declaration,
      module: entry.module,
      role: entry.role,
      reason: entry.reason,
    })),
    inputs: semantic.inputs,
    inputClosureSha256: semantic.inputClosureSha256,
    semanticIrSha256: semantic.semanticIrSha256,
    generatedBodySha256: semantic.generatedBodySha256,
  };
}

function canonicalEnvironmentAttestation(
  environment: LeanToTypeScriptEnvironmentAttestation,
): LeanToTypeScriptEnvironmentAttestation {
  return {
    runtime: environment.runtime,
    typescriptVersion: environment.typescriptVersion,
    platform: environment.platform,
    inputs: environment.inputs,
    inputClosureSha256: environment.inputClosureSha256,
  };
}

function sha256(value: string): string {
  return `sha256:${createHash('sha256').update(value).digest('hex')}`;
}

export function decodePackage(value: unknown): LeanToTypeScriptPackage {
  const emitted = record(value, 'Lean to TypeScript package');
  exactKeys(emitted, ['modules', 'manifest'], 'Lean to TypeScript package');
  const modules = array(emitted['modules'], 'Lean to TypeScript package modules');
  if (modules.length === 0) throw new TypeError('Lean to TypeScript package must emit at least one module');
  return {
    modules: modules.map((module, index) => {
      const location = `Lean to TypeScript package modules[${index}]`;
      const decoded = record(module, location);
      exactKeys(decoded, ['path', 'code', 'sourceMap'], location);
      const sourceMap = decoded['sourceMap'];
      if (sourceMap === undefined) {
        return {
          path: generatedPath(decoded['path'], `${location} path`),
          code: string(decoded['code'], `${location} code`),
          sourceMap: undefined,
        };
      }
      const map = record(sourceMap, `${location} source map`);
      exactKeys(map, ['path', 'contents'], `${location} source map`);
      return {
        path: generatedPath(decoded['path'], `${location} path`),
        code: string(decoded['code'], `${location} code`),
        sourceMap: {
          path: generatedPath(map['path'], `${location} source map path`),
          contents: string(map['contents'], `${location} source map contents`),
        },
      };
    }),
    manifest: decodeManifest(emitted['manifest']),
  };
}

export function decodeManifest(value: unknown): LeanToTypeScriptManifest {
  const manifest = record(value, 'Lean to TypeScript manifest');
  exactKeys(manifest, ['schemaVersion', 'semantic', 'environment'], 'Lean to TypeScript manifest');
  if (manifest['schemaVersion'] !== LEAN_TO_TYPESCRIPT_MANIFEST_SCHEMA_VERSION) {
    throw new TypeError('unsupported Lean to TypeScript manifest schema');
  }
  return canonicalManifest({
    schemaVersion: LEAN_TO_TYPESCRIPT_MANIFEST_SCHEMA_VERSION,
    semantic: decodeSemanticIdentity(manifest['semantic']),
    environment: decodeEnvironmentAttestation(manifest['environment']),
  });
}

function decodeSemanticIdentity(value: unknown): LeanToTypeScriptSemanticIdentity {
  const location = 'Lean to TypeScript manifest semantic identity';
  const semantic = record(value, location);
  exactKeys(
    semantic,
    [
      'fragmentVersion',
      'entryModule',
      'declarations',
      'leanToolchain',
      'modules',
      'closure',
      'inputs',
      'inputClosureSha256',
      'semanticIrSha256',
      'generatedBodySha256',
    ],
    location,
  );
  const declarations = strings(semantic['declarations'], `${location} declarations`);
  requireCanonicalOrder(declarations, `${location} declarations`);
  const leanToolchain = record(semantic['leanToolchain'], `${location} Lean toolchain`);
  exactKeys(leanToolchain, ['identity', 'leanVersion', 'lakeVersion'], `${location} Lean toolchain`);
  const modules = array(semantic['modules'], `${location} modules`).map((module, index) =>
    decodeModuleIdentity(module, `${location} modules[${index}]`),
  );
  if (modules.length === 0) throw new TypeError(`${location} modules must be nonempty`);
  requireCanonicalOrder(
    modules.map((module) => module.path),
    `${location} module paths`,
  );
  const closure = array(semantic['closure'], `${location} closure`).map((entry, index) =>
    decodeClosureEntry(entry, `${location} closure[${index}]`),
  );
  requireCanonicalOrder(
    closure.map((entry) => entry.declaration),
    `${location} closure declarations`,
  );
  return {
    fragmentVersion: string(semantic['fragmentVersion'], `${location} fragment version`),
    entryModule: string(semantic['entryModule'], `${location} entry module`),
    declarations,
    leanToolchain: {
      identity: string(leanToolchain['identity'], `${location} toolchain identity`),
      leanVersion: string(leanToolchain['leanVersion'], `${location} Lean version`),
      lakeVersion: string(leanToolchain['lakeVersion'], `${location} Lake version`),
    },
    modules,
    closure,
    ...decodeInputClosure(semantic, 'semantic', location),
    semanticIrSha256: digest(semantic['semanticIrSha256'], `${location} semantic IR`),
    generatedBodySha256: digest(semantic['generatedBodySha256'], `${location} generated body`),
  };
}

function decodeModuleIdentity(value: unknown, location: string): LeanToTypeScriptModuleIdentity {
  const module = record(value, location);
  exactKeys(module, ['path', 'leanModule', 'imports', 'declarations', 'bodySha256', 'sourceMapSha256'], location);
  const imports = array(module['imports'], `${location} imports`).map((entry, index) =>
    generatedPath(entry, `${location} imports[${index}]`),
  );
  requireCanonicalOrder(imports, `${location} imports`);
  const declarations = array(module['declarations'], `${location} declarations`).map((entry, index) =>
    decodeGeneratedDeclaration(entry, `${location} declarations[${index}]`),
  );
  const sourceMapSha256 = module['sourceMapSha256'];
  return {
    path: generatedPath(module['path'], `${location} path`),
    leanModule: optionalName(module['leanModule'], `${location} Lean module`),
    imports,
    declarations,
    bodySha256: digest(module['bodySha256'], `${location} body digest`),
    sourceMapSha256: sourceMapSha256 === '' ? '' : digest(sourceMapSha256, `${location} source map digest`),
  };
}

function decodeGeneratedDeclaration(value: unknown, location: string): LeanToTypeScriptGeneratedDeclaration {
  const declaration = record(value, location);
  exactKeys(declaration, ['declaration', 'emitted', 'line', 'span'], location);
  return {
    declaration: string(declaration['declaration'], `${location} declaration`),
    emitted: string(declaration['emitted'], `${location} emitted name`),
    line: position(declaration['line'], `${location} line`),
    span: decodeSourceSpan(declaration['span'], `${location} span`),
  };
}

function decodeSourceSpan(value: unknown, location: string): LeanToTypeScriptSourceSpan {
  const span = record(value, location);
  exactKeys(span, ['source', 'startLine', 'startColumn', 'endLine', 'endColumn'], location);
  return {
    source: string(span['source'], `${location} source`),
    startLine: position(span['startLine'], `${location} start line`),
    startColumn: offset(span['startColumn'], `${location} start column`),
    endLine: position(span['endLine'], `${location} end line`),
    endColumn: offset(span['endColumn'], `${location} end column`),
  };
}

function decodeClosureEntry(value: unknown, location: string): LeanToTypeScriptClosureEntry {
  const entry = record(value, location);
  exactKeys(entry, ['declaration', 'module', 'role', 'reason'], location);
  const role = declarationRole(entry['role'], `${location} role`);
  const reason = entry['reason'];
  if (typeof reason !== 'string') throw new TypeError(`${location} reason must be a string`);
  if ((role === 'emitted') !== (reason === '')) {
    throw new TypeError(`${location} reason must be empty exactly for an emitted declaration`);
  }
  return {
    declaration: string(entry['declaration'], `${location} declaration`),
    module: optionalName(entry['module'], `${location} module`),
    role,
    reason,
  };
}

function declarationRole(value: unknown, location: string): LeanToTypeScriptDeclarationRole {
  switch (value) {
    case 'emitted':
    case 'erased':
    case 'runtime-boundary':
      return value;
    default:
      throw new TypeError(`${location} has unknown role ${String(value)}`);
  }
}

function decodeEnvironmentAttestation(value: unknown): LeanToTypeScriptEnvironmentAttestation {
  const location = 'Lean to TypeScript manifest environment attestation';
  const environment = record(value, location);
  exactKeys(environment, ['runtime', 'typescriptVersion', 'platform', 'inputs', 'inputClosureSha256'], location);
  return {
    runtime: string(environment['runtime'], `${location} runtime`),
    typescriptVersion: string(environment['typescriptVersion'], `${location} TypeScript version`),
    platform: string(environment['platform'], `${location} platform`),
    ...decodeInputClosure(environment, 'environment', location),
  };
}

function decodeInputClosure(
  value: Record<string, unknown>,
  plane: LeanToTypeScriptPlane,
  location: string,
): { readonly inputs: readonly LeanToTypeScriptInput[]; readonly inputClosureSha256: string } {
  const inputs = array(value['inputs'], `${location} inputs`).map((input, index) =>
    decodeInput(input, `${location} inputs[${index}]`),
  );
  if (inputs.length === 0) throw new TypeError(`${location} inputs must be nonempty`);
  requireCanonicalOrder(
    inputs.map((input) => input.identity),
    `${location} input identities`,
  );
  for (const input of inputs) {
    if (LEAN_TO_TYPESCRIPT_INPUT_PLANES[input.kind] !== plane) {
      throw new TypeError(`${location} input ${input.identity} belongs to the other identity plane`);
    }
  }
  const inputClosureSha256 = digest(value['inputClosureSha256'], `${location} input closure`);
  if (sha256(JSON.stringify(inputs)) !== inputClosureSha256) {
    throw new TypeError(`${location} input closure does not match its inputs`);
  }
  return { inputs, inputClosureSha256 };
}

function decodeInput(value: unknown, location: string): LeanToTypeScriptInput {
  const input = record(value, location);
  exactKeys(input, ['kind', 'identity', 'sha256'], location);
  return {
    kind: inputKind(input['kind'], `${location} kind`),
    identity: string(input['identity'], `${location} identity`),
    sha256: digest(input['sha256'], `${location} digest`),
  };
}

function record(value: unknown, location: string): Record<string, unknown> {
  if (!isRecord(value)) throw new TypeError(`${location} must be an object`);
  return value;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function array(value: unknown, location: string): readonly unknown[] {
  if (!Array.isArray(value)) throw new TypeError(`${location} must be an array`);
  return value;
}

function string(value: unknown, location: string): string {
  if (typeof value !== 'string' || value.length === 0) throw new TypeError(`${location} must be a nonempty string`);
  return value;
}

function inputKind(value: unknown, location: string): LeanToTypeScriptInputKind {
  switch (value) {
    case 'compiler-runtime':
    case 'compiler-source':
    case 'lean-module':
    case 'lean-project':
    case 'lean-source':
    case 'lean-toolchain':
      return value;
    default:
      throw new TypeError(`${location} has unknown kind ${String(value)}`);
  }
}

function strings(value: unknown, location: string): readonly string[] {
  const values = array(value, location).map((entry, index) => string(entry, `${location}[${index}]`));
  if (values.length === 0) throw new TypeError(`${location} must be nonempty`);
  return values;
}

function digest(value: unknown, location: string): string {
  const hash = string(value, location);
  if (!/^sha256:[0-9a-f]{64}$/u.test(hash)) throw new TypeError(`${location} must be a SHA-256 digest`);
  return hash;
}

/**
 * A path inside the generated package: relative, forward-slashed, and free of `.` or `..`, so a
 * manifest can never name a destination outside the tree the compiler was asked to write.
 */
function generatedPath(value: unknown, location: string): string {
  const path = string(value, location);
  const segments = path.split('/');
  if (path.startsWith('/') || segments.some((segment) => segment === '' || segment === '.' || segment === '..')) {
    throw new TypeError(`${location} must be a relative path inside the generated package: ${path}`);
  }
  return path;
}

/** A name the schema allows to be absent, recorded as the empty string rather than omitted. */
function optionalName(value: unknown, location: string): string {
  if (value === '') return '';
  return string(value, location);
}

function position(value: unknown, location: string): number {
  if (!Number.isSafeInteger(value) || Number(value) < 1) throw new TypeError(`${location} must be a 1-based line`);
  return Number(value);
}

function offset(value: unknown, location: string): number {
  if (!Number.isSafeInteger(value) || Number(value) < 0) throw new TypeError(`${location} must be a column offset`);
  return Number(value);
}

function exactKeys(value: Record<string, unknown>, expected: readonly string[], location: string): void {
  const actual = Object.keys(value).sort(compareCodePoints);
  const canonical = [...expected].sort(compareCodePoints);
  if (actual.length !== canonical.length || actual.some((key, index) => key !== canonical[index])) {
    throw new TypeError(`${location} fields must be exactly ${canonical.join(', ')}`);
  }
}

function requireCanonicalOrder(values: readonly string[], location: string): void {
  for (let index = 1; index < values.length; index += 1) {
    const previous = values[index - 1];
    const current = values[index];
    if (previous === undefined || current === undefined || compareCodePoints(previous, current) >= 0) {
      throw new TypeError(`${location} must be strictly ordered and unique`);
    }
  }
}
