import { createHash } from 'node:crypto';
import {
  LEAN_TO_TYPESCRIPT_INPUT_PLANES,
  type LeanToTypeScriptArtifact,
  type LeanToTypeScriptEnvironmentAttestation,
  type LeanToTypeScriptInput,
  type LeanToTypeScriptInputKind,
  type LeanToTypeScriptManifest,
  type LeanToTypeScriptPlane,
  type LeanToTypeScriptSemanticIdentity,
} from './artifact.js';
import { compareCodePoints } from './ordering.js';

export const LEAN_TO_TYPESCRIPT_MANIFEST_SCHEMA_VERSION = 2;

/**
 * The provenance header carries the semantic identity only. Nothing about the machine that
 * ran the compiler appears in the generated bytes, so re-running the same compiler over the
 * same Lean sources under a different runtime reproduces the artifact byte for byte.
 */
export function provenanceHeader(manifest: LeanToTypeScriptManifest): string {
  const semantic = canonicalSemanticIdentity(manifest.semantic);
  return [
    '/*',
    ' * Generated by TSLean from a kernel-checked Lean declaration.',
    ` * Fragment: ${semantic.fragmentVersion}`,
    ` * Source module: ${semantic.sourceModule}`,
    ` * Semantic identity: ${semanticIdentityDigest(semantic)}`,
    ` * Input closure: ${semantic.inputClosureSha256}`,
    ` * Semantic IR: ${semantic.semanticIrSha256}`,
    ` * Generated body: ${semantic.generatedBodySha256}`,
    ` * Lean toolchain: ${semantic.leanToolchain.identity}`,
    ` * Lean: ${semantic.leanToolchain.leanVersion}`,
    ` * Lake: ${semantic.leanToolchain.lakeVersion}`,
    ' * Environment attestation: recorded in the manifest sidecar; it does not affect these bytes.',
    ' * Evidence boundary: generation is checked and differential tests are empirical; no refinement theorem is claimed.',
    ' */',
    '',
  ].join('\n');
}

export function semanticIdentityDigest(semantic: LeanToTypeScriptSemanticIdentity): string {
  return sha256(JSON.stringify(canonicalSemanticIdentity(semantic)));
}

export function environmentAttestationDigest(environment: LeanToTypeScriptEnvironmentAttestation): string {
  return sha256(JSON.stringify(canonicalEnvironmentAttestation(environment)));
}

export function canonicalManifest(manifest: LeanToTypeScriptManifest): LeanToTypeScriptManifest {
  return {
    schemaVersion: LEAN_TO_TYPESCRIPT_MANIFEST_SCHEMA_VERSION,
    semantic: canonicalSemanticIdentity(manifest.semantic),
    environment: canonicalEnvironmentAttestation(manifest.environment),
  };
}

export function verifyLeanToTypeScriptArtifact(value: unknown): asserts value is LeanToTypeScriptArtifact {
  const artifact = decodeArtifact(value);
  const header = provenanceHeader(artifact.manifest);
  if (!artifact.code.startsWith(header)) {
    throw new TypeError('generated TypeScript provenance header does not match its manifest');
  }
  const body = artifact.code.slice(header.length);
  if (sha256(body) !== artifact.manifest.semantic.generatedBodySha256) {
    throw new TypeError('generated TypeScript body does not match its manifest');
  }
}

/** Which recorded environment fields drifted from the environment that just ran. */
export function environmentAttestationDrift(
  recorded: LeanToTypeScriptEnvironmentAttestation,
  observed: LeanToTypeScriptEnvironmentAttestation,
): readonly string[] {
  const drift: string[] = [];
  if (recorded.runtime !== observed.runtime) drift.push(`runtime ${recorded.runtime} -> ${observed.runtime}`);
  if (recorded.typescriptVersion !== observed.typescriptVersion) {
    drift.push(`typescript ${recorded.typescriptVersion} -> ${observed.typescriptVersion}`);
  }
  if (recorded.platform !== observed.platform) drift.push(`platform ${recorded.platform} -> ${observed.platform}`);
  const observedInputs = new Map(observed.inputs.map((input) => [input.identity, input.sha256]));
  for (const input of recorded.inputs) {
    const current = observedInputs.get(input.identity);
    if (current === undefined) drift.push(`removed ${input.identity}`);
    else if (current !== input.sha256) drift.push(`changed ${input.identity}`);
  }
  const recordedInputs = new Set(recorded.inputs.map((input) => input.identity));
  for (const input of observed.inputs) {
    if (!recordedInputs.has(input.identity)) drift.push(`added ${input.identity}`);
  }
  return drift.sort(compareCodePoints);
}

function canonicalSemanticIdentity(semantic: LeanToTypeScriptSemanticIdentity): LeanToTypeScriptSemanticIdentity {
  return {
    fragmentVersion: semantic.fragmentVersion,
    sourceModule: semantic.sourceModule,
    declarations: semantic.declarations,
    leanToolchain: {
      identity: semantic.leanToolchain.identity,
      leanVersion: semantic.leanToolchain.leanVersion,
      lakeVersion: semantic.leanToolchain.lakeVersion,
    },
    inputs: semantic.inputs,
    inputClosureSha256: semantic.inputClosureSha256,
    semanticIrSha256: semantic.semanticIrSha256,
    generatedBodySha256: semantic.generatedBodySha256,
  };
}

function canonicalEnvironmentAttestation(
  environment: LeanToTypeScriptEnvironmentAttestation,
): LeanToTypeScriptEnvironmentAttestation {
  return {
    runtime: environment.runtime,
    typescriptVersion: environment.typescriptVersion,
    platform: environment.platform,
    inputs: environment.inputs,
    inputClosureSha256: environment.inputClosureSha256,
  };
}

function sha256(value: string): string {
  return `sha256:${createHash('sha256').update(value).digest('hex')}`;
}

export function decodeArtifact(value: unknown): LeanToTypeScriptArtifact {
  const artifact = record(value, 'Lean to TypeScript artifact');
  exactKeys(artifact, ['code', 'manifest'], 'Lean to TypeScript artifact');
  return {
    code: string(artifact['code'], 'Lean to TypeScript artifact code'),
    manifest: decodeManifest(artifact['manifest']),
  };
}

export function decodeManifest(value: unknown): LeanToTypeScriptManifest {
  const manifest = record(value, 'Lean to TypeScript manifest');
  exactKeys(manifest, ['schemaVersion', 'semantic', 'environment'], 'Lean to TypeScript manifest');
  if (manifest['schemaVersion'] !== LEAN_TO_TYPESCRIPT_MANIFEST_SCHEMA_VERSION) {
    throw new TypeError('unsupported Lean to TypeScript manifest schema');
  }
  return canonicalManifest({
    schemaVersion: LEAN_TO_TYPESCRIPT_MANIFEST_SCHEMA_VERSION,
    semantic: decodeSemanticIdentity(manifest['semantic']),
    environment: decodeEnvironmentAttestation(manifest['environment']),
  });
}

function decodeSemanticIdentity(value: unknown): LeanToTypeScriptSemanticIdentity {
  const location = 'Lean to TypeScript manifest semantic identity';
  const semantic = record(value, location);
  exactKeys(
    semantic,
    [
      'fragmentVersion',
      'sourceModule',
      'declarations',
      'leanToolchain',
      'inputs',
      'inputClosureSha256',
      'semanticIrSha256',
      'generatedBodySha256',
    ],
    location,
  );
  const declarations = strings(semantic['declarations'], `${location} declarations`);
  requireCanonicalOrder(declarations, `${location} declarations`);
  const leanToolchain = record(semantic['leanToolchain'], `${location} Lean toolchain`);
  exactKeys(leanToolchain, ['identity', 'leanVersion', 'lakeVersion'], `${location} Lean toolchain`);
  return {
    fragmentVersion: string(semantic['fragmentVersion'], `${location} fragment version`),
    sourceModule: string(semantic['sourceModule'], `${location} source module`),
    declarations,
    leanToolchain: {
      identity: string(leanToolchain['identity'], `${location} toolchain identity`),
      leanVersion: string(leanToolchain['leanVersion'], `${location} Lean version`),
      lakeVersion: string(leanToolchain['lakeVersion'], `${location} Lake version`),
    },
    ...decodeInputClosure(semantic, 'semantic', location),
    semanticIrSha256: digest(semantic['semanticIrSha256'], `${location} semantic IR`),
    generatedBodySha256: digest(semantic['generatedBodySha256'], `${location} generated body`),
  };
}

function decodeEnvironmentAttestation(value: unknown): LeanToTypeScriptEnvironmentAttestation {
  const location = 'Lean to TypeScript manifest environment attestation';
  const environment = record(value, location);
  exactKeys(environment, ['runtime', 'typescriptVersion', 'platform', 'inputs', 'inputClosureSha256'], location);
  return {
    runtime: string(environment['runtime'], `${location} runtime`),
    typescriptVersion: string(environment['typescriptVersion'], `${location} TypeScript version`),
    platform: string(environment['platform'], `${location} platform`),
    ...decodeInputClosure(environment, 'environment', location),
  };
}

function decodeInputClosure(
  value: Record<string, unknown>,
  plane: LeanToTypeScriptPlane,
  location: string,
): { readonly inputs: readonly LeanToTypeScriptInput[]; readonly inputClosureSha256: string } {
  const inputs = array(value['inputs'], `${location} inputs`).map((input, index) =>
    decodeInput(input, `${location} inputs[${index}]`),
  );
  if (inputs.length === 0) throw new TypeError(`${location} inputs must be nonempty`);
  requireCanonicalOrder(
    inputs.map((input) => input.identity),
    `${location} input identities`,
  );
  for (const input of inputs) {
    if (LEAN_TO_TYPESCRIPT_INPUT_PLANES[input.kind] !== plane) {
      throw new TypeError(`${location} input ${input.identity} belongs to the other identity plane`);
    }
  }
  const inputClosureSha256 = digest(value['inputClosureSha256'], `${location} input closure`);
  if (sha256(JSON.stringify(inputs)) !== inputClosureSha256) {
    throw new TypeError(`${location} input closure does not match its inputs`);
  }
  return { inputs, inputClosureSha256 };
}

function decodeInput(value: unknown, location: string): LeanToTypeScriptInput {
  const input = record(value, location);
  exactKeys(input, ['kind', 'identity', 'sha256'], location);
  return {
    kind: inputKind(input['kind'], `${location} kind`),
    identity: string(input['identity'], `${location} identity`),
    sha256: digest(input['sha256'], `${location} digest`),
  };
}

function record(value: unknown, location: string): Record<string, unknown> {
  if (!isRecord(value)) throw new TypeError(`${location} must be an object`);
  return value;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function array(value: unknown, location: string): readonly unknown[] {
  if (!Array.isArray(value)) throw new TypeError(`${location} must be an array`);
  return value;
}

function string(value: unknown, location: string): string {
  if (typeof value !== 'string' || value.length === 0) throw new TypeError(`${location} must be a nonempty string`);
  return value;
}

function inputKind(value: unknown, location: string): LeanToTypeScriptInputKind {
  switch (value) {
    case 'compiler-runtime':
    case 'compiler-source':
    case 'lean-module':
    case 'lean-project':
    case 'lean-source':
    case 'lean-toolchain':
      return value;
    default:
      throw new TypeError(`${location} has unknown kind ${String(value)}`);
  }
}

function strings(value: unknown, location: string): readonly string[] {
  const values = array(value, location).map((entry, index) => string(entry, `${location}[${index}]`));
  if (values.length === 0) throw new TypeError(`${location} must be nonempty`);
  return values;
}

function digest(value: unknown, location: string): string {
  const hash = string(value, location);
  if (!/^sha256:[0-9a-f]{64}$/u.test(hash)) throw new TypeError(`${location} must be a SHA-256 digest`);
  return hash;
}

function exactKeys(value: Record<string, unknown>, expected: readonly string[], location: string): void {
  const actual = Object.keys(value).sort(compareCodePoints);
  const canonical = [...expected].sort(compareCodePoints);
  if (actual.length !== canonical.length || actual.some((key, index) => key !== canonical[index])) {
    throw new TypeError(`${location} fields must be exactly ${canonical.join(', ')}`);
  }
}

function requireCanonicalOrder(values: readonly string[], location: string): void {
  for (let index = 1; index < values.length; index += 1) {
    const previous = values[index - 1];
    const current = values[index];
    if (previous === undefined || current === undefined || compareCodePoints(previous, current) >= 0) {
      throw new TypeError(`${location} must be strictly ordered and unique`);
    }
  }
}
