-- Auto-generated by ts-lean-transpiler
-- Source: /workspace/tslean-ex/examples/01-hello-world/hello.ts

import TSLean.Runtime.Basic
import TSLean.Runtime.Coercions

open TSLean

namespace TSLean.Generated.Hello

-- // 01-hello-world/hello.ts
-- // The simplest TSLean example: pure functions that map directly to Lean 4.
-- //
-- // Run: npx tsx src/cli.ts examples/01-hello-world/hello.ts -o output.lean
-- // Pure function → def greet : String
def greet (name : String) : String := s!"Hello, {name}!"

-- // Numeric computation → def add : Float → Float → Float
def add (a : Float) (b : Float) : Float := a + b

-- // Boolean logic → def isPositive : Float → Bool
def isPositive (x : Float) : Bool := x > 0

def pi : Float := 3.14159

def greeting : String := greet "world"

end TSLean.Generated.Hello