/*
 * Generated by TSLean from a kernel-checked Lean declaration.
 * Fragment: tslean-structural-first-order-v4
 * Source module: AgentCore.Facets.Enforcement
 * Semantic identity: sha256:2a2037eb66cfa3c79a070095582cf0a1a82bddb44a032b393382702f9ece395e
 * Input closure: sha256:120465166908a2f61f2dc025ca9057014e8b52b414cfd3d9dabb6fdfd6c1422b
 * Semantic IR: sha256:f412c9e3b6b69101b752d289fea38c6ce1373634ca5c89c6597f2d3c1b17b9b1
 * Generated body: sha256:fba73201f5d9a31aa72e8ce13994589b32a653bebd308a42b94c1ec860498e25
 * Lean toolchain: leanprover/lean4:v4.29.0
 * Lean: Lean (version 4.29.0, x86_64-unknown-linux-gnu, commit 98dc76e3c0a9b856c9b98726b713fb04fab16740, Release)
 * Lake: Lake version 5.0.0-src+98dc76e (Lean version 4.29.0)
 * Environment attestation: recorded in the manifest sidecar; it does not affect these bytes.
 * Evidence boundary: generation is checked and differential tests are empirical; no refinement theorem is claimed.
 */
/**
 * Which enforcement tier serves a call (SPEC §7.2). Only `mediated` carries evidence: a
 * direct call performs its authority, lease, watermark, PathEpochEvidence, and deadline
 * checks in memory and writes nothing durable, so there is no Invocation for it to name.
 */
export type EnforcementTier = "direct" | "mediated";

export type ImpactData = Impact["kind"];

/**
 * The impact an Operation declares, and the seam its request crosses (SPEC §4.2, §7.1).
 * The host derives impact from the seam, never from what the callee claims about itself.
 */
export abstract class Impact {
    public static get observe(): Impact {
        return observeImpact;
    }
    public static get mutate(): Impact {
        return mutateImpact;
    }
    public static get externalSend(): Impact {
        return externalSendImpact;
    }
    public static get execute(): Impact {
        return executeImpact;
    }
    public static get delegate(): Impact {
        return delegateImpact;
    }
    public static get administer(): Impact {
        return administerImpact;
    }
    public static from(kind: Impact["kind"]): Impact {
        switch (kind) {
            case "observe": return Impact.observe;
            case "mutate": return Impact.mutate;
            case "externalSend": return Impact.externalSend;
            case "execute": return Impact.execute;
            case "delegate": return Impact.delegate;
            case "administer": return Impact.administer;
        }
    }
    public static fromData(value: unknown): Impact {
        if (typeof value !== "string") {
            throw new TypeError("Impact data must be a string");
        }
        switch (value) {
            case "observe": return Impact.observe;
            case "mutate": return Impact.mutate;
            case "externalSend": return Impact.externalSend;
            case "execute": return Impact.execute;
            case "delegate": return Impact.delegate;
            case "administer": return Impact.administer;
            default: throw new TypeError("Impact data must name a constructor");
        }
    }
    public abstract readonly kind: "observe" | "mutate" | "externalSend" | "execute" | "delegate" | "administer";
    /**
     * Whether this impact may ever be served directly (SPEC §7.2): `observe` always may;
     * `execute` only inside a Turn-owned Session; `mutate` only against that Session's own
     * filesystem; `externalSend`, `delegate`, and `administer` never may.
     */
    public abstract admitsDirect(turnOwnedSession: boolean, sessionFilesystemTarget: boolean): boolean;
    /**
     * SPEC §7.1 (C13-POLICY-IMPACT-BOUNDARY): a callee's own claim may replace the derived
     * impact only when it never admits a floor (§7.2) the derived impact would have mediated.
     * Checked under both Turn-owned-Session conditions, because a claim recorded once — at
     * discovery or install time — has to hold safe at every call site it is later used at.
     * `sessionFilesystemTarget` is fixed per caller: pass `false` for a seam whose target is
     * never a Turn-owned Session's own filesystem.
     */
    public claimHonorsEnforcementFloor(derived: Impact, sessionFilesystemTarget: boolean): boolean {
        return honorsFloorUnder(this, derived, true, sessionFilesystemTarget) && honorsFloorUnder(this, derived, false, sessionFilesystemTarget);
    }
    /**
     * SPEC §7.2's enforcement floor: the weakest tier this impact admits under the given
     * session conditions. Policy only tightens this floor; it never lowers it.
     */
    public enforcementFloor(turnOwnedSession: boolean, sessionFilesystemTarget: boolean): EnforcementTier {
        return this.admitsDirect(turnOwnedSession, sessionFilesystemTarget) ? "direct" : "mediated";
    }
    public toData(): ImpactData {
        return this.kind;
    }
    public equals(other: Impact): boolean {
        return this === other;
    }
}

class ObserveImpact extends Impact {
    public readonly kind = "observe" as const;
    public override admitsDirect(): boolean {
        return true;
    }
}

class MutateImpact extends Impact {
    public readonly kind = "mutate" as const;
    public override admitsDirect(turnOwnedSession: boolean, sessionFilesystemTarget: boolean): boolean {
        return turnOwnedSession && sessionFilesystemTarget;
    }
}

class ExternalSendImpact extends Impact {
    public readonly kind = "externalSend" as const;
    public override admitsDirect(): boolean {
        return false;
    }
}

class ExecuteImpact extends Impact {
    public readonly kind = "execute" as const;
    public override admitsDirect(turnOwnedSession: boolean): boolean {
        return turnOwnedSession;
    }
}

class DelegateImpact extends Impact {
    public readonly kind = "delegate" as const;
    public override admitsDirect(): boolean {
        return false;
    }
}

class AdministerImpact extends Impact {
    public readonly kind = "administer" as const;
    public override admitsDirect(): boolean {
        return false;
    }
}

const observeImpact = new ObserveImpact();

const mutateImpact = new MutateImpact();

const externalSendImpact = new ExternalSendImpact();

const executeImpact = new ExecuteImpact();

const delegateImpact = new DelegateImpact();

const administerImpact = new AdministerImpact();

/**
 * Whether a claim honors the derived impact's floor under one fixed session condition: the
 * claim is admissible unless it would be served directly where the derived impact would
 * have been mediated.
 */
function honorsFloorUnder(claimed: Impact, derived: Impact, turnOwnedSession: boolean, sessionFilesystemTarget: boolean): boolean {
    return !claimed.admitsDirect(turnOwnedSession, sessionFilesystemTarget) || derived.admitsDirect(turnOwnedSession, sessionFilesystemTarget);
}
