-- TSLean: TypeScript → Lean 4 Runtime Library

-- Runtime
import TSLean.Runtime.Basic
import TSLean.Runtime.Monad
import TSLean.Runtime.Coercions
import TSLean.Runtime.BrandedTypes
import TSLean.Runtime.Validation
import TSLean.Runtime.WebAPI
import TSLean.Runtime.Inhabited

-- Stdlib
import TSLean.Stdlib.Array
import TSLean.Stdlib.HashMap
import TSLean.Stdlib.HashSet
import TSLean.Stdlib.String
import TSLean.Stdlib.Numeric
import TSLean.Stdlib.OptionResult

-- Effects
import TSLean.Effects.Core
import TSLean.Effects.Transformer

-- DurableObjects
import TSLean.DurableObjects.Model
import TSLean.DurableObjects.Storage
import TSLean.DurableObjects.State
import TSLean.DurableObjects.Transaction
import TSLean.DurableObjects.WebSocket
import TSLean.DurableObjects.Alarm
import TSLean.DurableObjects.RPC
import TSLean.DurableObjects.Hibernation
import TSLean.DurableObjects.RateLimiter
import TSLean.DurableObjects.ChatRoom
import TSLean.DurableObjects.SessionStore
import TSLean.DurableObjects.Queue
import TSLean.DurableObjects.Auth
import TSLean.DurableObjects.Analytics
import TSLean.DurableObjects.MultiDO
import TSLean.DurableObjects.Http

-- Verification
import TSLean.Verification.ProofObligation
import TSLean.Verification.Invariants
import TSLean.Verification.Tactics

-- Generated (hand-written)
import TSLean.Generated.Hello
import TSLean.Generated.Interfaces
import TSLean.Generated.Classes
import TSLean.Generated.CounterDO
import TSLean.Generated.RateLimiter
import TSLean.Generated.ChatRoom
import TSLean.Generated.SessionStore
import TSLean.Generated.QueueProcessor
import TSLean.Generated.FullProject.Shared.Types
import TSLean.Generated.FullProject.Shared.Validators
import TSLean.Generated.FullProject.Backend.AuthDo
import TSLean.Generated.FullProject.Backend.ChatRoomDo
import TSLean.Generated.FullProject.Backend.RateLimiterDo
import TSLean.Generated.FullProject.Backend.AnalyticsDo
import TSLean.Generated.FullProject.Backend.Router

-- Transpiler output (compiles with lake build — separate namespace from hand-written)
-- Note: not imported here to avoid name clashes with hand-written Generated/ files.
-- Import individually: `import TSLean.Generated.Basic.Hello` etc.
-- TODO: merge hand-written and transpiler-generated into single namespace

-- Veil Transition Systems
import TSLean.Veil.Core
import TSLean.Veil.DSL
import TSLean.Veil.DSLExamples
import TSLean.Veil.DSLAdoption
import TSLean.Veil.AuthDO
import TSLean.Veil.ChatRoomDO
import TSLean.Veil.CounterDO
import TSLean.Veil.QueueDO
import TSLean.Veil.RateLimiterDO
import TSLean.Veil.SessionStoreDO

-- External stubs (TS compiler API, Node.js path/fs)
import TSLean.External.Typescript
import TSLean.External.Path
import TSLean.External.Fs

-- Self-hosting (hand-fixed transpiler output)
import TSLean.Generated.SelfHost.IR_Types
import TSLean.Generated.SelfHost.DoModel_Ambient
-- Note: verification_index et al. are actively regenerated by the transpiler.
-- Import them individually after stabilization.

-- Specification & Tests
import TSLean.Specification
import TSLean.Tests
